import type { SideTapGameConfig } from '@/components/game/occupational/level4/session8/shared/SideTapGame';

export const ODD_EVEN_TAP_THEME = {
  title: 'Odd Even Tap',
  subtitle: 'Odd numbers → left! Even numbers → right!',
  emoji: '🔢',
  gradient: ['#450A0A', '#7F1D1D', '#1E3A8A', '#3B82F6'] as [string, string, string, string],
  accent: '#FB7185',
  accentDark: '#FECDD3',
  oddGlow: '#EF4444',
  evenGlow: '#60A5FA',
  leftColor: '#EF4444',
  rightColor: '#3B82F6',
  leftIcon: '1️⃣',
  rightIcon: '2️⃣',
  playBorder: 'rgba(251,113,133,0.42)',
  playBg: '#1A0A14',
  sparkleColor: '#FB7185',
  backText: '#FEE2E2',
  backBorder: 'rgba(251,113,133,0.38)',
  titleColor: '#FFF1F2',
  subtitleColor: 'rgba(254,205,211,0.9)',
  statLabel: 'rgba(254,205,211,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,113,133,0.32)',
  voiceIntro:
    'Welcome to the split brain challenge! Odd numbers mean tap left, even numbers mean tap right!',
  voiceCue: 'Odd left, even right — read the number fast!',
  voiceComplete: 'Brain and body linked! You mastered odd and even sides!',
  voiceSuccess: 'Perfect match!',
  voiceMiss: 'Too slow — read the number and tap!',
  voiceWrong: 'Check odd or even — tap the right side!',
  congrats: 'Odd Even Tap Champion!',
} as const;

export const ODD_EVEN_TAP_CONFIG: Omit<SideTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'count',
  theme: {
    title: ODD_EVEN_TAP_THEME.title,
    subtitle: ODD_EVEN_TAP_THEME.subtitle,
    emoji: ODD_EVEN_TAP_THEME.emoji,
    gradient: ODD_EVEN_TAP_THEME.gradient,
    accent: ODD_EVEN_TAP_THEME.accent,
    accentDark: ODD_EVEN_TAP_THEME.accentDark,
    leftColor: ODD_EVEN_TAP_THEME.leftColor,
    rightColor: ODD_EVEN_TAP_THEME.rightColor,
    leftIcon: ODD_EVEN_TAP_THEME.leftIcon,
    rightIcon: ODD_EVEN_TAP_THEME.rightIcon,
    backText: ODD_EVEN_TAP_THEME.backText,
    backBorder: ODD_EVEN_TAP_THEME.backBorder,
    titleColor: ODD_EVEN_TAP_THEME.titleColor,
    subtitleColor: ODD_EVEN_TAP_THEME.subtitleColor,
    statLabel: ODD_EVEN_TAP_THEME.statLabel,
    statValue: ODD_EVEN_TAP_THEME.statValue,
    statBorder: ODD_EVEN_TAP_THEME.statBorder,
    playBorder: ODD_EVEN_TAP_THEME.playBorder,
    playBg: ODD_EVEN_TAP_THEME.playBg,
    sparkleColor: ODD_EVEN_TAP_THEME.sparkleColor,
  },
  ttsIntro: ODD_EVEN_TAP_THEME.voiceIntro,
  ttsComplete: ODD_EVEN_TAP_THEME.voiceComplete,
  ttsCue: ODD_EVEN_TAP_THEME.voiceCue,
  ttsSuccess: ODD_EVEN_TAP_THEME.voiceSuccess,
  ttsMiss: ODD_EVEN_TAP_THEME.voiceMiss,
  ttsWrong: ODD_EVEN_TAP_THEME.voiceWrong,
  congratsMessage: ODD_EVEN_TAP_THEME.congrats,
  logType: 'count-and-tap',
  skillTags: ['cognitive-motor-link', 'number-recognition', 'alternating-sides'],
};
