import type { ReversePathDragGameConfig } from '@/components/game/occupational/level4/session2/shared/ReversePathDragGame';

export const BACK_TRACK_THEME = {
  title: 'Back Track',
  subtitle: 'Follow the glowing trail from the forest edge back home',
  emoji: '🛤️',
  gradient: ['#042F2E', '#0F766E', '#14B8A6', '#2DD4BF'] as [string, string, string, string],
  accent: '#A3E635',
  accentDark: '#65A30D',
  accentAmber: '#FBBF24',
  forestDark: '#042F2E',
  forestMid: '#134E4A',
  pathGlow: '#A3E635',
  pathCore: '#84CC16',
  moss: '#166534',
  lantern: '#FDE68A',
  draggableEmoji: '📦',
  backText: '#CCFBF1',
  backBorder: 'rgba(45,212,191,0.35)',
  titleColor: '#F0FDFA',
  subtitleColor: 'rgba(153,246,228,0.9)',
  statLabel: 'rgba(153,246,228,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(45,212,191,0.3)',
  playBorder: 'rgba(163,230,53,0.42)',
  playBg: '#0C3530',
  sparkleColor: '#A3E635',
  pathColor: '#A3E635',
  voiceIntro: 'Welcome to the forest trail! Follow the glowing path from the right all the way back home on the left!',
  voiceDrag: 'Trace the trail back home!',
  voiceComplete: 'Trail master! You found your way home on every path!',
  voiceMiss: 'Stay on the glowing trail — reach the home camp!',
  voiceArrived: 'Home safe!',
  congrats: 'Trail Guide Legend!',
} as const;

export const BACK_TRACK_CONFIG: Omit<ReversePathDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'reversePath',
  theme: {
    title: BACK_TRACK_THEME.title,
    subtitle: BACK_TRACK_THEME.subtitle,
    emoji: BACK_TRACK_THEME.emoji,
    gradient: BACK_TRACK_THEME.gradient,
    accent: BACK_TRACK_THEME.accent,
    accentDark: BACK_TRACK_THEME.accentDark,
    pathColor: BACK_TRACK_THEME.pathColor,
    draggableEmoji: BACK_TRACK_THEME.draggableEmoji,
    backText: BACK_TRACK_THEME.backText,
    backBorder: BACK_TRACK_THEME.backBorder,
    titleColor: BACK_TRACK_THEME.titleColor,
    subtitleColor: BACK_TRACK_THEME.subtitleColor,
    statLabel: BACK_TRACK_THEME.statLabel,
    statValue: BACK_TRACK_THEME.statValue,
    statBorder: BACK_TRACK_THEME.statBorder,
    playBorder: BACK_TRACK_THEME.playBorder,
    playBg: BACK_TRACK_THEME.playBg,
    sparkleColor: BACK_TRACK_THEME.sparkleColor,
  },
  ttsIntro: BACK_TRACK_THEME.voiceIntro,
  ttsComplete: BACK_TRACK_THEME.voiceComplete,
  ttsDrag: BACK_TRACK_THEME.voiceDrag,
  ttsMiss: BACK_TRACK_THEME.voiceMiss,
  ttsGoal: BACK_TRACK_THEME.voiceArrived,
  congratsMessage: BACK_TRACK_THEME.congrats,
  logType: 'reverse-path',
  skillTags: ['cognitive-flexibility', 'drag-right-left'],
};
