import type { HorizontalDragGameConfig } from '@/components/game/occupational/level4/session1/shared/HorizontalDragGame';

export const LANE_CROSS_CARS = ['🚗', '🚙', '🚕', '🏎️'] as const;

export const LANE_CROSS_THEME = {
  title: 'Lane Cross',
  subtitle: 'Drive from the left lane across to the parking spot',
  emoji: '🚗',
  gradient: ['#0F172A', '#1E293B', '#334155', '#475569'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#0891B2',
  accentAmber: '#FBBF24',
  asphalt: '#1F2937',
  asphaltLight: '#374151',
  laneMark: 'rgba(253,224,71,0.85)',
  laneWhite: 'rgba(255,255,255,0.55)',
  neonCyan: '#22D3EE',
  neonPink: '#F472B6',
  skyline: '#111827',
  windowLit: '#FDE68A',
  draggableEmoji: '🚗',
  targetEmoji: '🅿️',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#111827',
  sparkleColor: '#22D3EE',
  zoneBorder: 'rgba(34,211,238,0.45)',
  voiceIntro: 'Welcome to the city! Drive your car from the left lane to the parking spot on the right!',
  voiceDrag: 'Steer across the highway to the parking zone!',
  voiceComplete: 'Perfect driving! You crossed every lane safely!',
  voiceMiss: 'Stay on the road — park in the right zone!',
  voiceSafe: 'Safe crossing!',
  congrats: 'Highway Hero!',
} as const;

export const LANE_CROSS_CONFIG: Omit<HorizontalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'roadCrossing',
  theme: {
    title: LANE_CROSS_THEME.title,
    subtitle: LANE_CROSS_THEME.subtitle,
    emoji: LANE_CROSS_THEME.emoji,
    gradient: LANE_CROSS_THEME.gradient,
    accent: LANE_CROSS_THEME.accent,
    accentDark: LANE_CROSS_THEME.accentDark,
    draggableEmoji: LANE_CROSS_THEME.draggableEmoji,
    targetEmoji: LANE_CROSS_THEME.targetEmoji,
    backText: '#E0F2FE',
    backBorder: 'rgba(34,211,238,0.35)',
    titleColor: '#F0F9FF',
    subtitleColor: 'rgba(186,230,253,0.9)',
    statLabel: 'rgba(186,230,253,0.75)',
    statValue: '#FFFFFF',
    statBorder: 'rgba(34,211,238,0.3)',
    playBorder: LANE_CROSS_THEME.playBorder,
    playBg: LANE_CROSS_THEME.playBg,
    sparkleColor: LANE_CROSS_THEME.sparkleColor,
    zoneBorder: LANE_CROSS_THEME.zoneBorder,
  },
  ttsIntro: LANE_CROSS_THEME.voiceIntro,
  ttsComplete: LANE_CROSS_THEME.voiceComplete,
  ttsDrag: LANE_CROSS_THEME.voiceDrag,
  ttsMiss: LANE_CROSS_THEME.voiceMiss,
  ttsGoal: LANE_CROSS_THEME.voiceSafe,
  congratsMessage: LANE_CROSS_THEME.congrats,
  logType: 'road-crossing',
  skillTags: ['spatial-planning', 'drag-left-right'],
};
