// Centralized AAC tile data and types

export type Tile = {
  id: string;
  label: string;
  lang?: string;
  imageKey?: string;
  emoji?: string;
  core?: boolean;
  imageUrl?: string;
};

export type Category = {
  id: 'transport' | 'food' | 'jobs' | 'emotions' | 'actions' | 'favorites' | 'mytiles';
  title: string;
  color?: string;
  tiles: Tile[];
};

export const tileImages: Record<string, any> = {
  // Use images that exist under assets/tiles/transport. Missing ones will fall back to emoji.
  car: require('../assets/tiles/transport/car.png'),
  bike: require('../assets/tiles/transport/bike.png'),
  bicycle: require('../assets/tiles/transport/bicycle.png'),
  train: require('../assets/tiles/transport/train.png'),
  bus: require('../assets/tiles/transport/bus.png'),
  plane: require('../assets/tiles/transport/plane.png'),
  boat: require('../assets/tiles/transport/boat.png'),
  ship: require('../assets/tiles/transport/ship.png'),
  taxi: require('../assets/tiles/transport/taxi.png'),
  truck: require('../assets/tiles/transport/truck.png'),
  van: require('../assets/tiles/transport/van.png'),
  helicopter: require('../assets/tiles/transport/helicopter.png'),
  submarine: require('../assets/tiles/transport/submarine.png'),
  rocket: require('../assets/tiles/transport/rocket.png'),
  tram: require('../assets/tiles/transport/tram.png'),
  metro: require('../assets/tiles/transport/metro.png'),
  scooter: require('../assets/tiles/transport/scooter.png'),
  ambulance: require('../assets/tiles/transport/ambulance.png'),
  policecar: require('../assets/tiles/transport/police car.png'),
  firetruck: require('../assets/tiles/transport/firetruck.png'),
  skateboard: require('../assets/tiles/transport/skateboard.png'),
  rollerskates: require('../assets/tiles/transport/rollerskates.png'),
  wheelchair: require('../assets/tiles/transport/wheelchair.png'),
  // apple: require('../assets/tiles/apple.png'),
  // Food images
  apple: require('../assets/tiles/food/Apple.png'),
  banana: require('../assets/tiles/food/Banana.png'),
  grapes: require('../assets/tiles/food/Grapes.png'),
  pineapple: require('../assets/tiles/food/Pineapple.png'),
  mango: require('../assets/tiles/food/Mango.png'),
  orange: require('../assets/tiles/food/Orange.png'),
  strawberry: require('../assets/tiles/food/Strawberry.png'),
  watermelon: require('../assets/tiles/food/Watermelon.png'),
  pear: require('../assets/tiles/food/Pear.png'),
  peach: require('../assets/tiles/food/Peach.png'),
  cherry: require('../assets/tiles/food/Cherry.png'),
  kiwi: require('../assets/tiles/food/Kiwi.png'),
  lemon: require('../assets/tiles/food/Lemon.png'),
  rice: require('../assets/tiles/food/Rice.png'),
  milk: require('../assets/tiles/food/Milk.png'),
  bread: require('../assets/tiles/food/Bread.png'),
  cheese: require('../assets/tiles/food/Cheeese.png'),
  egg: require('../assets/tiles/food/Eggs.png'),
  chicken: require('../assets/tiles/food/Chicken.png'),
  fish: require('../assets/tiles/food/Fish.png'),
  pizza: require('../assets/tiles/food/Pizza.png'),
  burger: require('../assets/tiles/food/Burger.png'),
  pasta: require('../assets/tiles/food/Pasta.png'),
  salad: require('../assets/tiles/food/Salad.png'),
  soup: require('../assets/tiles/food/Soup.png'),
  icecream: require('../assets/tiles/food/Icecream.png'),
  cake: require('../assets/tiles/food/Cake.png'),
  cookie: require('../assets/tiles/food/Cookie.png'),
  juice: require('../assets/tiles/food/Juice.png'),
  yogurt: require('../assets/tiles/food/Yogurt.png'),

  // Emotions images
  happy: require('../assets/tiles/emotions/happy.png'),
  sad: require('../assets/tiles/emotions/sad.png'),
  angry: require('../assets/tiles/emotions/angry.png'),
  tired: require('../assets/tiles/emotions/tired.png'),
  excited: require('../assets/tiles/emotions/excited.png'),
  scared: require('../assets/tiles/emotions/scared.png'),
  surprised: require('../assets/tiles/emotions/surprised.png'),
  calm: require('../assets/tiles/emotions/calm.png'),
  bored: require('../assets/tiles/emotions/bored.png'),
  confused: require('../assets/tiles/emotions/confused.png'),
  proud: require('../assets/tiles/emotions/proud.png'),
  shy: require('../assets/tiles/emotions/silly.png'),
  silly: require('../assets/tiles/emotions/silly.png'),
  frustrated: require('../assets/tiles/emotions/frustrated.png'),
  worried: require('../assets/tiles/emotions/worried.png'),
  sleepy: require('../assets/tiles/emotions/sleepy.png'),
  sick: require('../assets/tiles/emotions/sick.png'),
  brave: require('../assets/tiles/emotions/brave.png'),
  curious: require('../assets/tiles/emotions/curious.png'),
  embarrassed: require('../assets/tiles/emotions/embarrassed.png'),
  lonely: require('../assets/tiles/emotions/lonely.png'),
  hopeful: require('../assets/tiles/emotions/hopeful.png'),
  grateful: require('../assets/tiles/emotions/grateful.png'),
  confident: require('../assets/tiles/emotions/confident.png'),
  relaxed: require('../assets/tiles/emotions/relaxed.png'),
  annoyed: require('../assets/tiles/emotions/annoyed.png'),
  shocked: require('../assets/tiles/emotions/shocked.png'),

  // Professions images
  artist: require('../assets/tiles/professions/artist.png'),
  barber: require('../assets/tiles/professions/barber.png'),
  builder: require('../assets/tiles/professions/builder.png'),
  cashier: require('../assets/tiles/professions/cashier.png'),
  chef: require('../assets/tiles/professions/chef.png'),
  dancer: require('../assets/tiles/professions/dancer.png'),
  dentist: require('../assets/tiles/professions/dentist.png'),
  doctor: require('../assets/tiles/professions/doctor.png'),
  driver: require('../assets/tiles/professions/driver.png'),
  engineer: require('../assets/tiles/professions/engineer.png'),
  farmer: require('../assets/tiles/professions/farmer.png'),
  firefighter: require('../assets/tiles/professions/firefighter.png'),
  nurse: require('../assets/tiles/professions/Nurse.png'),
  photographer: require('../assets/tiles/professions/photographer.png'),
  pilot: require('../assets/tiles/professions/pilot.png'),
  plumber: require('../assets/tiles/professions/plumber.png'),
  programmer: require('../assets/tiles/professions/programmer.png'),
  scientist: require('../assets/tiles/professions/scientist.png'),
  singer: require('../assets/tiles/professions/Singer.png'),
  soldier: require('../assets/tiles/professions/Soldier.png'),
  teacher: require('../assets/tiles/professions/Teacher.png'),
  waiter: require('../assets/tiles/professions/waiter.png'),
  police: require('../assets/tiles/professions/Police.png'),
  judge: require('../assets/tiles/professions/judge.png'),
  mechanic: require('../assets/tiles/professions/mechanic.png'),
  veterinarian: require('../assets/tiles/professions/veterinarian.png'),
  electrician: require('../assets/tiles/professions/electrician.png'),
  lawyer: require('../assets/tiles/professions/lawyer.png'),

  // Actions images
  eat: require('../assets/tiles/actions/eat.png'),
  drink: require('../assets/tiles/actions/drink.png'),
  open: require('../assets/tiles/actions/open.png'),
  close: require('../assets/tiles/actions/close.png'),
  play: require('../assets/tiles/actions/play.png'),
  run: require('../assets/tiles/actions/run.png'),
  walk: require('../assets/tiles/actions/walk.png'),
  jump: require('../assets/tiles/actions/jump.png'),
  sit: require('../assets/tiles/actions/sit.png'),
  stand: require('../assets/tiles/actions/stand.png'),
  sleep: require('../assets/tiles/actions/sleep.png'),
  read: require('../assets/tiles/actions/read.png'),
  write: require('../assets/tiles/actions/write.png'),
  draw: require('../assets/tiles/actions/draw.png'),
  sing: require('../assets/tiles/actions/sing.png'),
  dance: require('../assets/tiles/actions/dance.png'),
  wash: require('../assets/tiles/actions/wash.png'),
  brush: require('../assets/tiles/actions/brush.png'),
  take: require('../assets/tiles/actions/take.png'),
  give: require('../assets/tiles/actions/give.png'),
  go: require('../assets/tiles/actions/go.png'),
  come: require('../assets/tiles/actions/come.png'),
  look: require('../assets/tiles/actions/look.png'),
  listen: require('../assets/tiles/actions/listen.png'),
  stop: require('../assets/tiles/actions/stop.png'),
  start: require('../assets/tiles/actions/start.png'),
  help: require('../assets/tiles/actions/help.png'),
  call: require('../assets/tiles/actions/call.png'),
  wait: require('../assets/tiles/actions/wait.png'),
  think: require('../assets/tiles/actions/think.png'),
};

export const CATEGORY_STYLES: Record<
  Category['id'],
  { bg: string; chip: string; text: string; accent: string; headerEmoji: string }
> = {
  transport: { bg: '#FFF5EC', chip: '#FFEDD5', text: '#111827', accent: '#FF8A4C', headerEmoji: '🚗' },
  food:      { bg: '#F3FFE9', chip: '#E8FAD8', text: '#0F5132', accent: '#63C132', headerEmoji: '🍎' },
  jobs:      { bg: '#FFF0F5', chip: '#FFE1E9', text: '#5B2336', accent: '#FF5FA0', headerEmoji: '🧑‍🍳' },
  emotions:  { bg: '#F2F4FF', chip: '#E7E9FF', text: '#1F2A59', accent: '#6A7BFF', headerEmoji: '😊' },
  actions:   { bg: '#F2F7FF', chip: '#EAF3FF', text: '#153058', accent: '#5BA6FF', headerEmoji: '🎮' },
  favorites: { bg: '#FFFBEB', chip: '#FFE8A3', text: '#92400E', accent: '#F59E0B', headerEmoji: '❤️' },
  mytiles:   { bg: '#F0F9FF', chip: '#E0F2FE', text: '#0C4A6E', accent: '#0EA5E9', headerEmoji: '⭐' },
};

export const COMMON_WORDS: Tile[] = [
  { id: 'i',          label: 'I',          emoji: '👤', core: true },
  { id: 'want',       label: 'want',       emoji: '✨', core: true },
  { id: 'more',       label: 'more',       emoji: '➕', core: true },
  { id: 'help',       label: 'help',       emoji: '🆘', core: true },
  { id: 'go',         label: 'go',         emoji: '▶️', core: true },
  { id: 'stop',       label: 'stop',       emoji: '⏹️', core: true },
  { id: 'yes',        label: 'yes',        emoji: '👍', core: true },
  { id: 'no',         label: 'no',         emoji: '👎', core: true },
  { id: 'please',     label: 'please',     emoji: '🙏', core: true },
  { id: 'thankyou',   label: 'thank you',  emoji: '😊', core: true },
  { id: 'if',         label: 'if',         emoji: '❓', core: true },
  { id: 'this',       label: 'this',       emoji: '👉', core: true },
  { id: 'that',       label: 'that',       emoji: '👈', core: true },
  { id: 'then',       label: 'then',       emoji: '➡️', core: true },
  { id: 'to',         label: 'to',         emoji: '➡️', core: true },
];

export const CATEGORIES: Category[] = [
  {
    id: 'transport',
    title: 'Transport',
    color: '#FFEAD1',
    tiles: [
      { id: 'car',         label: 'car',         emoji: '🚗', imageKey: 'car' },
      { id: 'bike',        label: 'bike',        emoji: '🏍️', imageKey: 'bike' },
      { id: 'train',       label: 'train',       emoji: '🚆', imageKey: 'train' },
      { id: 'bus',         label: 'bus',         emoji: '🚌', imageKey: 'bus' },
      { id: 'plane',       label: 'plane',       emoji: '✈️', imageKey: 'plane' },
      { id: 'boat',        label: 'boat',        emoji: '🛶', imageKey: 'boat' },
      { id: 'ship',        label: 'ship',        emoji: '🚢', imageKey: 'ship' },
      { id: 'taxi',        label: 'taxi',        emoji: '🚕', imageKey: 'taxi' },
      { id: 'truck',       label: 'truck',       emoji: '🚚', imageKey: 'truck' },
      { id: 'scooter',     label: 'scooter',     emoji: '🛵', imageKey: 'scooter' },
      { id: 'helicopter',  label: 'helicopter',  emoji: '🚁', imageKey: 'helicopter' },
      { id: 'submarine',   label: 'submarine',   emoji: '🛳️', imageKey: 'submarine' },
      { id: 'rocket',      label: 'rocket',      emoji: '🚀', imageKey: 'rocket' },
      { id: 'bicycle',     label: 'bicycle',     emoji: '🚲', imageKey: 'bicycle' },
      { id: 'tram',        label: 'tram',        emoji: '🚊', imageKey: 'tram' },
      { id: 'metro',       label: 'metro',       emoji: '🚇', imageKey: 'metro' },
      { id: 'van',         label: 'van',         emoji: '🚐', imageKey: 'van' },
      { id: 'ambulance',   label: 'ambulance',   emoji: '🚑', imageKey: 'ambulance' },
      { id: 'policecar',   label: 'police car',  emoji: '🚓', imageKey: 'policecar' },
      { id: 'firetruck',   label: 'fire truck',  emoji: '🚒', imageKey: 'firetruck' },
      { id: 'skateboard',  label: 'skateboard',  emoji: '🛹', imageKey: 'skateboard' },
      { id: 'rollerskates',label: 'roller skates', emoji: '🛼', imageKey: 'rollerskates' },
      { id: 'wheelchair',  label: 'wheelchair',  emoji: '🦽', imageKey: 'wheelchair' },
    ],
  },
  {
    id: 'food',
    title: 'Food',
    color: '#E8FAD8',
    tiles: [
      { id: 'apple',     label: 'apple',     emoji: '🍎', imageKey: 'apple' },
      { id: 'banana',    label: 'banana',    emoji: '🍌', imageKey: 'banana' },
      { id: 'grapes',    label: 'grapes',    emoji: '🍇', imageKey: 'grapes' },
      { id: 'pineapple', label: 'pineapple', emoji: '🍍', imageKey: 'pineapple' },
      { id: 'mango',     label: 'mango',     emoji: '🥭', imageKey: 'mango' },
      { id: 'orange',    label: 'orange',    emoji: '🍊', imageKey: 'orange' },
      { id: 'strawberry',label: 'strawberry',emoji: '🍓', imageKey: 'strawberry' },
      { id: 'watermelon',label: 'watermelon',emoji: '🍉', imageKey: 'watermelon' },
      { id: 'pear',      label: 'pear',      emoji: '🍐', imageKey: 'pear' },
      { id: 'peach',     label: 'peach',     emoji: '🍑', imageKey: 'peach' },
      { id: 'cherry',    label: 'cherry',    emoji: '🍒', imageKey: 'cherry' },
      { id: 'kiwi',      label: 'kiwi',      emoji: '🥝', imageKey: 'kiwi' },
      { id: 'lemon',     label: 'lemon',     emoji: '🍋', imageKey: 'lemon' },
      { id: 'rice',      label: 'rice',      emoji: '🍚', imageKey: 'rice' },
      { id: 'milk',      label: 'milk',      emoji: '🥛', imageKey: 'milk' },
      { id: 'bread',     label: 'bread',     emoji: '🍞', imageKey: 'bread' },
      { id: 'cheese',    label: 'cheese',    emoji: '🧀', imageKey: 'cheese' },
      { id: 'egg',       label: 'egg',       emoji: '🥚', imageKey: 'egg' },
      { id: 'chicken',   label: 'chicken',   emoji: '🍗', imageKey: 'chicken' },
      { id: 'fish',      label: 'fish',      emoji: '🐟', imageKey: 'fish' },
      { id: 'pizza',     label: 'pizza',     emoji: '🍕', imageKey: 'pizza' },
      { id: 'burger',    label: 'burger',    emoji: '🍔', imageKey: 'burger' },
      { id: 'pasta',     label: 'pasta',     emoji: '🍝', imageKey: 'pasta' },
      { id: 'salad',     label: 'salad',     emoji: '🥗', imageKey: 'salad' },
      { id: 'soup',      label: 'soup',      emoji: '🍲', imageKey: 'soup' },
      { id: 'icecream',  label: 'ice cream', emoji: '🍨', imageKey: 'icecream' },
      { id: 'cake',      label: 'cake',      emoji: '🍰', imageKey: 'cake' },
      { id: 'cookie',    label: 'cookie',    emoji: '🍪', imageKey: 'cookie' },
      { id: 'juice',     label: 'juice',     emoji: '🧃', imageKey: 'juice' },
      { id: 'yogurt',    label: 'yogurt',    emoji: '🥛', imageKey: 'yogurt' },
    ],
  },
  {
    id: 'jobs',
    title: 'Professions',
    color: '#FFE1E9',
    tiles: [
      { id: 'doctor',     label: 'doctor',     emoji: '🩺', imageKey: 'doctor' },
      { id: 'nurse',      label: 'nurse',      emoji: '👩‍⚕️', imageKey: 'nurse' },
      { id: 'teacher',    label: 'teacher',    emoji: '🏫', imageKey: 'teacher' },
      { id: 'police',     label: 'police',     emoji: '👮', imageKey: 'police' },
      { id: 'firefighter',label: 'firefighter',emoji: '👨‍🚒', imageKey: 'firefighter' },
      { id: 'farmer',     label: 'farmer',     emoji: '👨‍🌾', imageKey: 'farmer' },
      { id: 'chef',       label: 'chef',       emoji: '👩‍🍳', imageKey: 'chef' },
      { id: 'driver',     label: 'driver',     emoji: '🧑‍✈️', imageKey: 'driver' },
      { id: 'engineer',   label: 'engineer',   emoji: '🧑‍🔧', imageKey: 'engineer' },
      { id: 'artist',     label: 'artist',     emoji: '🎨', imageKey: 'artist' },
      { id: 'singer',     label: 'singer',     emoji: '🎤', imageKey: 'singer' },
      { id: 'dancer',     label: 'dancer',     emoji: '💃', imageKey: 'dancer' },
      { id: 'soldier',    label: 'soldier',    emoji: '🪖', imageKey: 'soldier' },
      { id: 'pilot',      label: 'pilot',      emoji: '🛩️', imageKey: 'pilot' },
      { id: 'judge',      label: 'judge',      emoji: '⚖️', imageKey: 'judge' },
      { id: 'lawyer',     label: 'lawyer',     emoji: '👨‍⚖️', imageKey: 'lawyer' },
      { id: 'scientist',  label: 'scientist',  emoji: '🔬', imageKey: 'scientist' },
      { id: 'programmer', label: 'programmer', emoji: '💻', imageKey: 'programmer' },
      { id: 'builder',    label: 'builder',    emoji: '👷', imageKey: 'builder' },
      { id: 'cashier',    label: 'cashier',    emoji: '💵', imageKey: 'cashier' },
      { id: 'waiter',     label: 'waiter',     emoji: '🧑‍🍳', imageKey: 'waiter' },
      { id: 'barber',     label: 'barber',     emoji: '💈', imageKey: 'barber' },
      { id: 'mechanic',   label: 'mechanic',   emoji: '🔧', imageKey: 'mechanic' },
      { id: 'plumber',    label: 'plumber',    emoji: '🧰', imageKey: 'plumber' },
      { id: 'electrician',label: 'electrician',emoji: '💡', imageKey: 'electrician' },
      { id: 'photographer',label:'photographer',emoji: '📷', imageKey: 'photographer'  },
      { id: 'dentist',    label: 'dentist',    emoji: '🦷', imageKey: 'dentist'  },
      { id: 'veterinarian',label:'veterinarian',emoji:'🐾', imageKey: 'veterinarian' },
    ],
  },
  {
    id: 'emotions',
    title: 'Emotions',
    color: '#E7E9FF',
    tiles: [
      { id: 'happy',      label: 'happy',      emoji: '😊', imageKey: 'happy' },
      { id: 'sad',        label: 'sad',        emoji: '😢', imageKey: 'sad' },
      { id: 'angry',      label: 'angry',      emoji: '😠', imageKey: 'angry' },
      { id: 'tired',      label: 'tired',      emoji: '🥱', imageKey: 'tired' },
      { id: 'excited',    label: 'excited',    emoji: '🤩', imageKey: 'excited' },
      { id: 'scared',     label: 'scared',     emoji: '😨', imageKey: 'scared' },
      { id: 'surprised',  label: 'surprised',  emoji: '😲', imageKey: 'surprised' },
      { id: 'calm',       label: 'calm',       emoji: '😌', imageKey: 'calm' },
      { id: 'bored',      label: 'bored',      emoji: '🥱', imageKey: 'bored' },
      { id: 'confused',   label: 'confused',   emoji: '😕', imageKey: 'confused' },
      { id: 'proud',      label: 'proud',      emoji: '😌', imageKey: 'proud' },
      { id: 'shy',        label: 'shy',        emoji: '🤭', imageKey: 'shy' },
      { id: 'silly',      label: 'silly',      emoji: '😜', imageKey: 'silly' },
      { id: 'frustrated', label: 'frustrated', emoji: '😣', imageKey: 'frustrated' },
      { id: 'worried',    label: 'worried',    emoji: '😟', imageKey: 'worried' },
      { id: 'sleepy',     label: 'sleepy',     emoji: '😪', imageKey: 'sleepy' },
      { id: 'sick',       label: 'sick',       emoji: '🤒', imageKey: 'sick' },
      { id: 'brave',      label: 'brave',      emoji: '🦁', imageKey: 'brave' },
      { id: 'curious',    label: 'curious',    emoji: '🧐', imageKey: 'curious' },
      { id: 'embarrassed',label: 'embarrassed',emoji: '😳', imageKey: 'embarrassed' },
      { id: 'lonely',     label: 'lonely',     emoji: '😔', imageKey: 'lonely' },
      { id: 'hopeful',    label: 'hopeful',    emoji: '🙂', imageKey: 'hopeful' },
      { id: 'grateful',   label: 'grateful',   emoji: '🥰', imageKey: 'grateful' },
      { id: 'confident',  label: 'confident',  emoji: '😎', imageKey: 'confident' },
      { id: 'relaxed',    label: 'relaxed',    emoji: '🧘', imageKey: 'relaxed' },
      { id: 'annoyed',    label: 'annoyed',    emoji: '😒', imageKey: 'annoyed' },
      { id: 'shocked',    label: 'shocked',    emoji: '😱', imageKey: 'shocked' },
    ],
  },
  {
    id: 'actions',
    title: 'Actions',
    color: '#EAF3FF',
    tiles: [
      { id: 'eat',    label: 'eat',    emoji: '🍽️', imageKey: 'eat' },
      { id: 'drink',  label: 'drink',  emoji: '🥤',  imageKey: 'drink' },
      { id: 'open',   label: 'open',   emoji: '👐',  imageKey: 'open' },
      { id: 'close',  label: 'close',  emoji: '✋',  imageKey: 'close' },
      { id: 'play',   label: 'play',   emoji: '🎮',  imageKey: 'play' },
      { id: 'run',    label: 'run',    emoji: '🏃',  imageKey: 'run' },
      { id: 'walk',   label: 'walk',   emoji: '🚶',  imageKey: 'walk' },
      { id: 'jump',   label: 'jump',   emoji: '🤾',  imageKey: 'jump' },
      { id: 'sit',    label: 'sit',    emoji: '🪑',  imageKey: 'sit' },
      { id: 'stand',  label: 'stand',  emoji: '🧍',  imageKey: 'stand' },
      { id: 'sleep',  label: 'sleep',  emoji: '😴',  imageKey: 'sleep' },
      { id: 'read',   label: 'read',   emoji: '📖',  imageKey: 'read' },
      { id: 'write',  label: 'write',  emoji: '✍️',  imageKey: 'write' },
      { id: 'draw',   label: 'draw',   emoji: '🖍️', imageKey: 'draw' },
      { id: 'sing',   label: 'sing',   emoji: '🎤',  imageKey: 'sing' },
      { id: 'dance',  label: 'dance',  emoji: '💃',  imageKey: 'dance' },
      { id: 'wash',   label: 'wash',   emoji: '🧼',  imageKey: 'wash' },
      { id: 'brush',  label: 'brush',  emoji: '🪥',  imageKey: 'brush' },
      { id: 'take',   label: 'take',   emoji: '🤲',  imageKey: 'take' },
      { id: 'give',   label: 'give',   emoji: '👐',  imageKey: 'give' },
      { id: 'go',     label: 'go',     emoji: '➡️',  imageKey: 'go' },
      { id: 'come',   label: 'come',   emoji: '⬅️',  imageKey: 'come' },
      { id: 'look',   label: 'look',   emoji: '👀',  imageKey: 'look' },
      { id: 'listen', label: 'listen', emoji: '👂',  imageKey: 'listen' },
      { id: 'stop',   label: 'stop',   emoji: '⛔',  imageKey: 'stop' },
      { id: 'start',  label: 'start',  emoji: '▶️',  imageKey: 'start' },
      { id: 'help',   label: 'help',   emoji: '🆘',  imageKey: 'help' },
      { id: 'call',   label: 'call',   emoji: '📞',  imageKey: 'call' },
      { id: 'wait',   label: 'wait',   emoji: '⏳',  imageKey: 'wait' },
      { id: 'think',  label: 'think',  emoji: '🤔',  imageKey: 'think' },
    ],
  },
];


