/**
 * OT Level 4 Session 10 — Cross-body rhythm imitation theme tokens.
 */

/** Game 1 — Cross Clap · Rhythm studio (copy cross-body clap patterns) */
export const CROSS_CLAP_THEME = {
  title: 'Cross Clap',
  subtitle: 'Listen to the pattern — then copy the cross-body claps!',
  emoji: '👏',
  gradient: ['#0C1929', '#0F2744', '#1E3A5F', '#2563EB'] as [string, string, string, string],
  accent: '#60A5FA',
  accentDark: '#BFDBFE',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  crossGlow: '#93C5FD',
  playBorder: 'rgba(96,165,250,0.42)',
  playBg: '#0C1929',
  sparkleColor: '#60A5FA',
  backText: '#DBEAFE',
  backBorder: 'rgba(96,165,250,0.38)',
  titleColor: '#EFF6FF',
  subtitleColor: 'rgba(191,219,254,0.9)',
  statLabel: 'rgba(191,219,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(96,165,250,0.32)',
  voiceIntro:
    'Welcome to the rhythm studio! Listen to the cross-body clap pattern, then copy it with your hands!',
  voiceListen: 'Listen to the clap pattern!',
  voiceCopy: 'Now copy the pattern!',
  voiceComplete: 'Rhythm master! Your cross-body claps are on beat!',
  voiceSuccess: 'Perfect clap!',
  voiceFail: 'Try again — listen and copy!',
  congrats: 'Cross Clap Champion!',
} as const;

/** Game 2 — Shoulder Tap · Body map studio (cross-body shoulder tap patterns) */
export const SHOULDER_TAP_THEME = {
  title: 'Shoulder Tap',
  subtitle: 'Watch cross-body shoulder taps — then copy the pattern!',
  emoji: '👆',
  gradient: ['#052E16', '#14532D', '#166534', '#22C55E'] as [string, string, string, string],
  accent: '#4ADE80',
  accentDark: '#BBF7D0',
  leftColor: '#22C55E',
  rightColor: '#3B82F6',
  crossArc: '#6EE7B7',
  playBorder: 'rgba(74,222,128,0.42)',
  playBg: '#052E16',
  sparkleColor: '#4ADE80',
  backText: '#DCFCE7',
  backBorder: 'rgba(74,222,128,0.38)',
  titleColor: '#F0FDF4',
  subtitleColor: 'rgba(187,247,208,0.9)',
  statLabel: 'rgba(187,247,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(74,222,128,0.32)',
  voiceIntro:
    'Welcome to the body map studio! Watch hand-to-shoulder cross-body taps, then copy the pattern!',
  voiceListen: 'Watch the shoulder tap pattern!',
  voiceCopy: 'Now copy the pattern!',
  voiceComplete: 'Body mapping pro! Your cross-body shoulder taps are perfect!',
  voiceSuccess: 'Perfect tap!',
  voiceFail: 'Try again — watch and copy!',
  congrats: 'Shoulder Tap Champion!',
} as const;

/** Game 3 — Beat Mirror · Concert booth (mirror hand movements to the beat) */
export const BEAT_MIRROR_THEME = {
  title: 'Beat Mirror',
  subtitle: 'Listen to the beat — mirror left, right, or both hands!',
  emoji: '🎵',
  gradient: ['#2E1065', '#4C1D95', '#6D28D9', '#8B5CF6'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  leftColor: '#8B5CF6',
  rightColor: '#F472B6',
  waveGlow: '#C4B5FD',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#2E1065',
  sparkleColor: '#A78BFA',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(221,214,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the beat mirror booth! Listen to the rhythm, then mirror the hand movements — left, right, or both!',
  voiceListen: 'Listen to the beat pattern!',
  voiceCopy: 'Now mirror the hand movements!',
  voiceComplete: 'Sync superstar! Your hands move perfectly with the beat!',
  voiceSuccess: 'Perfect beat!',
  voiceFail: 'Try again — listen and mirror!',
  congrats: 'Beat Mirror Champion!',
} as const;

/** Game 4 — Rhythm Recall · Memory vault (listen, remember, repeat the pattern) */
export const RHYTHM_RECALL_THEME = {
  title: 'Rhythm Recall',
  subtitle: 'Listen carefully — remember the pattern — then repeat!',
  emoji: '🧠',
  gradient: ['#422006', '#78350F', '#92400E', '#FBBF24'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  leftColor: '#F59E0B',
  rightColor: '#EF4444',
  memoryGlow: '#FCD34D',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#422006',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(253,230,138,0.9)',
  statLabel: 'rgba(253,230,138,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the memory vault! Listen to the rhythm pattern, hold it in your mind, then repeat it back!',
  voiceListen: 'Listen and remember the pattern!',
  voiceCopy: 'Now repeat the pattern!',
  voiceComplete: 'Memory master! You recalled every rhythm perfectly!',
  voiceSuccess: 'Perfect recall!',
  voiceFail: 'Try again — listen and remember!',
  congrats: 'Rhythm Recall Champion!',
} as const;

/** Game 5 — Fast Beat · Lightning storm (rhythm accelerates each round) */
export const FAST_BEAT_THEME = {
  title: 'Fast Beat',
  subtitle: 'Copy the rhythm — it speeds up every round!',
  emoji: '⚡',
  gradient: ['#1C1917', '#450A0A', '#7F1D1D', '#EF4444'] as [string, string, string, string],
  accent: '#EF4444',
  accentDark: '#FCA5A5',
  leftColor: '#EF4444',
  rightColor: '#3B82F6',
  speedGlow: '#FBBF24',
  playBorder: 'rgba(239,68,68,0.42)',
  playBg: '#1C1917',
  sparkleColor: '#EF4444',
  backText: '#FECACA',
  backBorder: 'rgba(239,68,68,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,202,202,0.9)',
  statLabel: 'rgba(254,202,202,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(239,68,68,0.32)',
  voiceIntro:
    'Welcome to the lightning arena! Copy each rhythm pattern — the beat gets faster every round!',
  voiceListen: 'Listen to the rhythm!',
  voiceCopy: 'Now copy it — stay in control!',
  voiceComplete: 'Lightning fast! You mastered every accelerating beat!',
  voiceSuccess: 'Perfect timing!',
  voiceFail: 'Try again — keep the rhythm!',
  congrats: 'Fast Beat Champion!',
} as const;
