import type { MidlinePassGameConfig } from '@/components/game/occupational/level4/session6/shared/MidlinePassGame';

export const TOSS_GRAB_THEME = {
  title: 'Toss & Grab',
  subtitle: 'Throw with left, catch with right — arc across the net!',
  emoji: '🎾',
  gradient: ['#14532D', '#166534', '#CA8A04', '#F59E0B'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FEF3C7',
  accentGreen: '#22C55E',
  accentGold: '#F59E0B',
  courtDark: '#14532D',
  netWhite: '#FEF3C7',
  leftColor: '#22C55E',
  rightColor: '#F59E0B',
  ballEmoji: '🎾',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#14532D',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,243,199,0.9)',
  statLabel: 'rgba(254,243,199,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the tennis court! Throw the ball with your left hand, then catch it with your right across the net!',
  voiceCue: 'Tap left to throw, then right to catch!',
  voiceComplete: 'Amazing toss and grab! You nailed every throw and catch!',
  voiceSuccess: 'Great catch!',
  voiceWrong: 'Wait for the ball!',
  voiceMiss: 'Missed the catch — throw again!',
  congrats: 'Toss & Grab Star!',
} as const;

export const TOSS_GRAB_CONFIG: Omit<MidlinePassGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'throwCatch',
  theme: {
    title: TOSS_GRAB_THEME.title,
    subtitle: TOSS_GRAB_THEME.subtitle,
    emoji: TOSS_GRAB_THEME.emoji,
    gradient: TOSS_GRAB_THEME.gradient,
    accent: TOSS_GRAB_THEME.accent,
    accentDark: TOSS_GRAB_THEME.accentDark,
    ballEmoji: TOSS_GRAB_THEME.ballEmoji,
    leftColor: TOSS_GRAB_THEME.leftColor,
    rightColor: TOSS_GRAB_THEME.rightColor,
    backText: TOSS_GRAB_THEME.backText,
    backBorder: TOSS_GRAB_THEME.backBorder,
    titleColor: TOSS_GRAB_THEME.titleColor,
    subtitleColor: TOSS_GRAB_THEME.subtitleColor,
    statLabel: TOSS_GRAB_THEME.statLabel,
    statValue: TOSS_GRAB_THEME.statValue,
    statBorder: TOSS_GRAB_THEME.statBorder,
    playBorder: TOSS_GRAB_THEME.playBorder,
    playBg: TOSS_GRAB_THEME.playBg,
    sparkleColor: TOSS_GRAB_THEME.sparkleColor,
  },
  ttsIntro: TOSS_GRAB_THEME.voiceIntro,
  ttsComplete: TOSS_GRAB_THEME.voiceComplete,
  ttsCue: TOSS_GRAB_THEME.voiceCue,
  ttsSuccess: TOSS_GRAB_THEME.voiceSuccess,
  ttsWrong: TOSS_GRAB_THEME.voiceWrong,
  ttsMiss: TOSS_GRAB_THEME.voiceMiss,
  congratsMessage: TOSS_GRAB_THEME.congrats,
  logType: 'throw-catch',
  skillTags: ['hand-coordination', 'timing', 'throw-catch'],
};
