import type { MidlineDragPassGameConfig } from '@/components/game/occupational/level4/session6/shared/MidlineDragPassGame';

export const AIM_PASS_THEME = {
  title: 'Aim Pass',
  subtitle: 'Drag from the left — cross midline and hit the bullseye!',
  emoji: '🎯',
  gradient: ['#450A0A', '#7F1D1D', '#B91C1C', '#EF4444'] as [string, string, string, string],
  accent: '#EF4444',
  accentDark: '#FECACA',
  accentCrimson: '#DC2626',
  accentGold: '#FBBF24',
  laneDark: '#450A0A',
  bullseyeGlow: '#FBBF24',
  ballEmoji: '⚽',
  targetEmoji: '🎯',
  obstacleEmoji: '🚧',
  playBorder: 'rgba(239,68,68,0.42)',
  playBg: '#450A0A',
  sparkleColor: '#FBBF24',
  midlineColor: 'rgba(251,191,36,0.55)',
  backText: '#FEE2E2',
  backBorder: 'rgba(239,68,68,0.38)',
  titleColor: '#FEF2F2',
  subtitleColor: 'rgba(254,202,202,0.9)',
  statLabel: 'rgba(254,202,202,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(239,68,68,0.32)',
  voiceIntro:
    'Welcome to the archery lane! Drag the ball from the left, cross the golden midline, and land on the bullseye!',
  voiceDrag: 'Drag the ball left to right — cross the line and hit the bullseye!',
  voiceComplete: 'Sharpshooter! You hit every bullseye across midline!',
  voiceSuccess: 'Bullseye!',
  voiceMiss: 'Missed the target — drag to the bullseye on the right!',
  voiceCross: 'Cross the midline first, then aim for the bullseye!',
  congrats: 'Aim Pass Star!',
} as const;

export const AIM_PASS_CONFIG: Omit<MidlineDragPassGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'targetPass',
  theme: {
    title: AIM_PASS_THEME.title,
    subtitle: AIM_PASS_THEME.subtitle,
    emoji: AIM_PASS_THEME.emoji,
    gradient: AIM_PASS_THEME.gradient,
    accent: AIM_PASS_THEME.accent,
    accentDark: AIM_PASS_THEME.accentDark,
    ballEmoji: AIM_PASS_THEME.ballEmoji,
    targetEmoji: AIM_PASS_THEME.targetEmoji,
    obstacleEmoji: AIM_PASS_THEME.obstacleEmoji,
    backText: AIM_PASS_THEME.backText,
    backBorder: AIM_PASS_THEME.backBorder,
    titleColor: AIM_PASS_THEME.titleColor,
    subtitleColor: AIM_PASS_THEME.subtitleColor,
    statLabel: AIM_PASS_THEME.statLabel,
    statValue: AIM_PASS_THEME.statValue,
    statBorder: AIM_PASS_THEME.statBorder,
    playBorder: AIM_PASS_THEME.playBorder,
    playBg: AIM_PASS_THEME.playBg,
    sparkleColor: AIM_PASS_THEME.sparkleColor,
    midlineColor: AIM_PASS_THEME.midlineColor,
  },
  ttsIntro: AIM_PASS_THEME.voiceIntro,
  ttsComplete: AIM_PASS_THEME.voiceComplete,
  ttsDrag: AIM_PASS_THEME.voiceDrag,
  ttsMiss: AIM_PASS_THEME.voiceMiss,
  ttsCross: AIM_PASS_THEME.voiceCross,
  ttsSuccess: AIM_PASS_THEME.voiceSuccess,
  congratsMessage: AIM_PASS_THEME.congrats,
  logType: 'target-pass',
  skillTags: ['accuracy', 'midline-crossing', 'target-aiming'],
};
