import type { SidePingPongGameConfig } from '@/components/game/occupational/level4/session8/shared/SidePingPongGame';

export const RALLY_TAP_THEME = {
  title: 'Rally Tap',
  subtitle: 'Watch the ball cross — tap when it hits center!',
  emoji: '🏓',
  gradient: ['#052E16', '#14532D', '#166534', '#22C55E'] as [string, string, string, string],
  accent: '#4ADE80',
  accentDark: '#BBF7D0',
  courtLine: '#86EFAC',
  netGlow: '#6EE7B7',
  leftColor: '#22C55E',
  rightColor: '#3B82F6',
  ballEmoji: '🏓',
  playBorder: 'rgba(74,222,128,0.42)',
  playBg: '#052E16',
  sparkleColor: '#4ADE80',
  backText: '#DCFCE7',
  backBorder: 'rgba(74,222,128,0.38)',
  titleColor: '#F0FDF4',
  subtitleColor: 'rgba(187,247,208,0.9)',
  statLabel: 'rgba(187,247,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(74,222,128,0.32)',
  voiceIntro:
    'Welcome to the rally arena! Watch the ball zip across the court and tap when it reaches the center circle!',
  voiceCue: 'Tap when the ball reaches the center!',
  voiceComplete: 'Champion rally! Your timing and focus are on point!',
  voiceSuccess: 'Great rally tap!',
  voiceMiss: 'Wait until the center glows green!',
  voiceEarly: 'Too early! Wait for the ball at center!',
  voiceRetry: 'Missed! Try again!',
  congrats: 'Rally Tap Champion!',
} as const;

export const RALLY_TAP_CONFIG: Omit<SidePingPongGameConfig, 'onBack' | 'onComplete'> = {
  theme: {
    title: RALLY_TAP_THEME.title,
    subtitle: RALLY_TAP_THEME.subtitle,
    emoji: RALLY_TAP_THEME.emoji,
    gradient: RALLY_TAP_THEME.gradient,
    accent: RALLY_TAP_THEME.accent,
    accentDark: RALLY_TAP_THEME.accentDark,
    leftColor: RALLY_TAP_THEME.leftColor,
    rightColor: RALLY_TAP_THEME.rightColor,
    ballEmoji: RALLY_TAP_THEME.ballEmoji,
    backText: RALLY_TAP_THEME.backText,
    backBorder: RALLY_TAP_THEME.backBorder,
    titleColor: RALLY_TAP_THEME.titleColor,
    subtitleColor: RALLY_TAP_THEME.subtitleColor,
    statLabel: RALLY_TAP_THEME.statLabel,
    statValue: RALLY_TAP_THEME.statValue,
    statBorder: RALLY_TAP_THEME.statBorder,
    playBorder: RALLY_TAP_THEME.playBorder,
    playBg: RALLY_TAP_THEME.playBg,
    sparkleColor: RALLY_TAP_THEME.sparkleColor,
  },
  ttsIntro: RALLY_TAP_THEME.voiceIntro,
  ttsComplete: RALLY_TAP_THEME.voiceComplete,
  ttsCue: RALLY_TAP_THEME.voiceCue,
  ttsSuccess: RALLY_TAP_THEME.voiceSuccess,
  ttsMiss: RALLY_TAP_THEME.voiceMiss,
  ttsEarly: RALLY_TAP_THEME.voiceEarly,
  ttsRetry: RALLY_TAP_THEME.voiceRetry,
  congratsMessage: RALLY_TAP_THEME.congrats,
  logType: 'ping-pong-tap',
  skillTags: ['focus', 'alternating-sides', 'timing', 'visual-motor'],
};
