import type { DualDragGameConfig } from '@/components/game/occupational/level4/session9/shared/DualDragGame';

export const TWIN_DRAG_THEME = {
  title: 'Twin Drag',
  subtitle: 'Use both hands — drag left and right objects to their targets!',
  emoji: '🤲',
  gradient: ['#0C1929', '#0F2744', '#1E3A5F', '#2563EB'] as [string, string, string, string],
  accent: '#60A5FA',
  accentDark: '#BFDBFE',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  leftGlow: '#60A5FA',
  rightGlow: '#FB7185',
  leftIcon: '🔵',
  rightIcon: '🔴',
  playBorder: 'rgba(96,165,250,0.42)',
  playBg: '#0C1929',
  sparkleColor: '#60A5FA',
  zoneBorder: 'rgba(96,165,250,0.55)',
  backText: '#DBEAFE',
  backBorder: 'rgba(96,165,250,0.38)',
  titleColor: '#EFF6FF',
  subtitleColor: 'rgba(191,219,254,0.9)',
  statLabel: 'rgba(191,219,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(96,165,250,0.32)',
  voiceIntro:
    'Welcome to the twin workshop! Use both hands at once — drag the blue and red objects to their targets!',
  voiceCue: 'Drag left and right objects to their targets together!',
  voiceComplete: 'Both hands working as one! You mastered twin dragging!',
  voiceSuccess: 'Both objects placed!',
  congrats: 'Twin Drag Champion!',
} as const;

export const TWIN_DRAG_CONFIG: Omit<DualDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'dualTarget',
  theme: {
    title: TWIN_DRAG_THEME.title,
    subtitle: TWIN_DRAG_THEME.subtitle,
    emoji: TWIN_DRAG_THEME.emoji,
    gradient: TWIN_DRAG_THEME.gradient,
    accent: TWIN_DRAG_THEME.accent,
    accentDark: TWIN_DRAG_THEME.accentDark,
    leftColor: TWIN_DRAG_THEME.leftColor,
    rightColor: TWIN_DRAG_THEME.rightColor,
    backText: TWIN_DRAG_THEME.backText,
    backBorder: TWIN_DRAG_THEME.backBorder,
    titleColor: TWIN_DRAG_THEME.titleColor,
    subtitleColor: TWIN_DRAG_THEME.subtitleColor,
    statLabel: TWIN_DRAG_THEME.statLabel,
    statValue: TWIN_DRAG_THEME.statValue,
    statBorder: TWIN_DRAG_THEME.statBorder,
    playBorder: TWIN_DRAG_THEME.playBorder,
    playBg: TWIN_DRAG_THEME.playBg,
    sparkleColor: TWIN_DRAG_THEME.sparkleColor,
    zoneBorder: TWIN_DRAG_THEME.zoneBorder,
  },
  ttsIntro: TWIN_DRAG_THEME.voiceIntro,
  ttsComplete: TWIN_DRAG_THEME.voiceComplete,
  ttsCue: TWIN_DRAG_THEME.voiceCue,
  ttsSuccess: TWIN_DRAG_THEME.voiceSuccess,
  congratsMessage: TWIN_DRAG_THEME.congrats,
  logType: 'double-drag',
  skillTags: ['bilateral-strength', 'simultaneous-dragging', 'coordination'],
};
