import type { AlternateTapGameConfig } from '@/components/game/occupational/level4/session5/shared/AlternateTapGame';

export const FLASH_PICK_THEME = {
  title: 'Flash Pick',
  subtitle: 'Watch both panels — strike the side that lightning flashes!',
  emoji: '⚡',
  gradient: ['#1A0A0A', '#450A0A', '#7F1D1D', '#991B1B'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  accentBlue: '#60A5FA',
  accentRed: '#F87171',
  arenaDark: '#1A0A0A',
  boltGlow: '#FBBF24',
  leftColor: '#3B82F6',
  rightColor: '#EF4444',
  leftEmoji: '👈',
  rightEmoji: '👉',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#1A0A0A',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,243,199,0.88)',
  statLabel: 'rgba(254,243,199,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the decision arena! When lightning flashes on the left or right panel, tap that side with the matching hand!',
  voiceCue: 'Tap the flashing side!',
  voiceComplete: 'Lightning reflexes! You picked every flash perfectly!',
  voiceSuccess: 'Perfect pick!',
  voiceWrong: 'Wrong side — tap the panel that flashed!',
  voiceTooSlow: 'Too slow — watch for the next flash!',
  voiceWatch: 'Eyes on both panels…',
  congrats: 'Flash Pick Champion!',
} as const;

export const FLASH_PICK_CONFIG: Omit<AlternateTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'flash',
  theme: {
    title: FLASH_PICK_THEME.title,
    subtitle: FLASH_PICK_THEME.subtitle,
    emoji: FLASH_PICK_THEME.emoji,
    gradient: FLASH_PICK_THEME.gradient,
    accent: FLASH_PICK_THEME.accent,
    accentDark: FLASH_PICK_THEME.accentDark,
    leftColor: FLASH_PICK_THEME.leftColor,
    rightColor: FLASH_PICK_THEME.rightColor,
    leftEmoji: FLASH_PICK_THEME.leftEmoji,
    rightEmoji: FLASH_PICK_THEME.rightEmoji,
    targetStyle: 'panel',
    backText: FLASH_PICK_THEME.backText,
    backBorder: FLASH_PICK_THEME.backBorder,
    titleColor: FLASH_PICK_THEME.titleColor,
    subtitleColor: FLASH_PICK_THEME.subtitleColor,
    statLabel: FLASH_PICK_THEME.statLabel,
    statValue: FLASH_PICK_THEME.statValue,
    statBorder: FLASH_PICK_THEME.statBorder,
    playBorder: FLASH_PICK_THEME.playBorder,
    playBg: FLASH_PICK_THEME.playBg,
    sparkleColor: FLASH_PICK_THEME.sparkleColor,
  },
  ttsIntro: FLASH_PICK_THEME.voiceIntro,
  ttsComplete: FLASH_PICK_THEME.voiceComplete,
  ttsCue: FLASH_PICK_THEME.voiceCue,
  ttsSuccess: FLASH_PICK_THEME.voiceSuccess,
  ttsWrong: FLASH_PICK_THEME.voiceWrong,
  ttsTooSlow: FLASH_PICK_THEME.voiceTooSlow,
  ttsWatch: FLASH_PICK_THEME.voiceWatch,
  congratsMessage: FLASH_PICK_THEME.congrats,
  logType: 'flash-side',
  skillTags: ['decision-making', 'reaction-time', 'hand-selection'],
};
