import type { DiagonalDragGameConfig } from '@/components/game/occupational/level4/session3/shared/DiagonalDragGame';

export const DIAGONAL_DASH_THEME = {
  title: 'Diagonal Dash',
  subtitle: 'Launch from the summit and slide diagonally down to the valley finish',
  emoji: '↘️',
  gradient: ['#0C1A3A', '#1E3A5F', '#B45309', '#FBBF24'] as [string, string, string, string],
  accent: '#38BDF8',
  accentDark: '#7DD3FC',
  accentGold: '#FBBF24',
  accentAmber: '#F59E0B',
  summitDark: '#0F172A',
  valleyWarm: '#78350F',
  trailGlow: '#38BDF8',
  draggableEmoji: '☄️',
  targetEmoji: '🏁',
  playBorder: 'rgba(56,189,248,0.42)',
  playBg: '#0F172A',
  sparkleColor: '#FBBF24',
  zoneBorder: 'rgba(251,191,36,0.45)',
  voiceIntro:
    'Welcome to the mountain dash! Drag from the summit at the top-left all the way down to the valley finish at the bottom-right!',
  voiceDrag: 'Slide diagonally down to the finish!',
  voiceComplete: 'What a run! You dashed down the mountain on every try!',
  voiceMiss: 'Aim for the valley finish in the bottom-right corner!',
  voiceLanded: 'Landed!',
  congrats: 'Diagonal Dash Legend!',
} as const;

export const DIAGONAL_DASH_CONFIG: Omit<DiagonalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'cornerDrag',
  theme: {
    title: DIAGONAL_DASH_THEME.title,
    subtitle: DIAGONAL_DASH_THEME.subtitle,
    emoji: DIAGONAL_DASH_THEME.emoji,
    gradient: DIAGONAL_DASH_THEME.gradient,
    accent: DIAGONAL_DASH_THEME.accent,
    accentDark: DIAGONAL_DASH_THEME.accentDark,
    draggableEmoji: DIAGONAL_DASH_THEME.draggableEmoji,
    targetEmoji: DIAGONAL_DASH_THEME.targetEmoji,
    backText: '#E0F2FE',
    backBorder: 'rgba(56,189,248,0.38)',
    titleColor: '#F0F9FF',
    subtitleColor: 'rgba(186,230,253,0.9)',
    statLabel: 'rgba(186,230,253,0.75)',
    statValue: '#FFFFFF',
    statBorder: 'rgba(56,189,248,0.32)',
    playBorder: DIAGONAL_DASH_THEME.playBorder,
    playBg: DIAGONAL_DASH_THEME.playBg,
    sparkleColor: DIAGONAL_DASH_THEME.sparkleColor,
    zoneBorder: DIAGONAL_DASH_THEME.zoneBorder,
  },
  ttsIntro: DIAGONAL_DASH_THEME.voiceIntro,
  ttsComplete: DIAGONAL_DASH_THEME.voiceComplete,
  ttsDrag: DIAGONAL_DASH_THEME.voiceDrag,
  ttsMiss: DIAGONAL_DASH_THEME.voiceMiss,
  ttsGoal: DIAGONAL_DASH_THEME.voiceLanded,
  congratsMessage: DIAGONAL_DASH_THEME.congrats,
  logType: 'top-left-bottom-right',
  skillTags: ['midline-crossing', 'reading-prep', 'diagonal-drag'],
};
