import type { DualTapGameConfig } from '@/components/game/occupational/level4/session4/shared/DualTapGame';

export const TWIN_TAP_THEME = {
  title: 'Twin Tap',
  subtitle: 'Tap both glowing orbs at the same time — wake the sync bridge!',
  emoji: '⭕',
  gradient: ['#0F172A', '#1E3A5F', '#0E7490', '#06B6D4'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#67E8F9',
  accentCoral: '#FB7185',
  accentCyan: '#06B6D4',
  arenaDark: '#0F172A',
  syncGlow: '#22D3EE',
  leftColor: '#0EA5E9',
  rightColor: '#F43F5E',
  leftEmoji: '🖐️',
  rightEmoji: '🖐️',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#0F172A',
  sparkleColor: '#22D3EE',
  backText: '#CFFAFE',
  backBorder: 'rgba(34,211,238,0.38)',
  titleColor: '#F0F9FF',
  subtitleColor: 'rgba(186,230,253,0.9)',
  statLabel: 'rgba(186,230,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(34,211,238,0.32)',
  voiceIntro:
    'Welcome to the sync arena! Use both hands and tap the left and right orbs together to light up the bridge!',
  voiceCue: 'Tap both orbs together!',
  voiceComplete: 'Perfect synchronization! Your hands are working as a team!',
  voiceSuccess: 'In sync!',
  voiceMiss: 'Tap both orbs at the same time!',
  congrats: 'Twin Tap Champion!',
} as const;

export const TWIN_TAP_CONFIG: Omit<DualTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'circles',
  theme: {
    title: TWIN_TAP_THEME.title,
    subtitle: TWIN_TAP_THEME.subtitle,
    emoji: TWIN_TAP_THEME.emoji,
    gradient: TWIN_TAP_THEME.gradient,
    accent: TWIN_TAP_THEME.accent,
    accentDark: TWIN_TAP_THEME.accentDark,
    leftColor: TWIN_TAP_THEME.leftColor,
    rightColor: TWIN_TAP_THEME.rightColor,
    leftEmoji: TWIN_TAP_THEME.leftEmoji,
    rightEmoji: TWIN_TAP_THEME.rightEmoji,
    targetStyle: 'circle',
    backText: TWIN_TAP_THEME.backText,
    backBorder: TWIN_TAP_THEME.backBorder,
    titleColor: TWIN_TAP_THEME.titleColor,
    subtitleColor: TWIN_TAP_THEME.subtitleColor,
    statLabel: TWIN_TAP_THEME.statLabel,
    statValue: TWIN_TAP_THEME.statValue,
    statBorder: TWIN_TAP_THEME.statBorder,
    playBorder: TWIN_TAP_THEME.playBorder,
    playBg: TWIN_TAP_THEME.playBg,
    sparkleColor: TWIN_TAP_THEME.sparkleColor,
  },
  ttsIntro: TWIN_TAP_THEME.voiceIntro,
  ttsComplete: TWIN_TAP_THEME.voiceComplete,
  ttsCue: TWIN_TAP_THEME.voiceCue,
  ttsSuccess: TWIN_TAP_THEME.voiceSuccess,
  ttsMiss: TWIN_TAP_THEME.voiceMiss,
  congratsMessage: TWIN_TAP_THEME.congrats,
  logType: 'double-circle-tap',
  skillTags: ['bilateral-coordination', 'two-hand-tap'],
};
