/**
 * OT Level 4 Session 5 — Alternating hand theme tokens.
 */

/** Game 1 — Switch Tap · Relay switch track (L→R alternating sequence) */
export const SWITCH_TAP_THEME = {
  title: 'Switch Tap',
  subtitle: 'Ping-pong your taps — left, then right, then left again!',
  emoji: '👆',
  gradient: ['#0F172A', '#1E1B4B', '#312E81', '#4338CA'] as [string, string, string, string],
  accent: '#818CF8',
  accentDark: '#C7D2FE',
  accentBlue: '#3B82F6',
  accentCoral: '#FB7185',
  trackDark: '#0F172A',
  switchGlow: '#818CF8',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  leftEmoji: '👈',
  rightEmoji: '👉',
  playBorder: 'rgba(129,140,248,0.42)',
  playBg: '#0F172A',
  sparkleColor: '#818CF8',
  backText: '#E0E7FF',
  backBorder: 'rgba(129,140,248,0.38)',
  titleColor: '#EEF2FF',
  subtitleColor: 'rgba(199,210,254,0.9)',
  statLabel: 'rgba(199,210,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(129,140,248,0.32)',
  voiceIntro:
    'Welcome to the relay switch track! Tap left, then right, then left again — keep alternating your hands!',
  voiceCue: 'Start with your left hand, then switch to right!',
  voiceComplete: 'Amazing switching! You mastered the alternating rhythm!',
  voiceSuccess: 'Perfect switch!',
  voiceWrong: 'Use the other hand — keep alternating!',
  congrats: 'Switch Tap Champion!',
} as const;

/** Game 2 — Hand Walk · Meadow finger trail (alternating walk along path) */
export const HAND_WALK_THEME = {
  title: 'Hand Walk',
  subtitle: 'Walk your fingers along the meadow trail — left step, right step!',
  emoji: '🚶',
  gradient: ['#14532D', '#166534', '#15803D', '#22C55E'] as [string, string, string, string],
  accent: '#4ADE80',
  accentDark: '#BBF7D0',
  accentEarth: '#A3E635',
  pathTan: '#D9F99D',
  meadowDark: '#14532D',
  leftColor: '#3B82F6',
  rightColor: '#F59E0B',
  leftEmoji: '👣',
  rightEmoji: '👣',
  playBorder: 'rgba(74,222,128,0.42)',
  playBg: '#14532D',
  sparkleColor: '#4ADE80',
  backText: '#DCFCE7',
  backBorder: 'rgba(74,222,128,0.38)',
  titleColor: '#F0FDF4',
  subtitleColor: 'rgba(187,247,208,0.9)',
  statLabel: 'rgba(187,247,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(74,222,128,0.32)',
  voiceIntro:
    'Welcome to the meadow trail! Walk your hands along the path — tap left, then right, like little footsteps!',
  voiceCue: 'Step with your left hand, then your right!',
  voiceComplete: 'Wonderful walking! Your fingers traced the whole trail!',
  voiceSuccess: 'Nice step!',
  voiceWrong: 'Walk the other hand — keep stepping along!',
  congrats: 'Hand Walk Trailblazer!',
} as const;

/** Game 3 — Flash Pick · Split decision arena (tap the flashing side) */
export const FLASH_PICK_THEME = {
  title: 'Flash Pick',
  subtitle: 'Watch both panels — strike the side that lightning flashes!',
  emoji: '⚡',
  gradient: ['#1A0A0A', '#450A0A', '#7F1D1D', '#991B1B'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  accentBlue: '#60A5FA',
  accentRed: '#F87171',
  arenaDark: '#1A0A0A',
  boltGlow: '#FBBF24',
  leftColor: '#3B82F6',
  rightColor: '#EF4444',
  leftEmoji: '👈',
  rightEmoji: '👉',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#1A0A0A',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,243,199,0.88)',
  statLabel: 'rgba(254,243,199,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the decision arena! When lightning flashes on the left or right panel, tap that side with the matching hand!',
  voiceCue: 'Tap the flashing side!',
  voiceComplete: 'Lightning reflexes! You picked every flash perfectly!',
  voiceSuccess: 'Perfect pick!',
  voiceWrong: 'Wrong side — tap the panel that flashed!',
  voiceTooSlow: 'Too slow — watch for the next flash!',
  voiceWatch: 'Eyes on both panels…',
  congrats: 'Flash Pick Champion!',
} as const;

/** Game 4 — Rhythm Switch · Jazz club drum kit (alternating beat drums) */
export const RHYTHM_SWITCH_THEME = {
  title: 'Rhythm Switch',
  subtitle: 'Follow the metronome — alternate left and right drum hits!',
  emoji: '🥁',
  gradient: ['#1C1410', '#422006', '#78350F', '#B45309'] as [string, string, string, string],
  accent: '#F59E0B',
  accentDark: '#FDE68A',
  accentBronze: '#D97706',
  accentCopper: '#EA580C',
  stageDark: '#1C1410',
  metronomeGlow: '#FBBF24',
  leftColor: '#F97316',
  rightColor: '#DC2626',
  leftEmoji: '🥁',
  rightEmoji: '🥁',
  playBorder: 'rgba(245,158,11,0.45)',
  playBg: '#1C1410',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(245,158,11,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,243,199,0.88)',
  statLabel: 'rgba(254,243,199,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(245,158,11,0.32)',
  voiceIntro:
    'Welcome to the jazz drum stage! Follow the beat and alternate — tap the left drum, then the right, keeping the rhythm!',
  voiceCue: 'Follow the beat and alternate your drums!',
  voiceComplete: 'Swinging rhythm! You nailed every alternating beat!',
  voiceSuccess: 'On beat!',
  voiceWrong: 'Wrong drum — follow the alternating beat!',
  congrats: 'Rhythm Switch Virtuoso!',
} as const;

/** Game 5 — Speed Switch · Neon turbo lane (escalating alternate taps) */
export const SPEED_SWITCH_THEME = {
  title: 'Speed Switch',
  subtitle: 'Start slow on the turbo lane — alternate faster each step!',
  emoji: '⚡',
  gradient: ['#1E1B4B', '#312E81', '#5B21B6', '#7C3AED'] as [string, string, string, string],
  accent: '#8B5CF6',
  accentDark: '#C4B5FD',
  accentCyan: '#22D3EE',
  accentMagenta: '#E879F9',
  laneDark: '#1E1B4B',
  turboGlow: '#A78BFA',
  leftColor: '#3B82F6',
  rightColor: '#A855F7',
  leftEmoji: '👈',
  rightEmoji: '👉',
  playBorder: 'rgba(139,92,246,0.45)',
  playBg: '#1E1B4B',
  sparkleColor: '#A78BFA',
  backText: '#EDE9FE',
  backBorder: 'rgba(139,92,246,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(196,181,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(139,92,246,0.32)',
  voiceIntro:
    'Welcome to the turbo lane! Alternate left and right — each step gets faster. Keep up with the speed!',
  voiceCue: 'Start slow — then blast through the lane!',
  voiceComplete: 'Incredible velocity! You mastered every speed level!',
  voiceSuccess: 'Zoom!',
  voiceWrong: 'Wrong side — keep alternating as you speed up!',
  voiceTooSlow: 'Too slow — pick up the pace!',
  congrats: 'Speed Switch Pro!',
} as const;
