import type { AlternateTapGameConfig } from '@/components/game/occupational/level4/session5/shared/AlternateTapGame';

export const HAND_WALK_THEME = {
  title: 'Hand Walk',
  subtitle: 'Walk your fingers along the meadow trail — left step, right step!',
  emoji: '🚶',
  gradient: ['#14532D', '#166534', '#15803D', '#22C55E'] as [string, string, string, string],
  accent: '#4ADE80',
  accentDark: '#BBF7D0',
  accentEarth: '#A3E635',
  pathTan: '#D9F99D',
  meadowDark: '#14532D',
  leftColor: '#3B82F6',
  rightColor: '#F59E0B',
  leftEmoji: '👣',
  rightEmoji: '👣',
  playBorder: 'rgba(74,222,128,0.42)',
  playBg: '#14532D',
  sparkleColor: '#4ADE80',
  backText: '#DCFCE7',
  backBorder: 'rgba(74,222,128,0.38)',
  titleColor: '#F0FDF4',
  subtitleColor: 'rgba(187,247,208,0.9)',
  statLabel: 'rgba(187,247,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(74,222,128,0.32)',
  voiceIntro:
    'Welcome to the meadow trail! Walk your hands along the path — tap left, then right, like little footsteps!',
  voiceCue: 'Step with your left hand, then your right!',
  voiceComplete: 'Wonderful walking! Your fingers traced the whole trail!',
  voiceSuccess: 'Nice step!',
  voiceWrong: 'Walk the other hand — keep stepping along!',
  congrats: 'Hand Walk Trailblazer!',
} as const;

export const HAND_WALK_CONFIG: Omit<AlternateTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'walking',
  theme: {
    title: HAND_WALK_THEME.title,
    subtitle: HAND_WALK_THEME.subtitle,
    emoji: HAND_WALK_THEME.emoji,
    gradient: HAND_WALK_THEME.gradient,
    accent: HAND_WALK_THEME.accent,
    accentDark: HAND_WALK_THEME.accentDark,
    leftColor: HAND_WALK_THEME.leftColor,
    rightColor: HAND_WALK_THEME.rightColor,
    leftEmoji: HAND_WALK_THEME.leftEmoji,
    rightEmoji: HAND_WALK_THEME.rightEmoji,
    targetStyle: 'circle',
    backText: HAND_WALK_THEME.backText,
    backBorder: HAND_WALK_THEME.backBorder,
    titleColor: HAND_WALK_THEME.titleColor,
    subtitleColor: HAND_WALK_THEME.subtitleColor,
    statLabel: HAND_WALK_THEME.statLabel,
    statValue: HAND_WALK_THEME.statValue,
    statBorder: HAND_WALK_THEME.statBorder,
    playBorder: HAND_WALK_THEME.playBorder,
    playBg: HAND_WALK_THEME.playBg,
    sparkleColor: HAND_WALK_THEME.sparkleColor,
  },
  ttsIntro: HAND_WALK_THEME.voiceIntro,
  ttsComplete: HAND_WALK_THEME.voiceComplete,
  ttsCue: HAND_WALK_THEME.voiceCue,
  ttsSuccess: HAND_WALK_THEME.voiceSuccess,
  ttsWrong: HAND_WALK_THEME.voiceWrong,
  congratsMessage: HAND_WALK_THEME.congrats,
  logType: 'walking-hands',
  skillTags: ['pre-writing', 'alternating-hands', 'hand-coordination'],
};
