export const SKY_CATCH_STARS = ['⭐', '🌟', '💫', '☄️'] as const;

export const SKY_CATCH_THEME = {
  title: 'Sky Catch',
  subtitle: 'Slide your cloud net to snag stars falling diagonally across the sky',
  emoji: '☁️',
  gradient: ['#0C1445', '#1E3A8A', '#7C3AED', '#FB7185'] as [string, string, string, string],
  accent: '#38BDF8',
  accentDark: '#7DD3FC',
  accentPink: '#FB7185',
  accentViolet: '#A78BFA',
  skyDeep: '#0C1445',
  cloudWhite: '#E0F2FE',
  auroraGreen: '#34D399',
  catcherEmoji: '🥅',
  fallEmojis: SKY_CATCH_STARS,
  playBorder: 'rgba(56,189,248,0.42)',
  playBg: '#0C1445',
  sparkleColor: '#FBBF24',
  backText: '#E0F2FE',
  backBorder: 'rgba(56,189,248,0.38)',
  titleColor: '#F0F9FF',
  subtitleColor: 'rgba(186,230,253,0.9)',
  statLabel: 'rgba(186,230,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(56,189,248,0.32)',
  voiceIntro:
    'Welcome to the aurora sky! Stars fall diagonally — slide your cloud net along the bottom to catch them before they pass!',
  voiceDrag: 'Slide the net under the falling star!',
  voiceComplete: 'Sky legend! You caught every star that crossed the sky!',
  voiceMiss: 'Move faster — slide the net under the falling star!',
  voiceCaught: 'Snagged!',
  congrats: 'Sky Catch Champion!',
} as const;
