/** Auto-generated from assets/speech/level2 — run `node scripts/genLevel2Assets.js` after adding images. */
import type { ImageSourcePropType } from 'react-native';

export type Level2ImageKey = 'action-building' | 'action-clapping' | 'action-cooking' | 'action-crying' | 'action-drawing' | 'action-drinking' | 'action-driving' | 'action-eating' | 'action-flying' | 'action-kicking' | 'action-painting' | 'action-reading' | 'action-running' | 'action-singing' | 'action-sitting' | 'action-sleeping' | 'action-writing' | 'ant' | 'apple' | 'avatar-child-clap' | 'avatar-child-dance' | 'avatar-child-freeze-pose' | 'avatar-child-hop' | 'avatar-child-jump' | 'avatar-child-neutral' | 'avatar-child-spin' | 'avatar-child-star-pose' | 'avatar-child-tree-pose' | 'avatar-child-wiggle' | 'baby' | 'ball-big' | 'ball-small' | 'ballon' | 'banana' | 'bandage' | 'bath-tub' | 'bed' | 'bee' | 'bell' | 'bike' | 'bird' | 'boat' | 'body-arm' | 'body-ears' | 'body-eyes' | 'body-feet' | 'body-hair' | 'body-hands' | 'body-head' | 'body-knee' | 'body-legs' | 'body-mouth' | 'body-nose' | 'body-shoulders' | 'body-toes' | 'book' | 'book-stack' | 'books-many' | 'books-one' | 'bookshelf' | 'box' | 'boy' | 'bread' | 'bread-loaf' | 'brick' | 'brocoli' | 'brother' | 'bus' | 'candle' | 'car' | 'car-in-garage' | 'carrot' | 'cat' | 'cats-many' | 'cats-one' | 'chair' | 'cheese' | 'clothing-hat' | 'clothing-pants' | 'clothing-shirt' | 'comb' | 'corn' | 'cow' | 'crate' | 'cup' | 'dad' | 'dining-table' | 'doctor' | 'dog' | 'dogs-many' | 'dogs-one' | 'door' | 'egg' | 'elephant' | 'envelope' | 'finish-flag' | 'fire-fighter' | 'fire-flame' | 'fire-truck' | 'fish' | 'flower' | 'flower-bloom' | 'forest-trees' | 'fork' | 'fridge' | 'friends-two-kids' | 'garage-bus' | 'garage-car' | 'garage-plane' | 'girl' | 'glove' | 'grandma' | 'grandpa' | 'grapes' | 'guitar' | 'hammer' | 'hat-cap' | 'hat-top-hat' | 'heart' | 'horse' | 'house' | 'ice-cream' | 'key' | 'leaf' | 'letter-a' | 'letter-b' | 'letter-c' | 'letter-d' | 'letter-k' | 'letter-m' | 'letter-p' | 'letter-r' | 'letter-s' | 'letter-t' | 'letter-w' | 'letter-z' | 'librarian' | 'lion' | 'mailcarrier' | 'medal-first' | 'milk' | 'mom' | 'moon' | 'moon-night' | 'nail' | 'number-1' | 'number-2' | 'number-3' | 'orange' | 'paint-brush' | 'paint-pallete' | 'pajamas' | 'pan' | 'paper' | 'phone' | 'pillow' | 'place-beach' | 'place-farm' | 'place-fire-station' | 'place-hospital' | 'place-library' | 'place-park' | 'place-school' | 'place-zoo' | 'plane' | 'plant-seed' | 'plate' | 'police-officer' | 'rock' | 'roof' | 'room-backyard' | 'room-bathroom' | 'room-bedroom' | 'room-garage' | 'room-kitchen' | 'room-living' | 'room-office' | 'ruler' | 'sandwich' | 'sandwich-fillings' | 'scene-fruit-basket' | 'scene-mystery-bag' | 'school-bus' | 'scissors' | 'shoe' | 'sister' | 'sleeping-child' | 'sock' | 'sofa' | 'spoon' | 'star' | 'sun' | 'sun-noon' | 'sunrise' | 'teacher' | 'teddy' | 'tiger' | 'tomato' | 'toothbrush' | 'train-car-blue' | 'train-car-red' | 'train-car-yellow' | 'train-engine' | 'tree' | 'tree-palm' | 'ui-arrow-down' | 'ui-question-slot' | 'umbrella' | 'volleyball' | 'watch' | 'watering-can';

export const LEVEL2_IMAGES: Record<Level2ImageKey, ImageSourcePropType> = {
  'action-building': require('@/assets/speech/level2/actions/action-building.png'),
  'action-clapping': require('@/assets/speech/level2/actions/action-clapping.png'),
  'action-cooking': require('@/assets/speech/level2/actions/action-cooking.png'),
  'action-crying': require('@/assets/speech/level2/actions/action-crying.png'),
  'action-drawing': require('@/assets/speech/level2/actions/action-drawing.png'),
  'action-drinking': require('@/assets/speech/level2/actions/action-drinking.png'),
  'action-driving': require('@/assets/speech/level2/actions/action-driving.png'),
  'action-eating': require('@/assets/speech/level2/actions/action-eating.png'),
  'action-flying': require('@/assets/speech/level2/actions/action-flying.png'),
  'action-kicking': require('@/assets/speech/level2/actions/action-kicking.png'),
  'action-painting': require('@/assets/speech/level2/actions/action-painting.png'),
  'action-reading': require('@/assets/speech/level2/actions/action-reading.png'),
  'action-running': require('@/assets/speech/level2/actions/action-running.png'),
  'action-singing': require('@/assets/speech/level2/actions/action-singing.png'),
  'action-sitting': require('@/assets/speech/level2/actions/action-sitting.png'),
  'action-sleeping': require('@/assets/speech/level2/actions/action-sleeping.png'),
  'action-writing': require('@/assets/speech/level2/actions/action-writing.png'),
  'ant': require('@/assets/speech/level2/animals/ant.png'),
  'apple': require('@/assets/speech/level2/food/apple.png'),
  'avatar-child-clap': require('@/assets/speech/level2/characters/avatar-child-clap.png'),
  'avatar-child-dance': require('@/assets/speech/level2/characters/avatar-child-dance.png'),
  'avatar-child-freeze-pose': require('@/assets/speech/level2/characters/avatar-child-freeze-pose.png'),
  'avatar-child-hop': require('@/assets/speech/level2/characters/avatar-child-hop.png'),
  'avatar-child-jump': require('@/assets/speech/level2/characters/avatar-child-jump.png'),
  'avatar-child-neutral': require('@/assets/speech/level2/characters/avatar-child-neutral.png'),
  'avatar-child-spin': require('@/assets/speech/level2/characters/avatar-child-spin.png'),
  'avatar-child-star-pose': require('@/assets/speech/level2/characters/avatar-child-star-pose.png'),
  'avatar-child-tree-pose': require('@/assets/speech/level2/characters/avatar-child-tree-pose.png'),
  'avatar-child-wiggle': require('@/assets/speech/level2/characters/avatar-child-wiggle.png'),
  'baby': require('@/assets/speech/level2/characters/baby.png'),
  'ball-big': require('@/assets/speech/level2/objects/ball-big.png'),
  'ball-small': require('@/assets/speech/level2/objects/ball-small.png'),
  'ballon': require('@/assets/speech/level2/objects/ballon.png'),
  'banana': require('@/assets/speech/level2/food/banana.png'),
  'bandage': require('@/assets/speech/level2/objects/bandage.png'),
  'bath-tub': require('@/assets/speech/level2/sequenceordericons/bath-tub.png'),
  'bed': require('@/assets/speech/level2/objects/bed.png'),
  'bee': require('@/assets/speech/level2/animals/bee.png'),
  'bell': require('@/assets/speech/level2/objects/bell.png'),
  'bike': require('@/assets/speech/level2/vehicles/bike.png'),
  'bird': require('@/assets/speech/level2/animals/bird.png'),
  'boat': require('@/assets/speech/level2/vehicles/boat.png'),
  'body-arm': require('@/assets/speech/level2/body/body-arm.png'),
  'body-ears': require('@/assets/speech/level2/body/body-ears.png'),
  'body-eyes': require('@/assets/speech/level2/body/body-eyes.png'),
  'body-feet': require('@/assets/speech/level2/body/body-feet.png'),
  'body-hair': require('@/assets/speech/level2/body/body-hair.png'),
  'body-hands': require('@/assets/speech/level2/body/body-hands.png'),
  'body-head': require('@/assets/speech/level2/body/body-head.png'),
  'body-knee': require('@/assets/speech/level2/body/body-knee.png'),
  'body-legs': require('@/assets/speech/level2/body/body-legs.png'),
  'body-mouth': require('@/assets/speech/level2/body/body-mouth.png'),
  'body-nose': require('@/assets/speech/level2/body/body-nose.png'),
  'body-shoulders': require('@/assets/speech/level2/body/body-shoulders.png'),
  'body-toes': require('@/assets/speech/level2/body/body-toes.png'),
  'book': require('@/assets/speech/level2/objects/book.png'),
  'book-stack': require('@/assets/speech/level2/objects/book-stack.png'),
  'books-many': require('@/assets/speech/level2/singular-plural/books-many.png'),
  'books-one': require('@/assets/speech/level2/singular-plural/books-one.png'),
  'bookshelf': require('@/assets/speech/level2/objects/bookshelf.png'),
  'box': require('@/assets/speech/level2/objects/box.png'),
  'boy': require('@/assets/speech/level2/characters/boy.png'),
  'bread': require('@/assets/speech/level2/food/bread.png'),
  'bread-loaf': require('@/assets/speech/level2/sequenceordericons/bread-loaf.png'),
  'brick': require('@/assets/speech/level2/objects/brick.png'),
  'brocoli': require('@/assets/speech/level2/food/brocoli.png'),
  'brother': require('@/assets/speech/level2/characters/brother.png'),
  'bus': require('@/assets/speech/level2/vehicles/bus.png'),
  'candle': require('@/assets/speech/level2/objects/candle.png'),
  'car': require('@/assets/speech/level2/vehicles/car.png'),
  'car-in-garage': require('@/assets/speech/level2/objects/car-in-garage.png'),
  'carrot': require('@/assets/speech/level2/food/carrot.png'),
  'cat': require('@/assets/speech/level2/animals/cat.png'),
  'cats-many': require('@/assets/speech/level2/singular-plural/cats-many.png'),
  'cats-one': require('@/assets/speech/level2/singular-plural/cats-one.png'),
  'chair': require('@/assets/speech/level2/objects/chair.png'),
  'cheese': require('@/assets/speech/level2/food/cheese.png'),
  'clothing-hat': require('@/assets/speech/level2/body/clothing-hat.png'),
  'clothing-pants': require('@/assets/speech/level2/body/clothing-pants.png'),
  'clothing-shirt': require('@/assets/speech/level2/body/clothing-shirt.png'),
  'comb': require('@/assets/speech/level2/objects/comb.png'),
  'corn': require('@/assets/speech/level2/food/corn.png'),
  'cow': require('@/assets/speech/level2/animals/cow.png'),
  'crate': require('@/assets/speech/level2/objects/crate.png'),
  'cup': require('@/assets/speech/level2/objects/cup.png'),
  'dad': require('@/assets/speech/level2/characters/dad.png'),
  'dining-table': require('@/assets/speech/level2/objects/dining-table.png'),
  'doctor': require('@/assets/speech/level2/characters/doctor.png'),
  'dog': require('@/assets/speech/level2/animals/dog.png'),
  'dogs-many': require('@/assets/speech/level2/singular-plural/dogs-many.png'),
  'dogs-one': require('@/assets/speech/level2/singular-plural/dogs-one.png'),
  'door': require('@/assets/speech/level2/objects/door.png'),
  'egg': require('@/assets/speech/level2/food/egg.png'),
  'elephant': require('@/assets/speech/level2/animals/elephant.png'),
  'envelope': require('@/assets/speech/level2/objects/envelope.png'),
  'finish-flag': require('@/assets/speech/level2/sequenceordericons/finish-flag.png'),
  'fire-fighter': require('@/assets/speech/level2/characters/fire-fighter.png'),
  'fire-flame': require('@/assets/speech/level2/objects/fire-flame.png'),
  'fire-truck': require('@/assets/speech/level2/objects/fire-truck.png'),
  'fish': require('@/assets/speech/level2/animals/fish.png'),
  'flower': require('@/assets/speech/level2/objects/flower.png'),
  'flower-bloom': require('@/assets/speech/level2/sequenceordericons/flower-bloom.png'),
  'forest-trees': require('@/assets/speech/level2/objects/forest-trees.png'),
  'fork': require('@/assets/speech/level2/objects/fork.png'),
  'fridge': require('@/assets/speech/level2/objects/fridge.png'),
  'friends-two-kids': require('@/assets/speech/level2/characters/friends-two-kids.png'),
  'garage-bus': require('@/assets/speech/level2/scenes/garage-bus.png'),
  'garage-car': require('@/assets/speech/level2/scenes/garage-car.png'),
  'garage-plane': require('@/assets/speech/level2/scenes/garage-plane.png'),
  'girl': require('@/assets/speech/level2/characters/girl.png'),
  'glove': require('@/assets/speech/level2/objects/glove.png'),
  'grandma': require('@/assets/speech/level2/characters/grandma.png'),
  'grandpa': require('@/assets/speech/level2/characters/grandpa.png'),
  'grapes': require('@/assets/speech/level2/food/grapes.png'),
  'guitar': require('@/assets/speech/level2/objects/guitar.png'),
  'hammer': require('@/assets/speech/level2/objects/hammer.png'),
  'hat-cap': require('@/assets/speech/level2/objects/hat-cap.png'),
  'hat-top-hat': require('@/assets/speech/level2/objects/hat-top-hat.png'),
  'heart': require('@/assets/speech/level2/objects/heart.png'),
  'horse': require('@/assets/speech/level2/animals/horse.png'),
  'house': require('@/assets/speech/level2/objects/house.png'),
  'ice-cream': require('@/assets/speech/level2/food/ice-cream.png'),
  'key': require('@/assets/speech/level2/objects/key.png'),
  'leaf': require('@/assets/speech/level2/objects/leaf.png'),
  'letter-a': require('@/assets/speech/level2/scenes/letter-a.png'),
  'letter-b': require('@/assets/speech/level2/scenes/letter-b.png'),
  'letter-c': require('@/assets/speech/level2/scenes/letter-c.png'),
  'letter-d': require('@/assets/speech/level2/scenes/letter-d.png'),
  'letter-k': require('@/assets/speech/level2/scenes/letter-k.png'),
  'letter-m': require('@/assets/speech/level2/scenes/letter-m.png'),
  'letter-p': require('@/assets/speech/level2/scenes/letter-p.png'),
  'letter-r': require('@/assets/speech/level2/scenes/letter-r.png'),
  'letter-s': require('@/assets/speech/level2/scenes/letter-s.png'),
  'letter-t': require('@/assets/speech/level2/scenes/letter-t.png'),
  'letter-w': require('@/assets/speech/level2/scenes/letter-w.png'),
  'letter-z': require('@/assets/speech/level2/scenes/letter-z.png'),
  'librarian': require('@/assets/speech/level2/characters/librarian.png'),
  'lion': require('@/assets/speech/level2/animals/lion.png'),
  'mailcarrier': require('@/assets/speech/level2/characters/mailcarrier.png'),
  'medal-first': require('@/assets/speech/level2/sequenceordericons/medal-first.png'),
  'milk': require('@/assets/speech/level2/food/milk.png'),
  'mom': require('@/assets/speech/level2/characters/mom.png'),
  'moon': require('@/assets/speech/level2/objects/moon.png'),
  'moon-night': require('@/assets/speech/level2/sequenceordericons/moon-night.png'),
  'nail': require('@/assets/speech/level2/objects/nail.png'),
  'number-1': require('@/assets/speech/level2/sequenceordericons/number-1.png'),
  'number-2': require('@/assets/speech/level2/sequenceordericons/number-2.png'),
  'number-3': require('@/assets/speech/level2/sequenceordericons/number-3.png'),
  'orange': require('@/assets/speech/level2/food/orange.png'),
  'paint-brush': require('@/assets/speech/level2/objects/paint-brush.png'),
  'paint-pallete': require('@/assets/speech/level2/objects/paint-pallete.png'),
  'pajamas': require('@/assets/speech/level2/sequenceordericons/pajamas.png'),
  'pan': require('@/assets/speech/level2/objects/pan.png'),
  'paper': require('@/assets/speech/level2/objects/paper.png'),
  'phone': require('@/assets/speech/level2/objects/phone.png'),
  'pillow': require('@/assets/speech/level2/objects/pillow.png'),
  'place-beach': require('@/assets/speech/level2/rooms and places/place-beach.png'),
  'place-farm': require('@/assets/speech/level2/rooms and places/place-farm.png'),
  'place-fire-station': require('@/assets/speech/level2/rooms and places/place-fire-station.png'),
  'place-hospital': require('@/assets/speech/level2/rooms and places/place-hospital.png'),
  'place-library': require('@/assets/speech/level2/rooms and places/place-library.png'),
  'place-park': require('@/assets/speech/level2/rooms and places/place-park.png'),
  'place-school': require('@/assets/speech/level2/rooms and places/place-school.png'),
  'place-zoo': require('@/assets/speech/level2/rooms and places/place-zoo.png'),
  'plane': require('@/assets/speech/level2/vehicles/plane.png'),
  'plant-seed': require('@/assets/speech/level2/sequenceordericons/plant-seed.png'),
  'plate': require('@/assets/speech/level2/objects/plate.png'),
  'police-officer': require('@/assets/speech/level2/characters/police-officer.png'),
  'rock': require('@/assets/speech/level2/objects/rock.png'),
  'roof': require('@/assets/speech/level2/objects/roof.png'),
  'room-backyard': require('@/assets/speech/level2/rooms and places/room-backyard.png'),
  'room-bathroom': require('@/assets/speech/level2/rooms and places/room-bathroom.png'),
  'room-bedroom': require('@/assets/speech/level2/rooms and places/room-bedroom.png'),
  'room-garage': require('@/assets/speech/level2/rooms and places/room-garage.png'),
  'room-kitchen': require('@/assets/speech/level2/rooms and places/room-kitchen.png'),
  'room-living': require('@/assets/speech/level2/rooms and places/room-living.png'),
  'room-office': require('@/assets/speech/level2/rooms and places/room-office.png'),
  'ruler': require('@/assets/speech/level2/objects/ruler.png'),
  'sandwich': require('@/assets/speech/level2/food/sandwich.png'),
  'sandwich-fillings': require('@/assets/speech/level2/food/sandwich-fillings.png'),
  'scene-fruit-basket': require('@/assets/speech/level2/scenes/scene-fruit-basket.png'),
  'scene-mystery-bag': require('@/assets/speech/level2/scenes/scene-mystery-bag.png'),
  'school-bus': require('@/assets/speech/level2/objects/school-bus.png'),
  'scissors': require('@/assets/speech/level2/objects/scissors.png'),
  'shoe': require('@/assets/speech/level2/objects/shoe.png'),
  'sister': require('@/assets/speech/level2/characters/sister.png'),
  'sleeping-child': require('@/assets/speech/level2/sequenceordericons/sleeping-child.png'),
  'sock': require('@/assets/speech/level2/objects/sock.png'),
  'sofa': require('@/assets/speech/level2/objects/sofa.png'),
  'spoon': require('@/assets/speech/level2/objects/spoon.png'),
  'star': require('@/assets/speech/level2/objects/star.png'),
  'sun': require('@/assets/speech/level2/objects/sun.png'),
  'sun-noon': require('@/assets/speech/level2/sequenceordericons/sun-noon.png'),
  'sunrise': require('@/assets/speech/level2/sequenceordericons/sunrise.png'),
  'teacher': require('@/assets/speech/level2/characters/teacher.png'),
  'teddy': require('@/assets/speech/level2/objects/teddy.png'),
  'tiger': require('@/assets/speech/level2/animals/tiger.png'),
  'tomato': require('@/assets/speech/level2/food/tomato.png'),
  'toothbrush': require('@/assets/speech/level2/objects/toothbrush.png'),
  'train-car-blue': require('@/assets/speech/level2/scenes/train-car-blue.png'),
  'train-car-red': require('@/assets/speech/level2/scenes/train-car-red.png'),
  'train-car-yellow': require('@/assets/speech/level2/scenes/train-car-yellow.png'),
  'train-engine': require('@/assets/speech/level2/scenes/train-engine.png'),
  'tree': require('@/assets/speech/level2/objects/tree.png'),
  'tree-palm': require('@/assets/speech/level2/objects/tree-palm.png'),
  'ui-arrow-down': require('@/assets/speech/level2/ui/ui-arrow-down.png'),
  'ui-question-slot': require('@/assets/speech/level2/ui/ui-question-slot.png'),
  'umbrella': require('@/assets/speech/level2/objects/umbrella.png'),
  'volleyball': require('@/assets/speech/level2/objects/volleyball.png'),
  'watch': require('@/assets/speech/level2/objects/watch.png'),
  'watering-can': require('@/assets/speech/level2/sequenceordericons/watering-can.png'),
};

export function getLevel2Image(key: Level2ImageKey): ImageSourcePropType {
  return LEVEL2_IMAGES[key];
}

/** Scene backgrounds / props (assets/speech/level2/scenes) */
export type Level2SceneImageKey = 'garage-bus' | 'garage-car' | 'garage-plane' | 'letter-a' | 'letter-b' | 'letter-c' | 'letter-d' | 'letter-k' | 'letter-m' | 'letter-p' | 'letter-r' | 'letter-s' | 'letter-t' | 'letter-w' | 'letter-z' | 'scene-fruit-basket' | 'scene-mystery-bag' | 'train-car-blue' | 'train-car-red' | 'train-car-yellow' | 'train-engine';

/** UI chrome (assets/speech/level2/ui) */
export type Level2UiImageKey = 'ui-arrow-down' | 'ui-question-slot';

export const LEVEL2_SCENE_IMAGE_KEYS = ['garage-bus', 'garage-car', 'garage-plane', 'letter-a', 'letter-b', 'letter-c', 'letter-d', 'letter-k', 'letter-m', 'letter-p', 'letter-r', 'letter-s', 'letter-t', 'letter-w', 'letter-z', 'scene-fruit-basket', 'scene-mystery-bag', 'train-car-blue', 'train-car-red', 'train-car-yellow', 'train-engine'] as const;
export const LEVEL2_UI_IMAGE_KEYS = ['ui-arrow-down', 'ui-question-slot'] as const;
