import type { ReverseHorizontalDragGameConfig } from '@/components/game/occupational/level4/session2/shared/ReverseHorizontalDragGame';

export const STAR_SWEEP_STARS = ['⭐', '🌟', '✨', '💫'] as const;

export const STAR_SWEEP_THEME = {
  title: 'Star Sweep',
  subtitle: 'Sweep falling stars from the sky into your cosmic bag',
  emoji: '🌌',
  gradient: ['#0F0520', '#1E1B4B', '#4C1D95', '#7C3AED'] as [string, string, string, string],
  accent: '#FCD34D',
  accentDark: '#EAB308',
  accentViolet: '#C4B5FD',
  nebulaPink: '#F472B6',
  spaceDark: '#0F0520',
  bagPurple: '#5B21B6',
  draggableEmoji: '⭐',
  targetEmoji: '🎒',
  playBorder: 'rgba(196,181,253,0.42)',
  playBg: '#1E1033',
  sparkleColor: '#FCD34D',
  zoneBorder: 'rgba(196,181,253,0.45)',
  voiceIntro: 'Welcome to the star field! Sweep each star from the right into your cosmic bag on the left!',
  voiceDrag: 'Slide the star into the bag!',
  voiceComplete: 'The whole galaxy is in your bag! Amazing star sweeping!',
  voiceMiss: 'Guide the star into the cosmic bag on the left!',
  voiceCaught: 'Star caught!',
  congrats: 'Galaxy Collector!',
} as const;

export const STAR_SWEEP_CONFIG: Omit<ReverseHorizontalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'collectStars',
  theme: {
    title: STAR_SWEEP_THEME.title,
    subtitle: STAR_SWEEP_THEME.subtitle,
    emoji: STAR_SWEEP_THEME.emoji,
    gradient: STAR_SWEEP_THEME.gradient,
    accent: STAR_SWEEP_THEME.accent,
    accentDark: STAR_SWEEP_THEME.accentDark,
    draggableEmoji: STAR_SWEEP_THEME.draggableEmoji,
    targetEmoji: STAR_SWEEP_THEME.targetEmoji,
    backText: '#EDE9FE',
    backBorder: 'rgba(196,181,253,0.38)',
    titleColor: '#F5F3FF',
    subtitleColor: 'rgba(221,214,254,0.9)',
    statLabel: 'rgba(221,214,254,0.75)',
    statValue: '#FFFFFF',
    statBorder: 'rgba(196,181,253,0.32)',
    playBorder: STAR_SWEEP_THEME.playBorder,
    playBg: STAR_SWEEP_THEME.playBg,
    sparkleColor: STAR_SWEEP_THEME.sparkleColor,
    zoneBorder: STAR_SWEEP_THEME.zoneBorder,
  },
  ttsIntro: STAR_SWEEP_THEME.voiceIntro,
  ttsComplete: STAR_SWEEP_THEME.voiceComplete,
  ttsDrag: STAR_SWEEP_THEME.voiceDrag,
  ttsMiss: STAR_SWEEP_THEME.voiceMiss,
  ttsGoal: STAR_SWEEP_THEME.voiceCaught,
  congratsMessage: STAR_SWEEP_THEME.congrats,
  logType: 'collect-stars',
  skillTags: ['cross-body-reach', 'drag-right-left'],
};
