/**
 * OT Level 4 Session 6 — Pass ball across midline theme tokens.
 */

/** Game 1 — Hand Swap · Midline bridge transfer zone */
export const HAND_SWAP_THEME = {
  title: 'Hand Swap',
  subtitle: 'Pass the ball left ↔ right across your body midline!',
  emoji: '🤲',
  gradient: ['#0C1929', '#0F2744', '#1E3A5F', '#2563EB'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#A5F3FC',
  accentBlue: '#3B82F6',
  accentTeal: '#14B8A6',
  bridgeDark: '#0C1929',
  midlineGlow: '#22D3EE',
  leftColor: '#3B82F6',
  rightColor: '#14B8A6',
  ballEmoji: '⚽',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#0C1929',
  sparkleColor: '#22D3EE',
  backText: '#E0F2FE',
  backBorder: 'rgba(34,211,238,0.38)',
  titleColor: '#F0F9FF',
  subtitleColor: 'rgba(186,230,253,0.9)',
  statLabel: 'rgba(186,230,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(34,211,238,0.32)',
  voiceIntro:
    'Welcome to the midline bridge! Pass the ball from your left hand to your right, then back across your body!',
  voiceCue: 'Tap the hand holding the ball to swap across midline!',
  voiceComplete: 'Amazing swapping! You crossed midline every time!',
  voiceSuccess: 'Perfect swap!',
  voiceWrong: 'Tap the hand that has the ball!',
  congrats: 'Hand Swap Star!',
} as const;

/** Game 2 — Toss & Grab · Sunny tennis court (throw left, catch right) */
export const TOSS_GRAB_THEME = {
  title: 'Toss & Grab',
  subtitle: 'Throw with left, catch with right — arc across the net!',
  emoji: '🎾',
  gradient: ['#14532D', '#166534', '#CA8A04', '#F59E0B'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FEF3C7',
  accentGreen: '#22C55E',
  accentGold: '#F59E0B',
  courtDark: '#14532D',
  netWhite: '#FEF3C7',
  leftColor: '#22C55E',
  rightColor: '#F59E0B',
  ballEmoji: '🎾',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#14532D',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,243,199,0.9)',
  statLabel: 'rgba(254,243,199,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the tennis court! Throw the ball with your left hand, then catch it with your right across the net!',
  voiceCue: 'Tap left to throw, then right to catch!',
  voiceComplete: 'Amazing toss and grab! You nailed every throw and catch!',
  voiceSuccess: 'Great catch!',
  voiceWrong: 'Wait for the ball!',
  voiceMiss: 'Missed the catch — throw again!',
  congrats: 'Toss & Grab Star!',
} as const;

/** Game 3 — Aim Pass · Red archery lane (drag ball to bullseye across midline) */
export const AIM_PASS_THEME = {
  title: 'Aim Pass',
  subtitle: 'Drag from the left — cross midline and hit the bullseye!',
  emoji: '🎯',
  gradient: ['#450A0A', '#7F1D1D', '#B91C1C', '#EF4444'] as [string, string, string, string],
  accent: '#EF4444',
  accentDark: '#FECACA',
  accentCrimson: '#DC2626',
  accentGold: '#FBBF24',
  laneDark: '#450A0A',
  bullseyeGlow: '#FBBF24',
  ballEmoji: '⚽',
  targetEmoji: '🎯',
  obstacleEmoji: '🚧',
  playBorder: 'rgba(239,68,68,0.42)',
  playBg: '#450A0A',
  sparkleColor: '#FBBF24',
  midlineColor: 'rgba(251,191,36,0.55)',
  backText: '#FEE2E2',
  backBorder: 'rgba(239,68,68,0.38)',
  titleColor: '#FEF2F2',
  subtitleColor: 'rgba(254,202,202,0.9)',
  statLabel: 'rgba(254,202,202,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(239,68,68,0.32)',
  voiceIntro:
    'Welcome to the archery lane! Drag the ball from the left, cross the golden midline, and land on the bullseye!',
  voiceDrag: 'Drag the ball left to right — cross the line and hit the bullseye!',
  voiceComplete: 'Sharpshooter! You hit every bullseye across midline!',
  voiceSuccess: 'Bullseye!',
  voiceMiss: 'Missed the target — drag to the bullseye on the right!',
  voiceCross: 'Cross the midline first, then aim for the bullseye!',
  congrats: 'Aim Pass Star!',
} as const;

/** Game 4 — Beat Pass · Purple neon rhythm stage (tap on beat to pass ball) */
export const BEAT_PASS_THEME = {
  title: 'Beat Pass',
  subtitle: 'Wait for the beat flash — tap the hand holding the ball!',
  emoji: '🎵',
  gradient: ['#1E1B4B', '#312E81', '#5B21B6', '#7C3AED'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  accentViolet: '#8B5CF6',
  accentPink: '#E879F9',
  stageDark: '#1E1B4B',
  beatGlow: '#C4B5FD',
  leftColor: '#8B5CF6',
  rightColor: '#E879F9',
  ballEmoji: '🏀',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#1E1B4B',
  sparkleColor: '#C4B5FD',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(196,181,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the beat stage! When the neon beat flashes, tap the hand that holds the ball — four beats to finish each round!',
  voiceCue: 'Wait for the beat flash, then tap the hand with the ball!',
  voiceComplete: 'Grooving rhythm! You passed on every beat across midline!',
  voiceSuccess: 'On beat!',
  voiceWrong: 'Wait for the beat flash first!',
  voiceMissBeat: 'Missed the beat — wait for the next flash!',
  congrats: 'Beat Pass Virtuoso!',
} as const;

/** Game 5 — Detour Pass · Construction site (drag up and around barrier) */
export const DETOUR_PASS_THEME = {
  title: 'Detour Pass',
  subtitle: 'Go up and around the barrier — reach the goal on the right!',
  emoji: '🚧',
  gradient: ['#064E3B', '#065F46', '#047857', '#10B981'] as [string, string, string, string],
  accent: '#10B981',
  accentDark: '#A7F3D0',
  accentAmber: '#FBBF24',
  accentOrange: '#F97316',
  siteDark: '#064E3B',
  barrierGlow: '#FBBF24',
  ballEmoji: '⚽',
  targetEmoji: '🎯',
  obstacleEmoji: '🚧',
  playBorder: 'rgba(16,185,129,0.42)',
  playBg: '#064E3B',
  sparkleColor: '#34D399',
  midlineColor: 'rgba(251,191,36,0.55)',
  backText: '#D1FAE5',
  backBorder: 'rgba(16,185,129,0.38)',
  titleColor: '#ECFDF5',
  subtitleColor: 'rgba(167,243,208,0.9)',
  statLabel: 'rgba(167,243,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(16,185,129,0.32)',
  voiceIntro:
    'Welcome to the construction detour! Drag the ball up, go around the barrier on the right, and reach the goal!',
  voiceDrag: 'Go up, then right around the barrier to the goal!',
  voiceComplete: 'Master planner! You detoured around every barrier!',
  voiceSuccess: 'Detour complete!',
  voiceMiss: 'Go around the barrier to reach the goal!',
  voiceObstacle: 'You hit the barrier! Go up and around it!',
  voiceDetourCross: 'Go around via the right side first!',
  congrats: 'Detour Pass Star!',
} as const;
