/**
 * OT Level 4 Session 7 — Cross-body arrow theme tokens.
 */

/** Game 1 — Cross Tap · Neural bridge (opposite-hand arrow matching) */
export const CROSS_TAP_THEME = {
  title: 'Cross Tap',
  subtitle: 'Left arrow → right hand! Train your brain crossover!',
  emoji: '⬅️',
  gradient: ['#0F172A', '#1E1B4B', '#312E81', '#4338CA'] as [string, string, string, string],
  accent: '#818CF8',
  accentDark: '#C7D2FE',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  bridgeGlow: '#818CF8',
  synapseLeft: '#60A5FA',
  synapseRight: '#FB7185',
  playBorder: 'rgba(129,140,248,0.42)',
  playBg: '#0F172A',
  sparkleColor: '#818CF8',
  backText: '#E0E7FF',
  backBorder: 'rgba(129,140,248,0.38)',
  titleColor: '#EEF2FF',
  subtitleColor: 'rgba(199,210,254,0.9)',
  statLabel: 'rgba(199,210,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(129,140,248,0.32)',
  voiceIntro:
    'Welcome to the neural bridge! When you see a left arrow, tap with your right hand — cross your body!',
  voiceCue: 'Opposite hand for each arrow — left arrow means right hand!',
  voiceComplete: 'Amazing crossover! Your brain pathways are stronger!',
  voiceSuccess: 'Perfect cross tap!',
  voiceWrong: 'Use the opposite hand — cross your body!',
  voiceTooSlow: 'Too slow — catch the arrow!',
  congrats: 'Cross Tap Champion!',
} as const;

/** Game 2 — Swipe Cross · Wind tunnel (cross-body swipe arcs) */
export const SWIPE_CROSS_THEME = {
  title: 'Swipe Cross',
  subtitle: 'Swipe across your body — opposite direction!',
  emoji: '➡️',
  gradient: ['#450A0A', '#7F1D1D', '#991B1B', '#DC2626'] as [string, string, string, string],
  accent: '#F87171',
  accentDark: '#FECACA',
  trailGlow: '#FB7185',
  arcLeft: '#FCA5A5',
  arcRight: '#F97316',
  playBorder: 'rgba(248,113,113,0.42)',
  playBg: '#450A0A',
  sparkleColor: '#F87171',
  backText: '#FEE2E2',
  backBorder: 'rgba(248,113,113,0.38)',
  titleColor: '#FEF2F2',
  subtitleColor: 'rgba(254,202,202,0.9)',
  statLabel: 'rgba(254,202,202,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(248,113,113,0.32)',
  voiceIntro:
    'Welcome to the wind tunnel! See an arrow, then swipe the opposite way — across your body!',
  voiceCue: 'Swipe across your body in the opposite direction!',
  voiceComplete: 'Powerful cross-body swipes! Your coordination is on fire!',
  voiceSuccess: 'Perfect swipe!',
  voiceMiss: 'Swipe the opposite direction — cross your body!',
  congrats: 'Swipe Cross Champion!',
} as const;

/** Game 3 — Drift Tap · Nebula drift (track moving arrows, cross-body tap) */
export const DRIFT_TAP_THEME = {
  title: 'Drift Tap',
  subtitle: 'Track the drifting arrow — tap with the opposite hand!',
  emoji: '🌠',
  gradient: ['#2E1065', '#4C1D95', '#6D28D9', '#8B5CF6'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  driftGlow: '#C4B5FD',
  cometLeft: '#8B5CF6',
  cometRight: '#F472B6',
  leftColor: '#8B5CF6',
  rightColor: '#F472B6',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#2E1065',
  sparkleColor: '#A78BFA',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(221,214,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the nebula drift zone! Track the moving arrow and tap with your opposite hand before it floats away!',
  voiceCue: 'Catch the drifting arrow — use the opposite hand!',
  voiceComplete: 'Stellar tracking! You caught every drifting arrow!',
  voiceSuccess: 'Caught it!',
  voiceWrong: 'Use the opposite hand — cross your body!',
  voiceTooSlow: 'Too slow! Catch the arrow!',
  congrats: 'Drift Tap Champion!',
} as const;

/** Game 4 — Arrow Chain · Memory circuit (watch 3 arrows, tap in order) */
export const ARROW_CHAIN_THEME = {
  title: 'Arrow Chain',
  subtitle: 'Watch the chain — tap opposite hands in order!',
  emoji: '🔗',
  gradient: ['#022C22', '#064E3B', '#047857', '#10B981'] as [string, string, string, string],
  accent: '#34D399',
  accentDark: '#A7F3D0',
  linkGlow: '#6EE7B7',
  nodeLeft: '#10B981',
  nodeRight: '#F43F5E',
  leftColor: '#10B981',
  rightColor: '#F43F5E',
  playBorder: 'rgba(52,211,153,0.42)',
  playBg: '#022C22',
  sparkleColor: '#34D399',
  backText: '#D1FAE5',
  backBorder: 'rgba(52,211,153,0.38)',
  titleColor: '#ECFDF5',
  subtitleColor: 'rgba(167,243,208,0.9)',
  statLabel: 'rgba(167,243,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(52,211,153,0.32)',
  voiceIntro:
    'Welcome to the memory chain! Watch three arrows light up, then tap the opposite hand for each one in order!',
  voiceCue: 'Watch the arrows, then tap opposite hands in order!',
  voiceComplete: 'Chain mastered! Your memory and crossover skills are linked!',
  voiceSuccess: 'Perfect chain!',
  voiceWrong: 'Wrong hand — watch the chain again!',
  congrats: 'Arrow Chain Champion!',
} as const;

/** Game 5 — Flash Cross · Lightning storm (fast-flash arrows, cross-body react) */
export const FLASH_CROSS_THEME = {
  title: 'Flash Cross',
  subtitle: 'Lightning-fast arrows — tap the opposite hand instantly!',
  emoji: '⚡',
  gradient: ['#451A03', '#78350F', '#B45309', '#F59E0B'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  boltGlow: '#FCD34D',
  flashLeft: '#F59E0B',
  flashRight: '#EF4444',
  leftColor: '#F59E0B',
  rightColor: '#EF4444',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#451A03',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(253,230,138,0.9)',
  statLabel: 'rgba(253,230,138,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the lightning storm! Arrows flash fast — tap the opposite hand before they vanish!',
  voiceCue: 'React fast — left arrow means right hand!',
  voiceComplete: 'Lightning reflexes! You mastered the flash cross!',
  voiceSuccess: 'Flash hit!',
  voiceWrong: 'Wrong hand — cross your body fast!',
  voiceTooSlow: 'Too slow — react faster!',
  congrats: 'Flash Cross Champion!',
} as const;
