import type { HorizontalDragGameConfig } from '@/components/game/occupational/level4/session1/shared/HorizontalDragGame';

export const QUICK_DRAG_THEME = {
  title: 'Quick Drag',
  subtitle: 'Launch across the track before the timer hits zero',
  emoji: '⚡',
  gradient: ['#1A0505', '#450A0A', '#B91C1C', '#EF4444'] as [string, string, string, string],
  accent: '#F97316',
  accentDark: '#EA580C',
  accentYellow: '#FACC15',
  trackDark: '#0F0F0F',
  trackMid: '#1C1917',
  trackGlow: '#F97316',
  launchPad: '#292524',
  finishGate: '#FACC15',
  boltBlue: '#38BDF8',
  draggableEmoji: '⚡',
  targetEmoji: '🏁',
  playBorder: 'rgba(249,115,22,0.5)',
  playBg: '#0C0A09',
  sparkleColor: '#FACC15',
  zoneBorder: 'rgba(249,115,22,0.48)',
  voiceIntro: 'Welcome to the speed track! Drag from the launch pad to the finish gate before time runs out!',
  voiceDrag: 'Wait for launch — then drag fast!',
  voiceTimed: 'Go go go! Beat the clock!',
  voiceComplete: 'Lightning fast! You beat every countdown!',
  voiceMiss: 'Aim for the finish gate!',
  voiceSlow: 'Too slow! Try again — drag faster!',
  voiceFast: 'Blazing fast!',
  congrats: 'Speed Track Legend!',
} as const;

export const QUICK_DRAG_CONFIG: Omit<HorizontalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'timedDrag',
  theme: {
    title: QUICK_DRAG_THEME.title,
    subtitle: QUICK_DRAG_THEME.subtitle,
    emoji: QUICK_DRAG_THEME.emoji,
    gradient: QUICK_DRAG_THEME.gradient,
    accent: QUICK_DRAG_THEME.accent,
    accentDark: QUICK_DRAG_THEME.accentDark,
    draggableEmoji: QUICK_DRAG_THEME.draggableEmoji,
    targetEmoji: QUICK_DRAG_THEME.targetEmoji,
    backText: '#FFEDD5',
    backBorder: 'rgba(249,115,22,0.4)',
    titleColor: '#FFF7ED',
    subtitleColor: 'rgba(254,215,170,0.92)',
    statLabel: 'rgba(254,215,170,0.75)',
    statValue: '#FFFFFF',
    statBorder: 'rgba(249,115,22,0.35)',
    playBorder: QUICK_DRAG_THEME.playBorder,
    playBg: QUICK_DRAG_THEME.playBg,
    sparkleColor: QUICK_DRAG_THEME.sparkleColor,
    zoneBorder: QUICK_DRAG_THEME.zoneBorder,
  },
  ttsIntro: QUICK_DRAG_THEME.voiceIntro,
  ttsComplete: QUICK_DRAG_THEME.voiceComplete,
  ttsDrag: QUICK_DRAG_THEME.voiceDrag,
  ttsMiss: QUICK_DRAG_THEME.voiceMiss,
  ttsTimed: QUICK_DRAG_THEME.voiceTimed,
  ttsTimedMiss: QUICK_DRAG_THEME.voiceSlow,
  ttsGoal: QUICK_DRAG_THEME.voiceFast,
  congratsMessage: QUICK_DRAG_THEME.congrats,
  logType: 'timed-drag',
  skillTags: ['speed', 'accuracy', 'drag-left-right'],
};
