import type { ReverseHorizontalDragGameConfig } from '@/components/game/occupational/level4/session2/shared/ReverseHorizontalDragGame';

export const CROSS_REACH_THEME = {
  title: 'Cross Reach',
  subtitle: 'Reach across your body — drag from right to the mirror catch on the left',
  emoji: '🤲',
  gradient: ['#1E1035', '#4C1D95', '#9A3412', '#FB923C'] as [string, string, string, string],
  accent: '#38BDF8',
  accentDark: '#7DD3FC',
  accentWarm: '#FB923C',
  accentCoral: '#FDBA74',
  studioDark: '#1A1625',
  mirrorLine: 'rgba(255,255,255,0.55)',
  leftGlow: '#0EA5E9',
  rightGlow: '#F97316',
  draggableEmoji: '✋',
  targetEmoji: '🪞',
  playBorder: 'rgba(56,189,248,0.42)',
  playBg: '#1A1625',
  sparkleColor: '#38BDF8',
  zoneBorder: 'rgba(56,189,248,0.45)',
  voiceIntro:
    'Welcome to the mirror studio! Use your right hand to reach across and land the orb in the mirror catch on the left!',
  voiceDrag: 'Reach across — slide to the left mirror!',
  voiceComplete: 'Amazing cross-body control! Your brain and hand are in perfect sync!',
  voiceMiss: 'Reach farther across — aim for the mirror catch on the left!',
  voiceReached: 'Crossed!',
  congrats: 'Cross Reach Champion!',
} as const;

export const CROSS_REACH_CONFIG: Omit<ReverseHorizontalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'mirrorDrag',
  theme: {
    title: CROSS_REACH_THEME.title,
    subtitle: CROSS_REACH_THEME.subtitle,
    emoji: CROSS_REACH_THEME.emoji,
    gradient: CROSS_REACH_THEME.gradient,
    accent: CROSS_REACH_THEME.accent,
    accentDark: CROSS_REACH_THEME.accentDark,
    draggableEmoji: CROSS_REACH_THEME.draggableEmoji,
    targetEmoji: CROSS_REACH_THEME.targetEmoji,
    backText: '#E0F2FE',
    backBorder: 'rgba(56,189,248,0.38)',
    titleColor: '#F0F9FF',
    subtitleColor: 'rgba(186,230,253,0.9)',
    statLabel: 'rgba(186,230,253,0.75)',
    statValue: '#FFFFFF',
    statBorder: 'rgba(56,189,248,0.32)',
    playBorder: CROSS_REACH_THEME.playBorder,
    playBg: CROSS_REACH_THEME.playBg,
    sparkleColor: CROSS_REACH_THEME.sparkleColor,
    zoneBorder: CROSS_REACH_THEME.zoneBorder,
  },
  ttsIntro: CROSS_REACH_THEME.voiceIntro,
  ttsComplete: CROSS_REACH_THEME.voiceComplete,
  ttsDrag: CROSS_REACH_THEME.voiceDrag,
  ttsMiss: CROSS_REACH_THEME.voiceMiss,
  ttsGoal: CROSS_REACH_THEME.voiceReached,
  congratsMessage: CROSS_REACH_THEME.congrats,
  logType: 'mirror-drag',
  skillTags: ['brain-hand-sync', 'drag-right-left'],
};
