import type { DualPullGameConfig } from '@/components/game/occupational/level4/session9/shared/DualPullGame';

export const TUG_ROPE_THEME = {
  title: 'Tug Rope',
  subtitle: 'Grab both handles — pull outward at the same time!',
  emoji: '🪢',
  gradient: ['#422006', '#78350F', '#92400E', '#FBBF24'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  leftColor: '#F59E0B',
  rightColor: '#EF4444',
  ropeGlow: '#FCD34D',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#422006',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(253,230,138,0.9)',
  statLabel: 'rgba(253,230,138,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the tug arena! Grab both rope handles and pull outward at the same time — feel the tension!',
  voiceCue: 'Pull both handles outward together!',
  voiceComplete: 'Strong pull! Your upper body and both arms worked as one!',
  voiceSuccess: 'Perfect tug!',
  congrats: 'Tug Rope Champion!',
} as const;

export const TUG_ROPE_CONFIG: Omit<DualPullGameConfig, 'onBack' | 'onComplete'> = {
  theme: {
    title: TUG_ROPE_THEME.title,
    subtitle: TUG_ROPE_THEME.subtitle,
    emoji: TUG_ROPE_THEME.emoji,
    gradient: TUG_ROPE_THEME.gradient,
    accent: TUG_ROPE_THEME.accent,
    accentDark: TUG_ROPE_THEME.accentDark,
    leftColor: TUG_ROPE_THEME.leftColor,
    rightColor: TUG_ROPE_THEME.rightColor,
    backText: TUG_ROPE_THEME.backText,
    backBorder: TUG_ROPE_THEME.backBorder,
    titleColor: TUG_ROPE_THEME.titleColor,
    subtitleColor: TUG_ROPE_THEME.subtitleColor,
    statLabel: TUG_ROPE_THEME.statLabel,
    statValue: TUG_ROPE_THEME.statValue,
    statBorder: TUG_ROPE_THEME.statBorder,
    playBorder: TUG_ROPE_THEME.playBorder,
    playBg: TUG_ROPE_THEME.playBg,
    sparkleColor: TUG_ROPE_THEME.sparkleColor,
  },
  ttsIntro: TUG_ROPE_THEME.voiceIntro,
  ttsComplete: TUG_ROPE_THEME.voiceComplete,
  ttsCue: TUG_ROPE_THEME.voiceCue,
  ttsSuccess: TUG_ROPE_THEME.voiceSuccess,
  congratsMessage: TUG_ROPE_THEME.congrats,
  logType: 'rope-pull',
  skillTags: ['upper-body-integration', 'simultaneous-pulling', 'bilateral-coordination'],
};
