import type { MidlinePassGameConfig } from '@/components/game/occupational/level4/session6/shared/MidlinePassGame';

export const HAND_SWAP_THEME = {
  title: 'Hand Swap',
  subtitle: 'Pass the ball left ↔ right across your body midline!',
  emoji: '🤲',
  gradient: ['#0C1929', '#0F2744', '#1E3A5F', '#2563EB'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#A5F3FC',
  accentBlue: '#3B82F6',
  accentTeal: '#14B8A6',
  bridgeDark: '#0C1929',
  midlineGlow: '#22D3EE',
  leftColor: '#3B82F6',
  rightColor: '#14B8A6',
  ballEmoji: '⚽',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#0C1929',
  sparkleColor: '#22D3EE',
  backText: '#E0F2FE',
  backBorder: 'rgba(34,211,238,0.38)',
  titleColor: '#F0F9FF',
  subtitleColor: 'rgba(186,230,253,0.9)',
  statLabel: 'rgba(186,230,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(34,211,238,0.32)',
  voiceIntro:
    'Welcome to the midline bridge! Pass the ball from your left hand to your right, then back across your body!',
  voiceCue: 'Tap the hand holding the ball to swap across midline!',
  voiceComplete: 'Amazing swapping! You crossed midline every time!',
  voiceSuccess: 'Perfect swap!',
  voiceWrong: 'Tap the hand that has the ball!',
  congrats: 'Hand Swap Star!',
} as const;

export const HAND_SWAP_CONFIG: Omit<MidlinePassGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'handPass',
  theme: {
    title: HAND_SWAP_THEME.title,
    subtitle: HAND_SWAP_THEME.subtitle,
    emoji: HAND_SWAP_THEME.emoji,
    gradient: HAND_SWAP_THEME.gradient,
    accent: HAND_SWAP_THEME.accent,
    accentDark: HAND_SWAP_THEME.accentDark,
    ballEmoji: HAND_SWAP_THEME.ballEmoji,
    backText: HAND_SWAP_THEME.backText,
    backBorder: HAND_SWAP_THEME.backBorder,
    titleColor: HAND_SWAP_THEME.titleColor,
    subtitleColor: HAND_SWAP_THEME.subtitleColor,
    statLabel: HAND_SWAP_THEME.statLabel,
    statValue: HAND_SWAP_THEME.statValue,
    statBorder: HAND_SWAP_THEME.statBorder,
    playBorder: HAND_SWAP_THEME.playBorder,
    playBg: HAND_SWAP_THEME.playBg,
    sparkleColor: HAND_SWAP_THEME.sparkleColor,
    leftColor: HAND_SWAP_THEME.leftColor,
    rightColor: HAND_SWAP_THEME.rightColor,
  },
  ttsIntro: HAND_SWAP_THEME.voiceIntro,
  ttsComplete: HAND_SWAP_THEME.voiceComplete,
  ttsCue: HAND_SWAP_THEME.voiceCue,
  ttsSuccess: HAND_SWAP_THEME.voiceSuccess,
  ttsWrong: HAND_SWAP_THEME.voiceWrong,
  congratsMessage: HAND_SWAP_THEME.congrats,
  logType: 'hand-to-hand-pass',
  skillTags: ['midline-awareness', 'hand-coordination', 'ball-pass'],
};
