import type { BalanceDualDragGameConfig } from '@/components/game/occupational/level4/session9/shared/BalanceDualDragGame';

export const EVEN_PULL_THEME = {
  title: 'Even Pull',
  subtitle: 'Drag both weights down — reach the balance line together!',
  emoji: '⚖️',
  gradient: ['#450A0A', '#7F1D1D', '#1E3A8A', '#3B82F6'] as [string, string, string, string],
  accent: '#FB7185',
  accentDark: '#FECDD3',
  leftColor: '#EF4444',
  rightColor: '#3B82F6',
  balanceGlow: '#FDA4AF',
  playBorder: 'rgba(251,113,133,0.42)',
  playBg: '#1A0A14',
  sparkleColor: '#FB7185',
  backText: '#FEE2E2',
  backBorder: 'rgba(251,113,133,0.38)',
  titleColor: '#FFF1F2',
  subtitleColor: 'rgba(254,205,211,0.9)',
  statLabel: 'rgba(254,205,211,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,113,133,0.32)',
  voiceIntro:
    'Welcome to the balance scale! Drag both weights down to the balance line — keep both hands moving at the same speed!',
  voiceCue: 'Drag both down together at the same pace!',
  voiceComplete: 'Perfect rhythm! You mastered balanced simultaneous dragging!',
  voiceSuccess: 'Perfect balance!',
  congrats: 'Even Pull Champion!',
} as const;

export const EVEN_PULL_CONFIG: Omit<BalanceDualDragGameConfig, 'onBack' | 'onComplete'> = {
  theme: {
    title: EVEN_PULL_THEME.title,
    subtitle: EVEN_PULL_THEME.subtitle,
    emoji: EVEN_PULL_THEME.emoji,
    gradient: EVEN_PULL_THEME.gradient,
    accent: EVEN_PULL_THEME.accent,
    accentDark: EVEN_PULL_THEME.accentDark,
    leftColor: EVEN_PULL_THEME.leftColor,
    rightColor: EVEN_PULL_THEME.rightColor,
    backText: EVEN_PULL_THEME.backText,
    backBorder: EVEN_PULL_THEME.backBorder,
    titleColor: EVEN_PULL_THEME.titleColor,
    subtitleColor: EVEN_PULL_THEME.subtitleColor,
    statLabel: EVEN_PULL_THEME.statLabel,
    statValue: EVEN_PULL_THEME.statValue,
    statBorder: EVEN_PULL_THEME.statBorder,
    playBorder: EVEN_PULL_THEME.playBorder,
    playBg: EVEN_PULL_THEME.playBg,
    sparkleColor: EVEN_PULL_THEME.sparkleColor,
  },
  ttsIntro: EVEN_PULL_THEME.voiceIntro,
  ttsComplete: EVEN_PULL_THEME.voiceComplete,
  ttsCue: EVEN_PULL_THEME.voiceCue,
  ttsSuccess: EVEN_PULL_THEME.voiceSuccess,
  congratsMessage: EVEN_PULL_THEME.congrats,
  logType: 'balance-drag',
  skillTags: ['speed-regulation', 'balanced-pace', 'simultaneous-dragging', 'coordination'],
};
