/**
 * OT Level 4 Session 4 — Two-hand tap theme tokens.
 */

/** Game 1 — Twin Tap · Neural sync arena (simultaneous dual tap) */
export const TWIN_TAP_THEME = {
  title: 'Twin Tap',
  subtitle: 'Tap both glowing orbs at the same time — wake the sync bridge!',
  emoji: '⭕',
  gradient: ['#0F172A', '#1E3A5F', '#0E7490', '#06B6D4'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#67E8F9',
  accentCoral: '#FB7185',
  accentCyan: '#06B6D4',
  arenaDark: '#0F172A',
  syncGlow: '#22D3EE',
  leftColor: '#0EA5E9',
  rightColor: '#F43F5E',
  leftEmoji: '🖐️',
  rightEmoji: '🖐️',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#0F172A',
  sparkleColor: '#22D3EE',
  backText: '#CFFAFE',
  backBorder: 'rgba(34,211,238,0.38)',
  titleColor: '#F0F9FF',
  subtitleColor: 'rgba(186,230,253,0.9)',
  statLabel: 'rgba(186,230,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(34,211,238,0.32)',
  voiceIntro:
    'Welcome to the sync arena! Use both hands and tap the left and right orbs together to light up the bridge!',
  voiceCue: 'Tap both orbs together!',
  voiceComplete: 'Perfect synchronization! Your hands are working as a team!',
  voiceSuccess: 'In sync!',
  voiceMiss: 'Tap both orbs at the same time!',
  congrats: 'Twin Tap Champion!',
} as const;

/** Game 2 — Duo Keys · Concert hall grand piano (timed dual chord) */
export const DUO_KEYS_THEME = {
  title: 'Duo Keys',
  subtitle: 'Strike both ivory keys together before the spotlight fades!',
  emoji: '🎹',
  gradient: ['#1C0A0A', '#3D1515', '#5C2E0A', '#78350F'] as [string, string, string, string],
  accent: '#F59E0B',
  accentDark: '#FDE68A',
  accentGold: '#FBBF24',
  stageDark: '#1C0A0A',
  curtainRed: '#7F1D1D',
  spotlight: '#FEF3C7',
  leftColor: '#FFFBEB',
  rightColor: '#FEF9C3',
  keyPressed: '#FBBF24',
  leftEmoji: '♩',
  rightEmoji: '♪',
  leftNote: 'C',
  rightNote: 'G',
  playBorder: 'rgba(245,158,11,0.45)',
  playBg: '#1C0A0A',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(245,158,11,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,243,199,0.88)',
  statLabel: 'rgba(254,243,199,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(245,158,11,0.32)',
  voiceIntro:
    'Welcome to the concert hall! Press both piano keys at the same time before the spotlight goes out!',
  voiceCue: 'Press both keys together!',
  voiceComplete: 'Bravo! You played every chord in perfect harmony!',
  voiceSuccess: 'Beautiful chord!',
  voiceMiss: 'Too slow — press both keys before time runs out!',
  congrats: 'Duo Keys Virtuoso!',
} as const;

/** Game 3 — Beat Duo · Neon rhythm stage (simultaneous drum hits) */
export const BEAT_DUO_THEME = {
  title: 'Beat Duo',
  subtitle: 'Smash both drum pads on the beat — feel the rhythm pulse!',
  emoji: '🥁',
  gradient: ['#0F0A1A', '#1E1B4B', '#312E81', '#6D28D9'] as [string, string, string, string],
  accent: '#F472B6',
  accentDark: '#FBCFE8',
  accentOrange: '#F97316',
  accentPink: '#EC4899',
  stageDark: '#0F0A1A',
  neonGlow: '#A855F7',
  leftColor: '#F97316',
  rightColor: '#EC4899',
  leftEmoji: '🥁',
  rightEmoji: '🥁',
  playBorder: 'rgba(168,85,247,0.45)',
  playBg: '#0F0A1A',
  sparkleColor: '#F472B6',
  backText: '#F5D0FE',
  backBorder: 'rgba(244,114,182,0.38)',
  titleColor: '#FAF5FF',
  subtitleColor: 'rgba(233,213,255,0.9)',
  statLabel: 'rgba(233,213,255,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(168,85,247,0.32)',
  voiceIntro:
    'Welcome to the rhythm stage! Use both hands and hit the left and right drum pads together on every beat!',
  voiceCue: 'Hit both drums together!',
  voiceComplete: 'Incredible rhythm! You rocked every double beat!',
  voiceSuccess: 'Boom! Double beat!',
  voiceMiss: 'Hit both drums at the same time!',
  congrats: 'Beat Duo Rockstar!',
} as const;

/** Game 4 — Flash Tap · Neon reaction grid (tap when both targets light up) */
export const FLASH_TAP_THEME = {
  title: 'Flash Tap',
  subtitle: 'Watch the grid — strike both neon targets the instant they flash!',
  emoji: '💡',
  gradient: ['#030712', '#0F172A', '#1E293B', '#111827'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#67E8F9',
  accentRed: '#EF4444',
  accentBlue: '#3B82F6',
  gridDark: '#030712',
  neonCyan: '#22D3EE',
  neonRed: '#F87171',
  leftColor: '#3B82F6',
  rightColor: '#EF4444',
  leftEmoji: '⚡',
  rightEmoji: '⚡',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#030712',
  sparkleColor: '#22D3EE',
  backText: '#CFFAFE',
  backBorder: 'rgba(34,211,238,0.38)',
  titleColor: '#F0F9FF',
  subtitleColor: 'rgba(186,230,253,0.88)',
  statLabel: 'rgba(186,230,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(34,211,238,0.32)',
  voiceIntro:
    'Welcome to the flash grid! Wait for both neon targets to light up, then tap them together as fast as you can!',
  voiceCue: 'Tap both targets now!',
  voiceComplete: 'Lightning reflexes! You nailed every flash!',
  voiceSuccess: 'Flash hit!',
  voiceMiss: 'Too slow — wait for the flash and tap both targets!',
  voiceWatch: 'Watch for the lights…',
  voiceTooSlow: 'Too slow! Wait for the next flash!',
  congrats: 'Flash Tap Champion!',
} as const;

/** Game 5 — Hold & Hit · Split-hand control lab (hold + tap independence) */
export const HOLD_HIT_THEME = {
  title: 'Hold & Hit',
  subtitle: 'Anchor one hand steady — strike fast with the other!',
  emoji: '🤲',
  gradient: ['#0C1A1F', '#134E4A', '#1E3A5F', '#0F766E'] as [string, string, string, string],
  accent: '#2DD4BF',
  accentDark: '#5EEAD4',
  accentAmber: '#FBBF24',
  accentTeal: '#14B8A6',
  labDark: '#0C1A1F',
  anchorGlow: '#2DD4BF',
  strikeGlow: '#FBBF24',
  holdBlue: '#0D9488',
  holdRed: '#0F766E',
  tapGold: '#F59E0B',
  tapGreen: '#FBBF24',
  playBorder: 'rgba(45,212,191,0.42)',
  playBg: '#0C1A1F',
  sparkleColor: '#2DD4BF',
  backText: '#CCFBF1',
  backBorder: 'rgba(45,212,191,0.38)',
  titleColor: '#F0FDFA',
  subtitleColor: 'rgba(153,246,228,0.9)',
  statLabel: 'rgba(153,246,228,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(45,212,191,0.32)',
  voiceIntro:
    'Welcome to the split-hand lab! Hold one pad steady with one hand, then tap the strike pad with your other hand!',
  voiceHoldLeft: 'Hold with your left hand, tap with your right!',
  voiceHoldRight: 'Hold with your right hand, tap with your left!',
  voiceKeepHolding: 'Keep holding the anchor pad!',
  voiceNowTap: 'Anchor locked — now tap!',
  voiceComplete: 'Outstanding! Your hands are working independently!',
  voiceSuccess: 'Perfect split control!',
  congrats: 'Hold & Hit Master!',
} as const;
