import type { RhythmPatternGameConfig } from '@/components/game/occupational/level4/session10/shared/RhythmPatternGame';

export const CROSS_CLAP_THEME = {
  title: 'Cross Clap',
  subtitle: 'Listen to the pattern — then copy the cross-body claps!',
  emoji: '👏',
  gradient: ['#0C1929', '#0F2744', '#1E3A5F', '#2563EB'] as [string, string, string, string],
  accent: '#60A5FA',
  accentDark: '#BFDBFE',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  crossGlow: '#93C5FD',
  playBorder: 'rgba(96,165,250,0.42)',
  playBg: '#0C1929',
  sparkleColor: '#60A5FA',
  backText: '#DBEAFE',
  backBorder: 'rgba(96,165,250,0.38)',
  titleColor: '#EFF6FF',
  subtitleColor: 'rgba(191,219,254,0.9)',
  statLabel: 'rgba(191,219,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(96,165,250,0.32)',
  voiceIntro:
    'Welcome to the rhythm studio! Listen to the cross-body clap pattern, then copy it with your hands!',
  voiceListen: 'Listen to the clap pattern!',
  voiceCopy: 'Now copy the pattern!',
  voiceComplete: 'Rhythm master! Your cross-body claps are on beat!',
  voiceSuccess: 'Perfect clap!',
  voiceFail: 'Try again — listen and copy!',
  congrats: 'Cross Clap Champion!',
} as const;

export const CROSS_CLAP_CONFIG: Omit<RhythmPatternGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'clapCross',
  theme: {
    title: CROSS_CLAP_THEME.title,
    subtitle: CROSS_CLAP_THEME.subtitle,
    emoji: CROSS_CLAP_THEME.emoji,
    gradient: CROSS_CLAP_THEME.gradient,
    accent: CROSS_CLAP_THEME.accent,
    accentDark: CROSS_CLAP_THEME.accentDark,
    leftColor: CROSS_CLAP_THEME.leftColor,
    rightColor: CROSS_CLAP_THEME.rightColor,
    backText: CROSS_CLAP_THEME.backText,
    backBorder: CROSS_CLAP_THEME.backBorder,
    titleColor: CROSS_CLAP_THEME.titleColor,
    subtitleColor: CROSS_CLAP_THEME.subtitleColor,
    statLabel: CROSS_CLAP_THEME.statLabel,
    statValue: CROSS_CLAP_THEME.statValue,
    statBorder: CROSS_CLAP_THEME.statBorder,
    playBorder: CROSS_CLAP_THEME.playBorder,
    playBg: CROSS_CLAP_THEME.playBg,
    sparkleColor: CROSS_CLAP_THEME.sparkleColor,
  },
  ttsIntro: CROSS_CLAP_THEME.voiceIntro,
  ttsComplete: CROSS_CLAP_THEME.voiceComplete,
  ttsListen: CROSS_CLAP_THEME.voiceListen,
  ttsCopy: CROSS_CLAP_THEME.voiceCopy,
  ttsSuccess: CROSS_CLAP_THEME.voiceSuccess,
  ttsFail: CROSS_CLAP_THEME.voiceFail,
  congratsMessage: CROSS_CLAP_THEME.congrats,
  logType: 'clap-pattern',
  skillTags: ['rhythm', 'midline', 'cross-body-coordination', 'pattern-copying'],
};
