import type { ReverseHorizontalDragGameConfig } from '@/components/game/occupational/level4/session2/shared/ReverseHorizontalDragGame';

export const RETURN_PASS_THEME = {
  title: 'Return Pass',
  subtitle: 'Send the ball home — slide from right to left into the net',
  emoji: '⚽',
  gradient: ['#431407', '#7C2D12', '#C2410C', '#FB923C'] as [string, string, string, string],
  accent: '#FDE68A',
  accentDark: '#F59E0B',
  accentCoral: '#FB7185',
  pitchDark: '#14532D',
  pitchLight: '#22C55E',
  pitchLine: 'rgba(255,255,255,0.72)',
  goalGold: '#FDE68A',
  sunsetGlow: 'rgba(251,146,60,0.18)',
  draggableEmoji: '⚽',
  targetEmoji: '🥅',
  playBorder: 'rgba(253,224,71,0.48)',
  playBg: '#166534',
  sparkleColor: '#FDE68A',
  zoneBorder: 'rgba(253,224,71,0.55)',
  voiceIntro: 'Sunset kick-off! Drag the ball from the right and score in the home goal on the left!',
  voiceDrag: 'Slide the ball left across the pitch!',
  voiceComplete: 'What a comeback! Every return pass found the net!',
  voiceMiss: 'Keep it on the pitch — aim for the left goal!',
  voiceScore: 'Home goal!',
  congrats: 'Return Pass Legend!',
} as const;

export const RETURN_PASS_CONFIG: Omit<ReverseHorizontalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'ballTransfer',
  theme: {
    title: RETURN_PASS_THEME.title,
    subtitle: RETURN_PASS_THEME.subtitle,
    emoji: RETURN_PASS_THEME.emoji,
    gradient: RETURN_PASS_THEME.gradient,
    accent: RETURN_PASS_THEME.accent,
    accentDark: RETURN_PASS_THEME.accentDark,
    draggableEmoji: RETURN_PASS_THEME.draggableEmoji,
    targetEmoji: RETURN_PASS_THEME.targetEmoji,
    backText: '#FFEDD5',
    backBorder: 'rgba(253,224,71,0.35)',
    titleColor: '#FFF7ED',
    subtitleColor: 'rgba(254,215,170,0.92)',
    statLabel: 'rgba(254,215,170,0.75)',
    statValue: '#FFFFFF',
    statBorder: 'rgba(253,224,71,0.3)',
    playBorder: RETURN_PASS_THEME.playBorder,
    playBg: RETURN_PASS_THEME.playBg,
    sparkleColor: RETURN_PASS_THEME.sparkleColor,
    zoneBorder: RETURN_PASS_THEME.zoneBorder,
  },
  ttsIntro: RETURN_PASS_THEME.voiceIntro,
  ttsComplete: RETURN_PASS_THEME.voiceComplete,
  ttsDrag: RETURN_PASS_THEME.voiceDrag,
  ttsMiss: RETURN_PASS_THEME.voiceMiss,
  ttsGoal: RETURN_PASS_THEME.voiceScore,
  congratsMessage: RETURN_PASS_THEME.congrats,
  logType: 'reverse-ball-pass',
  skillTags: ['bilateral-balance', 'drag-right-left'],
};
