import type { DualTapGameConfig } from '@/components/game/occupational/level4/session4/shared/DualTapGame';

export const FLASH_TAP_THEME = {
  title: 'Flash Tap',
  subtitle: 'Watch the grid — strike both neon targets the instant they flash!',
  emoji: '💡',
  gradient: ['#030712', '#0F172A', '#1E293B', '#111827'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#67E8F9',
  accentRed: '#EF4444',
  accentBlue: '#3B82F6',
  gridDark: '#030712',
  neonCyan: '#22D3EE',
  neonRed: '#F87171',
  leftColor: '#3B82F6',
  rightColor: '#EF4444',
  leftEmoji: '⚡',
  rightEmoji: '⚡',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#030712',
  sparkleColor: '#22D3EE',
  backText: '#CFFAFE',
  backBorder: 'rgba(34,211,238,0.38)',
  titleColor: '#F0F9FF',
  subtitleColor: 'rgba(186,230,253,0.88)',
  statLabel: 'rgba(186,230,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(34,211,238,0.32)',
  voiceIntro:
    'Welcome to the flash grid! Wait for both neon targets to light up, then tap them together as fast as you can!',
  voiceCue: 'Tap both targets now!',
  voiceComplete: 'Lightning reflexes! You nailed every flash!',
  voiceSuccess: 'Flash hit!',
  voiceMiss: 'Too slow — wait for the flash and tap both targets!',
  voiceWatch: 'Watch for the lights…',
  voiceTooSlow: 'Too slow! Wait for the next flash!',
  congrats: 'Flash Tap Champion!',
} as const;

export const FLASH_TAP_CONFIG: Omit<DualTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'lights',
  theme: {
    title: FLASH_TAP_THEME.title,
    subtitle: FLASH_TAP_THEME.subtitle,
    emoji: FLASH_TAP_THEME.emoji,
    gradient: FLASH_TAP_THEME.gradient,
    accent: FLASH_TAP_THEME.accent,
    accentDark: FLASH_TAP_THEME.accentDark,
    leftColor: FLASH_TAP_THEME.leftColor,
    rightColor: FLASH_TAP_THEME.rightColor,
    leftEmoji: FLASH_TAP_THEME.leftEmoji,
    rightEmoji: FLASH_TAP_THEME.rightEmoji,
    targetStyle: 'circle',
    backText: FLASH_TAP_THEME.backText,
    backBorder: FLASH_TAP_THEME.backBorder,
    titleColor: FLASH_TAP_THEME.titleColor,
    subtitleColor: FLASH_TAP_THEME.subtitleColor,
    statLabel: FLASH_TAP_THEME.statLabel,
    statValue: FLASH_TAP_THEME.statValue,
    statBorder: FLASH_TAP_THEME.statBorder,
    playBorder: FLASH_TAP_THEME.playBorder,
    playBg: FLASH_TAP_THEME.playBg,
    sparkleColor: FLASH_TAP_THEME.sparkleColor,
  },
  ttsIntro: FLASH_TAP_THEME.voiceIntro,
  ttsComplete: FLASH_TAP_THEME.voiceComplete,
  ttsCue: FLASH_TAP_THEME.voiceCue,
  ttsSuccess: FLASH_TAP_THEME.voiceSuccess,
  ttsMiss: FLASH_TAP_THEME.voiceMiss,
  ttsTooSlow: FLASH_TAP_THEME.voiceTooSlow,
  ttsWatch: FLASH_TAP_THEME.voiceWatch,
  congratsMessage: FLASH_TAP_THEME.congrats,
  logType: 'light-up-targets',
  skillTags: ['reaction-timing', 'two-hand-tap'],
};
