import type { AlternateTapGameConfig } from '@/components/game/occupational/level4/session5/shared/AlternateTapGame';

export const SWITCH_TAP_THEME = {
  title: 'Switch Tap',
  subtitle: 'Ping-pong your taps — left, then right, then left again!',
  emoji: '👆',
  gradient: ['#0F172A', '#1E1B4B', '#312E81', '#4338CA'] as [string, string, string, string],
  accent: '#818CF8',
  accentDark: '#C7D2FE',
  accentBlue: '#3B82F6',
  accentCoral: '#FB7185',
  trackDark: '#0F172A',
  switchGlow: '#818CF8',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  leftEmoji: '👈',
  rightEmoji: '👉',
  playBorder: 'rgba(129,140,248,0.42)',
  playBg: '#0F172A',
  sparkleColor: '#818CF8',
  backText: '#E0E7FF',
  backBorder: 'rgba(129,140,248,0.38)',
  titleColor: '#EEF2FF',
  subtitleColor: 'rgba(199,210,254,0.9)',
  statLabel: 'rgba(199,210,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(129,140,248,0.32)',
  voiceIntro:
    'Welcome to the relay switch track! Tap left, then right, then left again — keep alternating your hands!',
  voiceCue: 'Start with your left hand, then switch to right!',
  voiceComplete: 'Amazing switching! You mastered the alternating rhythm!',
  voiceSuccess: 'Perfect switch!',
  voiceWrong: 'Use the other hand — keep alternating!',
  congrats: 'Switch Tap Champion!',
} as const;

export const SWITCH_TAP_CONFIG: Omit<AlternateTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'sequence',
  theme: {
    title: SWITCH_TAP_THEME.title,
    subtitle: SWITCH_TAP_THEME.subtitle,
    emoji: SWITCH_TAP_THEME.emoji,
    gradient: SWITCH_TAP_THEME.gradient,
    accent: SWITCH_TAP_THEME.accent,
    accentDark: SWITCH_TAP_THEME.accentDark,
    leftColor: SWITCH_TAP_THEME.leftColor,
    rightColor: SWITCH_TAP_THEME.rightColor,
    leftEmoji: SWITCH_TAP_THEME.leftEmoji,
    rightEmoji: SWITCH_TAP_THEME.rightEmoji,
    targetStyle: 'circle',
    backText: SWITCH_TAP_THEME.backText,
    backBorder: SWITCH_TAP_THEME.backBorder,
    titleColor: SWITCH_TAP_THEME.titleColor,
    subtitleColor: SWITCH_TAP_THEME.subtitleColor,
    statLabel: SWITCH_TAP_THEME.statLabel,
    statValue: SWITCH_TAP_THEME.statValue,
    statBorder: SWITCH_TAP_THEME.statBorder,
    playBorder: SWITCH_TAP_THEME.playBorder,
    playBg: SWITCH_TAP_THEME.playBg,
    sparkleColor: SWITCH_TAP_THEME.sparkleColor,
  },
  ttsIntro: SWITCH_TAP_THEME.voiceIntro,
  ttsComplete: SWITCH_TAP_THEME.voiceComplete,
  ttsCue: SWITCH_TAP_THEME.voiceCue,
  ttsSuccess: SWITCH_TAP_THEME.voiceSuccess,
  ttsWrong: SWITCH_TAP_THEME.voiceWrong,
  congratsMessage: SWITCH_TAP_THEME.congrats,
  logType: 'left-right-tap',
  skillTags: ['sequencing', 'alternating-hands', 'left-right-coordination'],
};
