/**
 * OT Level 4 Session 8 — Alternating side tap theme tokens.
 */

/** Game 1 — Glow Tap · Neon panels (tap the glowing side) */
export const GLOW_TAP_THEME = {
  title: 'Glow Tap',
  subtitle: 'Watch which side glows — tap it fast!',
  emoji: '💡',
  gradient: ['#0C1929', '#0F2744', '#1E3A5F', '#2563EB'] as [string, string, string, string],
  accent: '#60A5FA',
  accentDark: '#BFDBFE',
  glowLeft: '#3B82F6',
  glowRight: '#F43F5E',
  neonPulse: '#93C5FD',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  leftIcon: '💡',
  rightIcon: '💡',
  playBorder: 'rgba(96,165,250,0.42)',
  playBg: '#0C1929',
  sparkleColor: '#60A5FA',
  backText: '#DBEAFE',
  backBorder: 'rgba(96,165,250,0.38)',
  titleColor: '#EFF6FF',
  subtitleColor: 'rgba(191,219,254,0.9)',
  statLabel: 'rgba(191,219,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(96,165,250,0.32)',
  voiceIntro:
    'Welcome to the neon panels! Watch which side lights up and tap it before the glow fades!',
  voiceCue: 'Tap the glowing side!',
  voiceComplete: 'Brilliant bilateral tapping! Both sides are activated!',
  voiceSuccess: 'Perfect glow tap!',
  voiceMiss: 'Too slow — tap the glowing side!',
  voiceWrong: 'Wrong side — tap the glowing panel!',
  congrats: 'Glow Tap Champion!',
} as const;

/** Game 2 — Rally Tap · Arena court (tap when ball hits center) */
export const RALLY_TAP_THEME = {
  title: 'Rally Tap',
  subtitle: 'Watch the ball cross — tap when it hits center!',
  emoji: '🏓',
  gradient: ['#052E16', '#14532D', '#166534', '#22C55E'] as [string, string, string, string],
  accent: '#4ADE80',
  accentDark: '#BBF7D0',
  courtLine: '#86EFAC',
  netGlow: '#6EE7B7',
  leftColor: '#22C55E',
  rightColor: '#3B82F6',
  ballEmoji: '🏓',
  playBorder: 'rgba(74,222,128,0.42)',
  playBg: '#052E16',
  sparkleColor: '#4ADE80',
  backText: '#DCFCE7',
  backBorder: 'rgba(74,222,128,0.38)',
  titleColor: '#F0FDF4',
  subtitleColor: 'rgba(187,247,208,0.9)',
  statLabel: 'rgba(187,247,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(74,222,128,0.32)',
  voiceIntro:
    'Welcome to the rally arena! Watch the ball zip across the court and tap when it reaches the center circle!',
  voiceCue: 'Tap when the ball reaches the center!',
  voiceComplete: 'Champion rally! Your timing and focus are on point!',
  voiceSuccess: 'Great rally tap!',
  voiceMiss: 'Wait until the center glows green!',
  voiceEarly: 'Too early! Wait for the ball at center!',
  voiceRetry: 'Missed! Try again!',
  congrats: 'Rally Tap Champion!',
} as const;

/** Game 3 — Sound Tap · Studio booth (hear sound, tap that side) */
export const SOUND_TAP_THEME = {
  title: 'Sound Tap',
  subtitle: 'Listen closely — tap the side where you hear the sound!',
  emoji: '🔊',
  gradient: ['#2E1065', '#4C1D95', '#6D28D9', '#8B5CF6'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  waveGlow: '#C4B5FD',
  speakerLeft: '#8B5CF6',
  speakerRight: '#F472B6',
  leftColor: '#8B5CF6',
  rightColor: '#F472B6',
  leftIcon: '🔊',
  rightIcon: '🔊',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#2E1065',
  sparkleColor: '#A78BFA',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(221,214,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the sound studio! Listen for the bell, drum, or clap — then tap the side where you heard it!',
  voiceCue: 'Tap the side where you hear the sound!',
  voiceComplete: 'Amazing ears! You nailed every sound localization!',
  voiceSuccess: 'Perfect sound tap!',
  voiceMiss: 'Too slow — listen and tap faster!',
  voiceWrong: 'Wrong side — listen again!',
  congrats: 'Sound Tap Champion!',
} as const;

/** Game 4 — Odd Even Tap · Split brain (odd = left, even = right) */
export const ODD_EVEN_TAP_THEME = {
  title: 'Odd Even Tap',
  subtitle: 'Odd numbers → left! Even numbers → right!',
  emoji: '🔢',
  gradient: ['#450A0A', '#7F1D1D', '#1E3A8A', '#3B82F6'] as [string, string, string, string],
  accent: '#FB7185',
  accentDark: '#FECDD3',
  oddGlow: '#EF4444',
  evenGlow: '#60A5FA',
  leftColor: '#EF4444',
  rightColor: '#3B82F6',
  leftIcon: '1️⃣',
  rightIcon: '2️⃣',
  playBorder: 'rgba(251,113,133,0.42)',
  playBg: '#1A0A14',
  sparkleColor: '#FB7185',
  backText: '#FEE2E2',
  backBorder: 'rgba(251,113,133,0.38)',
  titleColor: '#FFF1F2',
  subtitleColor: 'rgba(254,205,211,0.9)',
  statLabel: 'rgba(254,205,211,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,113,133,0.32)',
  voiceIntro:
    'Welcome to the split brain challenge! Odd numbers mean tap left, even numbers mean tap right!',
  voiceCue: 'Odd left, even right — read the number fast!',
  voiceComplete: 'Brain and body linked! You mastered odd and even sides!',
  voiceSuccess: 'Perfect match!',
  voiceMiss: 'Too slow — read the number and tap!',
  voiceWrong: 'Check odd or even — tap the right side!',
  congrats: 'Odd Even Tap Champion!',
} as const;

/** Game 5 — Quick Switch · Lightning arena (sides flash faster each round) */
export const QUICK_SWITCH_THEME = {
  title: 'Quick Switch',
  subtitle: 'Tap the active side — it gets faster every round!',
  emoji: '⚡',
  gradient: ['#1C1917', '#422006', '#78350F', '#FBBF24'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  boltLeft: '#F59E0B',
  boltRight: '#EF4444',
  leftColor: '#F59E0B',
  rightColor: '#EF4444',
  leftIcon: '⚡',
  rightIcon: '⚡',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#1C1917',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(253,230,138,0.9)',
  statLabel: 'rgba(253,230,138,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the lightning arena! Tap whichever side flashes — but hurry, it gets faster each round!',
  voiceCue: 'Switch sides fast — speed increases!',
  voiceComplete: 'Lightning reflexes! You mastered rapid side switching!',
  voiceSuccess: 'Quick switch!',
  voiceMiss: 'Too slow — tap before the flash fades!',
  voiceWrong: 'Wrong side — tap the flashing panel!',
  congrats: 'Quick Switch Champion!',
} as const;
