import type { AlternateTapGameConfig } from '@/components/game/occupational/level4/session5/shared/AlternateTapGame';

export const RHYTHM_SWITCH_THEME = {
  title: 'Rhythm Switch',
  subtitle: 'Follow the metronome — alternate left and right drum hits!',
  emoji: '🥁',
  gradient: ['#1C1410', '#422006', '#78350F', '#B45309'] as [string, string, string, string],
  accent: '#F59E0B',
  accentDark: '#FDE68A',
  accentBronze: '#D97706',
  accentCopper: '#EA580C',
  stageDark: '#1C1410',
  metronomeGlow: '#FBBF24',
  leftColor: '#F97316',
  rightColor: '#DC2626',
  leftEmoji: '🥁',
  rightEmoji: '🥁',
  playBorder: 'rgba(245,158,11,0.45)',
  playBg: '#1C1410',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(245,158,11,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,243,199,0.88)',
  statLabel: 'rgba(254,243,199,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(245,158,11,0.32)',
  voiceIntro:
    'Welcome to the jazz drum stage! Follow the beat and alternate — tap the left drum, then the right, keeping the rhythm!',
  voiceCue: 'Follow the beat and alternate your drums!',
  voiceComplete: 'Swinging rhythm! You nailed every alternating beat!',
  voiceSuccess: 'On beat!',
  voiceWrong: 'Wrong drum — follow the alternating beat!',
  congrats: 'Rhythm Switch Virtuoso!',
} as const;

export const RHYTHM_SWITCH_CONFIG: Omit<AlternateTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'beat',
  theme: {
    title: RHYTHM_SWITCH_THEME.title,
    subtitle: RHYTHM_SWITCH_THEME.subtitle,
    emoji: RHYTHM_SWITCH_THEME.emoji,
    gradient: RHYTHM_SWITCH_THEME.gradient,
    accent: RHYTHM_SWITCH_THEME.accent,
    accentDark: RHYTHM_SWITCH_THEME.accentDark,
    leftColor: RHYTHM_SWITCH_THEME.leftColor,
    rightColor: RHYTHM_SWITCH_THEME.rightColor,
    leftEmoji: RHYTHM_SWITCH_THEME.leftEmoji,
    rightEmoji: RHYTHM_SWITCH_THEME.rightEmoji,
    targetStyle: 'drum',
    backText: RHYTHM_SWITCH_THEME.backText,
    backBorder: RHYTHM_SWITCH_THEME.backBorder,
    titleColor: RHYTHM_SWITCH_THEME.titleColor,
    subtitleColor: RHYTHM_SWITCH_THEME.subtitleColor,
    statLabel: RHYTHM_SWITCH_THEME.statLabel,
    statValue: RHYTHM_SWITCH_THEME.statValue,
    statBorder: RHYTHM_SWITCH_THEME.statBorder,
    playBorder: RHYTHM_SWITCH_THEME.playBorder,
    playBg: RHYTHM_SWITCH_THEME.playBg,
    sparkleColor: RHYTHM_SWITCH_THEME.sparkleColor,
  },
  ttsIntro: RHYTHM_SWITCH_THEME.voiceIntro,
  ttsComplete: RHYTHM_SWITCH_THEME.voiceComplete,
  ttsCue: RHYTHM_SWITCH_THEME.voiceCue,
  ttsSuccess: RHYTHM_SWITCH_THEME.voiceSuccess,
  ttsWrong: RHYTHM_SWITCH_THEME.voiceWrong,
  congratsMessage: RHYTHM_SWITCH_THEME.congrats,
  logType: 'drum-alternate',
  skillTags: ['rhythm-control', 'alternating-hands', 'coordination'],
};
