import type { DualTapGameConfig } from '@/components/game/occupational/level4/session4/shared/DualTapGame';

export const BEAT_DUO_THEME = {
  title: 'Beat Duo',
  subtitle: 'Smash both drum pads on the beat — feel the rhythm pulse!',
  emoji: '🥁',
  gradient: ['#0F0A1A', '#1E1B4B', '#312E81', '#6D28D9'] as [string, string, string, string],
  accent: '#F472B6',
  accentDark: '#FBCFE8',
  accentOrange: '#F97316',
  accentPink: '#EC4899',
  stageDark: '#0F0A1A',
  neonGlow: '#A855F7',
  leftColor: '#F97316',
  rightColor: '#EC4899',
  leftEmoji: '🥁',
  rightEmoji: '🥁',
  playBorder: 'rgba(168,85,247,0.45)',
  playBg: '#0F0A1A',
  sparkleColor: '#F472B6',
  backText: '#F5D0FE',
  backBorder: 'rgba(244,114,182,0.38)',
  titleColor: '#FAF5FF',
  subtitleColor: 'rgba(233,213,255,0.9)',
  statLabel: 'rgba(233,213,255,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(168,85,247,0.32)',
  voiceIntro:
    'Welcome to the rhythm stage! Use both hands and hit the left and right drum pads together on every beat!',
  voiceCue: 'Hit both drums together!',
  voiceComplete: 'Incredible rhythm! You rocked every double beat!',
  voiceSuccess: 'Boom! Double beat!',
  voiceMiss: 'Hit both drums at the same time!',
  congrats: 'Beat Duo Rockstar!',
} as const;

export const BEAT_DUO_CONFIG: Omit<DualTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'drums',
  theme: {
    title: BEAT_DUO_THEME.title,
    subtitle: BEAT_DUO_THEME.subtitle,
    emoji: BEAT_DUO_THEME.emoji,
    gradient: BEAT_DUO_THEME.gradient,
    accent: BEAT_DUO_THEME.accent,
    accentDark: BEAT_DUO_THEME.accentDark,
    leftColor: BEAT_DUO_THEME.leftColor,
    rightColor: BEAT_DUO_THEME.rightColor,
    leftEmoji: BEAT_DUO_THEME.leftEmoji,
    rightEmoji: BEAT_DUO_THEME.rightEmoji,
    targetStyle: 'drum',
    backText: BEAT_DUO_THEME.backText,
    backBorder: BEAT_DUO_THEME.backBorder,
    titleColor: BEAT_DUO_THEME.titleColor,
    subtitleColor: BEAT_DUO_THEME.subtitleColor,
    statLabel: BEAT_DUO_THEME.statLabel,
    statValue: BEAT_DUO_THEME.statValue,
    statBorder: BEAT_DUO_THEME.statBorder,
    playBorder: BEAT_DUO_THEME.playBorder,
    playBg: BEAT_DUO_THEME.playBg,
    sparkleColor: BEAT_DUO_THEME.sparkleColor,
  },
  ttsIntro: BEAT_DUO_THEME.voiceIntro,
  ttsComplete: BEAT_DUO_THEME.voiceComplete,
  ttsCue: BEAT_DUO_THEME.voiceCue,
  ttsSuccess: BEAT_DUO_THEME.voiceSuccess,
  ttsMiss: BEAT_DUO_THEME.voiceMiss,
  congratsMessage: BEAT_DUO_THEME.congrats,
  logType: 'drum-duo',
  skillTags: ['rhythm', 'coordination', 'two-hand-tap'],
};
