import type { HorizontalDragGameConfig } from '@/components/game/occupational/level4/session1/shared/HorizontalDragGame';

export const GOAL_PASS_THEME = {
  title: 'Goal Pass',
  subtitle: 'Slide the ball across the pitch into the net',
  emoji: '⚽',
  gradient: ['#0C1A3A', '#1E3A5F', '#1D4ED8', '#3B82F6'] as [string, string, string, string],
  accent: '#FCD34D',
  accentDark: '#F59E0B',
  accentBlue: '#3B82F6',
  pitchDark: '#166534',
  pitchLight: '#22C55E',
  pitchLine: 'rgba(255,255,255,0.72)',
  goalGold: '#FCD34D',
  goalNet: 'rgba(255,255,255,0.18)',
  draggableEmoji: '⚽',
  targetEmoji: '🥅',
  playBorder: 'rgba(252,211,77,0.45)',
  playBg: '#15803D',
  sparkleColor: '#FCD34D',
  zoneBorder: 'rgba(252,211,77,0.55)',
  floodlight: 'rgba(254,243,199,0.12)',
  shadow: 'rgba(0,0,0,0.35)',
  hintBg: 'rgba(15,23,42,0.72)',
  hintText: '#F8FAFC',
  progressFill: '#FCD34D',
  progressTrack: 'rgba(255,255,255,0.2)',
  voiceIntro: 'Welcome to the stadium! Drag the ball from the kick-off spot into the goal net!',
  voiceDrag: 'Slide the ball across the pitch to score!',
  voiceComplete: 'What a striker! You scored every pass!',
  voiceMiss: 'Keep the ball on the pitch — aim for the goal!',
  voiceGoal: 'Goal!',
  congrats: 'Stadium Striker!',
} as const;

export const GOAL_PASS_CONFIG: Omit<HorizontalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'ballTransfer',
  theme: {
    title: GOAL_PASS_THEME.title,
    subtitle: GOAL_PASS_THEME.subtitle,
    emoji: GOAL_PASS_THEME.emoji,
    gradient: GOAL_PASS_THEME.gradient,
    accent: GOAL_PASS_THEME.accent,
    accentDark: GOAL_PASS_THEME.accentDark,
    draggableEmoji: GOAL_PASS_THEME.draggableEmoji,
    targetEmoji: GOAL_PASS_THEME.targetEmoji,
    backText: '#E2E8F0',
    backBorder: 'rgba(255,255,255,0.22)',
    titleColor: '#F8FAFC',
    subtitleColor: 'rgba(226,232,240,0.88)',
    statLabel: 'rgba(226,232,240,0.75)',
    statValue: '#FFFFFF',
    statBorder: 'rgba(255,255,255,0.22)',
    playBorder: GOAL_PASS_THEME.playBorder,
    playBg: GOAL_PASS_THEME.playBg,
    sparkleColor: GOAL_PASS_THEME.sparkleColor,
    zoneBorder: GOAL_PASS_THEME.zoneBorder,
  },
  ttsIntro: GOAL_PASS_THEME.voiceIntro,
  ttsComplete: GOAL_PASS_THEME.voiceComplete,
  ttsDrag: GOAL_PASS_THEME.voiceDrag,
  ttsMiss: GOAL_PASS_THEME.voiceMiss,
  ttsGoal: GOAL_PASS_THEME.voiceGoal,
  congratsMessage: GOAL_PASS_THEME.congrats,
  logType: 'ball-transfer',
  skillTags: ['midline-crossing', 'brain-hemispheres', 'drag-left-right'],
};
