/**
 * OT Level 4 Session 3 — Diagonal drag theme tokens.
 */

/** Game 1 — Diagonal Dash · Summit-to-valley diagonal slide */
export const DIAGONAL_DASH_THEME = {
  title: 'Diagonal Dash',
  subtitle: 'Launch from the summit and slide diagonally down to the valley finish',
  emoji: '↘️',
  gradient: ['#0C1A3A', '#1E3A5F', '#B45309', '#FBBF24'] as [string, string, string, string],
  accent: '#38BDF8',
  accentDark: '#7DD3FC',
  accentGold: '#FBBF24',
  accentAmber: '#F59E0B',
  summitDark: '#0F172A',
  valleyWarm: '#78350F',
  trailGlow: '#38BDF8',
  draggableEmoji: '☄️',
  targetEmoji: '🏁',
  playBorder: 'rgba(56,189,248,0.42)',
  playBg: '#0F172A',
  sparkleColor: '#FBBF24',
  zoneBorder: 'rgba(251,191,36,0.45)',
  voiceIntro:
    'Welcome to the mountain dash! Drag from the summit at the top-left all the way down to the valley finish at the bottom-right!',
  voiceDrag: 'Slide diagonally down to the finish!',
  voiceComplete: 'What a run! You dashed down the mountain on every try!',
  voiceMiss: 'Aim for the valley finish in the bottom-right corner!',
  voiceLanded: 'Landed!',
  congrats: 'Diagonal Dash Legend!',
} as const;

/** Game 2 — X Trace · Ancient sigil chamber (dual diagonal trace) */
export const X_TRACE_THEME = {
  title: 'X Trace',
  subtitle: 'Trace both legs of the glowing sigil — complete the ancient X',
  emoji: '✨',
  gradient: ['#1E0A3C', '#4C1D95', '#6B21A8', '#C026D3'] as [string, string, string, string],
  accent: '#E879F9',
  accentDark: '#F0ABFC',
  accentGold: '#FDE68A',
  accentViolet: '#A78BFA',
  chamberDark: '#1A0A2E',
  sigilGlow: '#E879F9',
  runeGold: '#FBBF24',
  draggableEmoji: '🖊️',
  playBorder: 'rgba(232,121,249,0.42)',
  playBg: '#1A0A2E',
  sparkleColor: '#E879F9',
  pathColor: '#E879F9',
  backText: '#FAE8FF',
  backBorder: 'rgba(232,121,249,0.38)',
  titleColor: '#FAF5FF',
  subtitleColor: 'rgba(233,213,255,0.9)',
  statLabel: 'rgba(233,213,255,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(232,121,249,0.32)',
  voiceIntro:
    'Enter the sigil chamber! Trace the first diagonal from top-left to bottom-right, then the second from top-right to bottom-left to complete the X!',
  voiceDrag: 'Trace the glowing X — both legs!',
  voiceComplete: 'The ancient sigil is complete! Your hand and eyes are perfectly in sync!',
  voiceMiss: 'Stay on the sigil path — finish both legs of the X!',
  voiceTraced: 'Sigil complete!',
  voiceLeg1: 'First leg done!',
  congrats: 'X Trace Master!',
} as const;

/** Game 3 — Sky Catch · Aurora cloud arena (diagonal intercept) */
export const SKY_CATCH_STARS = ['⭐', '🌟', '💫', '☄️'] as const;

export const SKY_CATCH_THEME = {
  title: 'Sky Catch',
  subtitle: 'Slide your cloud net to snag stars falling diagonally across the sky',
  emoji: '☁️',
  gradient: ['#0C1445', '#1E3A8A', '#7C3AED', '#FB7185'] as [string, string, string, string],
  accent: '#38BDF8',
  accentDark: '#7DD3FC',
  accentPink: '#FB7185',
  accentViolet: '#A78BFA',
  skyDeep: '#0C1445',
  cloudWhite: '#E0F2FE',
  auroraGreen: '#34D399',
  catcherEmoji: '🥅',
  fallEmojis: SKY_CATCH_STARS,
  playBorder: 'rgba(56,189,248,0.42)',
  playBg: '#0C1445',
  sparkleColor: '#FBBF24',
  backText: '#E0F2FE',
  backBorder: 'rgba(56,189,248,0.38)',
  titleColor: '#F0F9FF',
  subtitleColor: 'rgba(186,230,253,0.9)',
  statLabel: 'rgba(186,230,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(56,189,248,0.32)',
  voiceIntro:
    'Welcome to the aurora sky! Stars fall diagonally — slide your cloud net along the bottom to catch them before they pass!',
  voiceDrag: 'Slide the net under the falling star!',
  voiceComplete: 'Sky legend! You caught every star that crossed the sky!',
  voiceMiss: 'Move faster — slide the net under the falling star!',
  voiceCaught: 'Snagged!',
  congrats: 'Sky Catch Champion!',
} as const;

/** Game 4 — Zigzag Run · Lightning canyon (diagonal zigzag trace) */
export const ZIGZAG_RUN_THEME = {
  title: 'Zigzag Run',
  subtitle: 'Ride the lightning bolt along the zigzag canyon trail to the thunder gate',
  emoji: '⚡',
  gradient: ['#0A0A0A', '#1C1917', '#365314', '#84CC16'] as [string, string, string, string],
  accent: '#A3E635',
  accentDark: '#BEF264',
  accentGold: '#FACC15',
  accentElectric: '#EAB308',
  canyonDark: '#0C0A09',
  rockMid: '#292524',
  boltGlow: '#FACC15',
  draggableEmoji: '⚡',
  targetEmoji: '🌩️',
  playBorder: 'rgba(163,230,53,0.42)',
  playBg: '#0C0A09',
  sparkleColor: '#FACC15',
  pathColor: '#A3E635',
  backText: '#ECFCCB',
  backBorder: 'rgba(163,230,53,0.38)',
  titleColor: '#F7FEE7',
  subtitleColor: 'rgba(217,249,157,0.9)',
  statLabel: 'rgba(217,249,157,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(163,230,53,0.32)',
  voiceIntro:
    'Enter the lightning canyon! Trace the zigzag bolt path from the spark at the top-left all the way to the thunder gate at the bottom-right!',
  voiceDrag: 'Follow the zigzag lightning trail!',
  voiceComplete: 'Thunder master! You rode every zigzag bolt to the gate!',
  voiceMiss: 'Stay on the lightning path — reach the thunder gate!',
  voiceZapped: 'Zapped!',
  congrats: 'Zigzag Run Legend!',
} as const;

/** Game 5 — Corner Match · Prism vault (diagonal color match) */
export const CORNER_MATCH_THEME = {
  title: 'Corner Match',
  subtitle: 'Carry the glowing gem from its pedestal to the matching corner across the vault',
  emoji: '💎',
  gradient: ['#1A0A14', '#881337', '#BE123C', '#F59E0B'] as [string, string, string, string],
  accent: '#FB7185',
  accentDark: '#FDA4AF',
  accentGold: '#FBBF24',
  accentRose: '#F43F5E',
  vaultDark: '#1A0A14',
  velvet: '#4C0519',
  prismGlow: '#FBBF24',
  playBorder: 'rgba(251,113,133,0.42)',
  playBg: '#1A0A14',
  sparkleColor: '#FBBF24',
  zoneBorder: 'rgba(251,191,36,0.45)',
  backText: '#FFE4E6',
  backBorder: 'rgba(251,113,133,0.38)',
  titleColor: '#FFF1F2',
  subtitleColor: 'rgba(254,205,211,0.9)',
  statLabel: 'rgba(254,205,211,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,113,133,0.32)',
  voiceIntro:
    'Welcome to the prism vault! Pick up the glowing gem and drag it diagonally to the matching pedestal in the opposite corner!',
  voiceDrag: 'Match the gem at the opposite corner!',
  voiceComplete: 'Jewel master! Every gem found its matching corner!',
  voiceMiss: 'Drag the gem to the matching pedestal in the opposite corner!',
  voiceMatched: 'Matched!',
  congrats: 'Corner Match Hero!',
} as const;
