import type { RhythmPatternGameConfig } from '@/components/game/occupational/level4/session10/shared/RhythmPatternGame';

export const FAST_BEAT_THEME = {
  title: 'Fast Beat',
  subtitle: 'Copy the rhythm — it speeds up every round!',
  emoji: '⚡',
  gradient: ['#1C1917', '#450A0A', '#7F1D1D', '#EF4444'] as [string, string, string, string],
  accent: '#EF4444',
  accentDark: '#FCA5A5',
  leftColor: '#EF4444',
  rightColor: '#3B82F6',
  speedGlow: '#FBBF24',
  playBorder: 'rgba(239,68,68,0.42)',
  playBg: '#1C1917',
  sparkleColor: '#EF4444',
  backText: '#FECACA',
  backBorder: 'rgba(239,68,68,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,202,202,0.9)',
  statLabel: 'rgba(254,202,202,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(239,68,68,0.32)',
  voiceIntro:
    'Welcome to the lightning arena! Copy each rhythm pattern — the beat gets faster every round!',
  voiceListen: 'Listen to the rhythm!',
  voiceCopy: 'Now copy it — stay in control!',
  voiceComplete: 'Lightning fast! You mastered every accelerating beat!',
  voiceSuccess: 'Perfect timing!',
  voiceFail: 'Try again — keep the rhythm!',
  congrats: 'Fast Beat Champion!',
} as const;

export const FAST_BEAT_CONFIG: Omit<RhythmPatternGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'speed',
  theme: {
    title: FAST_BEAT_THEME.title,
    subtitle: FAST_BEAT_THEME.subtitle,
    emoji: FAST_BEAT_THEME.emoji,
    gradient: FAST_BEAT_THEME.gradient,
    accent: FAST_BEAT_THEME.accent,
    accentDark: FAST_BEAT_THEME.accentDark,
    leftColor: FAST_BEAT_THEME.leftColor,
    rightColor: FAST_BEAT_THEME.rightColor,
    backText: FAST_BEAT_THEME.backText,
    backBorder: FAST_BEAT_THEME.backBorder,
    titleColor: FAST_BEAT_THEME.titleColor,
    subtitleColor: FAST_BEAT_THEME.subtitleColor,
    statLabel: FAST_BEAT_THEME.statLabel,
    statValue: FAST_BEAT_THEME.statValue,
    statBorder: FAST_BEAT_THEME.statBorder,
    playBorder: FAST_BEAT_THEME.playBorder,
    playBg: FAST_BEAT_THEME.playBg,
    sparkleColor: FAST_BEAT_THEME.sparkleColor,
  },
  ttsIntro: FAST_BEAT_THEME.voiceIntro,
  ttsComplete: FAST_BEAT_THEME.voiceComplete,
  ttsListen: FAST_BEAT_THEME.voiceListen,
  ttsCopy: FAST_BEAT_THEME.voiceCopy,
  ttsSuccess: FAST_BEAT_THEME.voiceSuccess,
  ttsFail: FAST_BEAT_THEME.voiceFail,
  congratsMessage: FAST_BEAT_THEME.congrats,
  logType: 'speed-rhythm',
  skillTags: ['control', 'flexibility', 'speed-regulation', 'rhythm', 'cross-body-coordination'],
};
