import type { MidlineDragPassGameConfig } from '@/components/game/occupational/level4/session6/shared/MidlineDragPassGame';

export const DETOUR_PASS_THEME = {
  title: 'Detour Pass',
  subtitle: 'Go up and around the barrier — reach the goal on the right!',
  emoji: '🚧',
  gradient: ['#064E3B', '#065F46', '#047857', '#10B981'] as [string, string, string, string],
  accent: '#10B981',
  accentDark: '#A7F3D0',
  accentAmber: '#FBBF24',
  accentOrange: '#F97316',
  siteDark: '#064E3B',
  barrierGlow: '#FBBF24',
  ballEmoji: '⚽',
  targetEmoji: '🎯',
  obstacleEmoji: '🚧',
  playBorder: 'rgba(16,185,129,0.42)',
  playBg: '#064E3B',
  sparkleColor: '#34D399',
  midlineColor: 'rgba(251,191,36,0.55)',
  backText: '#D1FAE5',
  backBorder: 'rgba(16,185,129,0.38)',
  titleColor: '#ECFDF5',
  subtitleColor: 'rgba(167,243,208,0.9)',
  statLabel: 'rgba(167,243,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(16,185,129,0.32)',
  voiceIntro:
    'Welcome to the construction detour! Drag the ball up, go around the barrier on the right, and reach the goal!',
  voiceDrag: 'Go up, then right around the barrier to the goal!',
  voiceComplete: 'Master planner! You detoured around every barrier!',
  voiceSuccess: 'Detour complete!',
  voiceMiss: 'Go around the barrier to reach the goal!',
  voiceObstacle: 'You hit the barrier! Go up and around it!',
  voiceDetourCross: 'Go around via the right side first!',
  congrats: 'Detour Pass Star!',
} as const;

export const DETOUR_PASS_CONFIG: Omit<MidlineDragPassGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'obstaclePass',
  theme: {
    title: DETOUR_PASS_THEME.title,
    subtitle: DETOUR_PASS_THEME.subtitle,
    emoji: DETOUR_PASS_THEME.emoji,
    gradient: DETOUR_PASS_THEME.gradient,
    accent: DETOUR_PASS_THEME.accent,
    accentDark: DETOUR_PASS_THEME.accentDark,
    ballEmoji: DETOUR_PASS_THEME.ballEmoji,
    targetEmoji: DETOUR_PASS_THEME.targetEmoji,
    obstacleEmoji: DETOUR_PASS_THEME.obstacleEmoji,
    backText: DETOUR_PASS_THEME.backText,
    backBorder: DETOUR_PASS_THEME.backBorder,
    titleColor: DETOUR_PASS_THEME.titleColor,
    subtitleColor: DETOUR_PASS_THEME.subtitleColor,
    statLabel: DETOUR_PASS_THEME.statLabel,
    statValue: DETOUR_PASS_THEME.statValue,
    statBorder: DETOUR_PASS_THEME.statBorder,
    playBorder: DETOUR_PASS_THEME.playBorder,
    playBg: DETOUR_PASS_THEME.playBg,
    sparkleColor: DETOUR_PASS_THEME.sparkleColor,
    midlineColor: DETOUR_PASS_THEME.midlineColor,
  },
  ttsIntro: DETOUR_PASS_THEME.voiceIntro,
  ttsComplete: DETOUR_PASS_THEME.voiceComplete,
  ttsDrag: DETOUR_PASS_THEME.voiceDrag,
  ttsMiss: DETOUR_PASS_THEME.voiceMiss,
  ttsObstacle: DETOUR_PASS_THEME.voiceObstacle,
  ttsDetourCross: DETOUR_PASS_THEME.voiceDetourCross,
  ttsSuccess: DETOUR_PASS_THEME.voiceSuccess,
  congratsMessage: DETOUR_PASS_THEME.congrats,
  logType: 'obstacle-pass',
  skillTags: ['planning-skill', 'obstacle-avoidance', 'midline-crossing'],
};
