import type { AlternateTapGameConfig } from '@/components/game/occupational/level4/session5/shared/AlternateTapGame';

export const SPEED_SWITCH_THEME = {
  title: 'Speed Switch',
  subtitle: 'Start slow on the turbo lane — alternate faster each step!',
  emoji: '⚡',
  gradient: ['#1E1B4B', '#312E81', '#5B21B6', '#7C3AED'] as [string, string, string, string],
  accent: '#8B5CF6',
  accentDark: '#C4B5FD',
  accentCyan: '#22D3EE',
  accentMagenta: '#E879F9',
  laneDark: '#1E1B4B',
  turboGlow: '#A78BFA',
  leftColor: '#3B82F6',
  rightColor: '#A855F7',
  leftEmoji: '👈',
  rightEmoji: '👉',
  playBorder: 'rgba(139,92,246,0.45)',
  playBg: '#1E1B4B',
  sparkleColor: '#A78BFA',
  backText: '#EDE9FE',
  backBorder: 'rgba(139,92,246,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(196,181,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(139,92,246,0.32)',
  voiceIntro:
    'Welcome to the turbo lane! Alternate left and right — each step gets faster. Keep up with the speed!',
  voiceCue: 'Start slow — then blast through the lane!',
  voiceComplete: 'Incredible velocity! You mastered every speed level!',
  voiceSuccess: 'Zoom!',
  voiceWrong: 'Wrong side — keep alternating as you speed up!',
  voiceTooSlow: 'Too slow — pick up the pace!',
  congrats: 'Speed Switch Pro!',
} as const;

export const SPEED_SWITCH_CONFIG: Omit<AlternateTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'speed',
  theme: {
    title: SPEED_SWITCH_THEME.title,
    subtitle: SPEED_SWITCH_THEME.subtitle,
    emoji: SPEED_SWITCH_THEME.emoji,
    gradient: SPEED_SWITCH_THEME.gradient,
    accent: SPEED_SWITCH_THEME.accent,
    accentDark: SPEED_SWITCH_THEME.accentDark,
    leftColor: SPEED_SWITCH_THEME.leftColor,
    rightColor: SPEED_SWITCH_THEME.rightColor,
    leftEmoji: SPEED_SWITCH_THEME.leftEmoji,
    rightEmoji: SPEED_SWITCH_THEME.rightEmoji,
    targetStyle: 'circle',
    backText: SPEED_SWITCH_THEME.backText,
    backBorder: SPEED_SWITCH_THEME.backBorder,
    titleColor: SPEED_SWITCH_THEME.titleColor,
    subtitleColor: SPEED_SWITCH_THEME.subtitleColor,
    statLabel: SPEED_SWITCH_THEME.statLabel,
    statValue: SPEED_SWITCH_THEME.statValue,
    statBorder: SPEED_SWITCH_THEME.statBorder,
    playBorder: SPEED_SWITCH_THEME.playBorder,
    playBg: SPEED_SWITCH_THEME.playBg,
    sparkleColor: SPEED_SWITCH_THEME.sparkleColor,
  },
  ttsIntro: SPEED_SWITCH_THEME.voiceIntro,
  ttsComplete: SPEED_SWITCH_THEME.voiceComplete,
  ttsCue: SPEED_SWITCH_THEME.voiceCue,
  ttsSuccess: SPEED_SWITCH_THEME.voiceSuccess,
  ttsWrong: SPEED_SWITCH_THEME.voiceWrong,
  ttsTooSlow: SPEED_SWITCH_THEME.voiceTooSlow,
  congratsMessage: SPEED_SWITCH_THEME.congrats,
  logType: 'speed-alternate',
  skillTags: ['motor-speed-control', 'alternating-hands', 'speed-progression'],
};
