import type { MidlinePassGameConfig } from '@/components/game/occupational/level4/session6/shared/MidlinePassGame';

export const BEAT_PASS_THEME = {
  title: 'Beat Pass',
  subtitle: 'Wait for the beat flash — tap the hand holding the ball!',
  emoji: '🎵',
  gradient: ['#1E1B4B', '#312E81', '#5B21B6', '#7C3AED'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  accentViolet: '#8B5CF6',
  accentPink: '#E879F9',
  stageDark: '#1E1B4B',
  beatGlow: '#C4B5FD',
  leftColor: '#8B5CF6',
  rightColor: '#E879F9',
  ballEmoji: '🏀',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#1E1B4B',
  sparkleColor: '#C4B5FD',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(196,181,253,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the beat stage! When the neon beat flashes, tap the hand that holds the ball — four beats to finish each round!',
  voiceCue: 'Wait for the beat flash, then tap the hand with the ball!',
  voiceComplete: 'Grooving rhythm! You passed on every beat across midline!',
  voiceSuccess: 'On beat!',
  voiceWrong: 'Wait for the beat flash first!',
  voiceMissBeat: 'Missed the beat — wait for the next flash!',
  congrats: 'Beat Pass Virtuoso!',
} as const;

export const BEAT_PASS_CONFIG: Omit<MidlinePassGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'rhythmPass',
  theme: {
    title: BEAT_PASS_THEME.title,
    subtitle: BEAT_PASS_THEME.subtitle,
    emoji: BEAT_PASS_THEME.emoji,
    gradient: BEAT_PASS_THEME.gradient,
    accent: BEAT_PASS_THEME.accent,
    accentDark: BEAT_PASS_THEME.accentDark,
    ballEmoji: BEAT_PASS_THEME.ballEmoji,
    leftColor: BEAT_PASS_THEME.leftColor,
    rightColor: BEAT_PASS_THEME.rightColor,
    backText: BEAT_PASS_THEME.backText,
    backBorder: BEAT_PASS_THEME.backBorder,
    titleColor: BEAT_PASS_THEME.titleColor,
    subtitleColor: BEAT_PASS_THEME.subtitleColor,
    statLabel: BEAT_PASS_THEME.statLabel,
    statValue: BEAT_PASS_THEME.statValue,
    statBorder: BEAT_PASS_THEME.statBorder,
    playBorder: BEAT_PASS_THEME.playBorder,
    playBg: BEAT_PASS_THEME.playBg,
    sparkleColor: BEAT_PASS_THEME.sparkleColor,
  },
  ttsIntro: BEAT_PASS_THEME.voiceIntro,
  ttsComplete: BEAT_PASS_THEME.voiceComplete,
  ttsCue: BEAT_PASS_THEME.voiceCue,
  ttsSuccess: BEAT_PASS_THEME.voiceSuccess,
  ttsWrong: BEAT_PASS_THEME.voiceWrong,
  ttsMissBeat: BEAT_PASS_THEME.voiceMissBeat,
  congratsMessage: BEAT_PASS_THEME.congrats,
  logType: 'rhythm-pass',
  skillTags: ['timing', 'flow', 'rhythm', 'midline-crossing'],
};
