import type { CrossBodyArrowGameConfig } from '@/components/game/occupational/level4/session7/shared/CrossBodyArrowGame';

export const CROSS_TAP_THEME = {
  title: 'Cross Tap',
  subtitle: 'Left arrow → right hand! Train your brain crossover!',
  emoji: '⬅️',
  gradient: ['#0F172A', '#1E1B4B', '#312E81', '#4338CA'] as [string, string, string, string],
  accent: '#818CF8',
  accentDark: '#C7D2FE',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  bridgeGlow: '#818CF8',
  synapseLeft: '#60A5FA',
  synapseRight: '#FB7185',
  playBorder: 'rgba(129,140,248,0.42)',
  playBg: '#0F172A',
  sparkleColor: '#818CF8',
  backText: '#E0E7FF',
  backBorder: 'rgba(129,140,248,0.38)',
  titleColor: '#EEF2FF',
  subtitleColor: 'rgba(199,210,254,0.9)',
  statLabel: 'rgba(199,210,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(129,140,248,0.32)',
  voiceIntro:
    'Welcome to the neural bridge! When you see a left arrow, tap with your right hand — cross your body!',
  voiceCue: 'Opposite hand for each arrow — left arrow means right hand!',
  voiceComplete: 'Amazing crossover! Your brain pathways are stronger!',
  voiceSuccess: 'Perfect cross tap!',
  voiceWrong: 'Use the opposite hand — cross your body!',
  voiceTooSlow: 'Too slow — catch the arrow!',
  congrats: 'Cross Tap Champion!',
} as const;

export const CROSS_TAP_CONFIG: Omit<CrossBodyArrowGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'tap',
  theme: {
    title: CROSS_TAP_THEME.title,
    subtitle: CROSS_TAP_THEME.subtitle,
    emoji: CROSS_TAP_THEME.emoji,
    gradient: CROSS_TAP_THEME.gradient,
    accent: CROSS_TAP_THEME.accent,
    accentDark: CROSS_TAP_THEME.accentDark,
    leftColor: CROSS_TAP_THEME.leftColor,
    rightColor: CROSS_TAP_THEME.rightColor,
    backText: CROSS_TAP_THEME.backText,
    backBorder: CROSS_TAP_THEME.backBorder,
    titleColor: CROSS_TAP_THEME.titleColor,
    subtitleColor: CROSS_TAP_THEME.subtitleColor,
    statLabel: CROSS_TAP_THEME.statLabel,
    statValue: CROSS_TAP_THEME.statValue,
    statBorder: CROSS_TAP_THEME.statBorder,
    playBorder: CROSS_TAP_THEME.playBorder,
    playBg: CROSS_TAP_THEME.playBg,
    sparkleColor: CROSS_TAP_THEME.sparkleColor,
  },
  ttsIntro: CROSS_TAP_THEME.voiceIntro,
  ttsComplete: CROSS_TAP_THEME.voiceComplete,
  ttsCue: CROSS_TAP_THEME.voiceCue,
  ttsSuccess: CROSS_TAP_THEME.voiceSuccess,
  ttsWrong: CROSS_TAP_THEME.voiceWrong,
  congratsMessage: CROSS_TAP_THEME.congrats,
  logType: 'arrow-touch',
  skillTags: ['brain-crossover', 'cross-body-coordination', 'visual-motor'],
};
