import type { RhythmPatternGameConfig } from '@/components/game/occupational/level4/session10/shared/RhythmPatternGame';

export const RHYTHM_RECALL_THEME = {
  title: 'Rhythm Recall',
  subtitle: 'Listen carefully — remember the pattern — then repeat!',
  emoji: '🧠',
  gradient: ['#422006', '#78350F', '#92400E', '#FBBF24'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  leftColor: '#F59E0B',
  rightColor: '#EF4444',
  memoryGlow: '#FCD34D',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#422006',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(253,230,138,0.9)',
  statLabel: 'rgba(253,230,138,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the memory vault! Listen to the rhythm pattern, hold it in your mind, then repeat it back!',
  voiceListen: 'Listen and remember the pattern!',
  voiceCopy: 'Now repeat the pattern!',
  voiceComplete: 'Memory master! You recalled every rhythm perfectly!',
  voiceSuccess: 'Perfect recall!',
  voiceFail: 'Try again — listen and remember!',
  congrats: 'Rhythm Recall Champion!',
} as const;

export const RHYTHM_RECALL_CONFIG: Omit<RhythmPatternGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'memory',
  theme: {
    title: RHYTHM_RECALL_THEME.title,
    subtitle: RHYTHM_RECALL_THEME.subtitle,
    emoji: RHYTHM_RECALL_THEME.emoji,
    gradient: RHYTHM_RECALL_THEME.gradient,
    accent: RHYTHM_RECALL_THEME.accent,
    accentDark: RHYTHM_RECALL_THEME.accentDark,
    leftColor: RHYTHM_RECALL_THEME.leftColor,
    rightColor: RHYTHM_RECALL_THEME.rightColor,
    backText: RHYTHM_RECALL_THEME.backText,
    backBorder: RHYTHM_RECALL_THEME.backBorder,
    titleColor: RHYTHM_RECALL_THEME.titleColor,
    subtitleColor: RHYTHM_RECALL_THEME.subtitleColor,
    statLabel: RHYTHM_RECALL_THEME.statLabel,
    statValue: RHYTHM_RECALL_THEME.statValue,
    statBorder: RHYTHM_RECALL_THEME.statBorder,
    playBorder: RHYTHM_RECALL_THEME.playBorder,
    playBg: RHYTHM_RECALL_THEME.playBg,
    sparkleColor: RHYTHM_RECALL_THEME.sparkleColor,
  },
  ttsIntro: RHYTHM_RECALL_THEME.voiceIntro,
  ttsComplete: RHYTHM_RECALL_THEME.voiceComplete,
  ttsListen: RHYTHM_RECALL_THEME.voiceListen,
  ttsCopy: RHYTHM_RECALL_THEME.voiceCopy,
  ttsSuccess: RHYTHM_RECALL_THEME.voiceSuccess,
  ttsFail: RHYTHM_RECALL_THEME.voiceFail,
  congratsMessage: RHYTHM_RECALL_THEME.congrats,
  logType: 'memory-rhythm',
  skillTags: ['working-memory', 'pattern-memory', 'rhythm', 'cross-body-coordination'],
};
