import type { CrossBodyArrowGameConfig } from '@/components/game/occupational/level4/session7/shared/CrossBodyArrowGame';

export const FLASH_CROSS_THEME = {
  title: 'Flash Cross',
  subtitle: 'Lightning-fast arrows — tap the opposite hand instantly!',
  emoji: '⚡',
  gradient: ['#451A03', '#78350F', '#B45309', '#F59E0B'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  boltGlow: '#FCD34D',
  flashLeft: '#F59E0B',
  flashRight: '#EF4444',
  leftColor: '#F59E0B',
  rightColor: '#EF4444',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#451A03',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(253,230,138,0.9)',
  statLabel: 'rgba(253,230,138,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the lightning storm! Arrows flash fast — tap the opposite hand before they vanish!',
  voiceCue: 'React fast — left arrow means right hand!',
  voiceComplete: 'Lightning reflexes! You mastered the flash cross!',
  voiceSuccess: 'Flash hit!',
  voiceWrong: 'Wrong hand — cross your body fast!',
  voiceTooSlow: 'Too slow — react faster!',
  congrats: 'Flash Cross Champion!',
} as const;

export const FLASH_CROSS_CONFIG: Omit<CrossBodyArrowGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'speed',
  theme: {
    title: FLASH_CROSS_THEME.title,
    subtitle: FLASH_CROSS_THEME.subtitle,
    emoji: FLASH_CROSS_THEME.emoji,
    gradient: FLASH_CROSS_THEME.gradient,
    accent: FLASH_CROSS_THEME.accent,
    accentDark: FLASH_CROSS_THEME.accentDark,
    leftColor: FLASH_CROSS_THEME.leftColor,
    rightColor: FLASH_CROSS_THEME.rightColor,
    backText: FLASH_CROSS_THEME.backText,
    backBorder: FLASH_CROSS_THEME.backBorder,
    titleColor: FLASH_CROSS_THEME.titleColor,
    subtitleColor: FLASH_CROSS_THEME.subtitleColor,
    statLabel: FLASH_CROSS_THEME.statLabel,
    statValue: FLASH_CROSS_THEME.statValue,
    statBorder: FLASH_CROSS_THEME.statBorder,
    playBorder: FLASH_CROSS_THEME.playBorder,
    playBg: FLASH_CROSS_THEME.playBg,
    sparkleColor: FLASH_CROSS_THEME.sparkleColor,
  },
  ttsIntro: FLASH_CROSS_THEME.voiceIntro,
  ttsComplete: FLASH_CROSS_THEME.voiceComplete,
  ttsCue: FLASH_CROSS_THEME.voiceCue,
  ttsSuccess: FLASH_CROSS_THEME.voiceSuccess,
  ttsWrong: FLASH_CROSS_THEME.voiceWrong,
  ttsTooSlow: FLASH_CROSS_THEME.voiceTooSlow,
  congratsMessage: FLASH_CROSS_THEME.congrats,
  logType: 'speed-arrows',
  skillTags: ['reaction-speed', 'cross-body-coordination', 'visual-motor'],
};
