import type { HorizontalDragGameConfig } from '@/components/game/occupational/level4/session1/shared/HorizontalDragGame';

export const COLOR_SLIDE_THEME = {
  title: 'Color Slide',
  subtitle: 'Slide each paint blob to its matching bucket',
  emoji: '🎨',
  gradient: ['#FFF7ED', '#FFEDD5', '#FBCFE8', '#F472B6'] as [string, string, string, string],
  accent: '#EC4899',
  accentDark: '#BE185D',
  accentViolet: '#8B5CF6',
  studioCream: '#FFF7ED',
  studioWood: '#D97706',
  canvasWhite: '#FFFBEB',
  conveyor: '#78716C',
  paintLabel: '#57534E',
  draggableEmoji: '🔴',
  targetEmoji: '🪣',
  playBorder: 'rgba(236,72,153,0.38)',
  playBg: '#FFFBEB',
  sparkleColor: '#F472B6',
  zoneBorder: 'rgba(236,72,153,0.42)',
  voiceIntro: 'Welcome to the paint studio! Slide each color blob to the matching paint bucket!',
  voiceDrag: 'Slide the paint to the same color bucket!',
  voiceComplete: 'Master painter! You matched every color perfectly!',
  voiceMiss: 'Aim for the matching color bucket!',
  voiceWrong: 'That is the wrong color — find the matching bucket!',
  voiceMatch: 'Perfect match!',
  congrats: 'Studio Color Star!',
} as const;

export const COLOR_SLIDE_CONFIG: Omit<HorizontalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'colorMatch',
  theme: {
    title: COLOR_SLIDE_THEME.title,
    subtitle: COLOR_SLIDE_THEME.subtitle,
    emoji: COLOR_SLIDE_THEME.emoji,
    gradient: COLOR_SLIDE_THEME.gradient,
    accent: COLOR_SLIDE_THEME.accent,
    accentDark: COLOR_SLIDE_THEME.accentDark,
    draggableEmoji: COLOR_SLIDE_THEME.draggableEmoji,
    targetEmoji: COLOR_SLIDE_THEME.targetEmoji,
    backText: '#831843',
    backBorder: 'rgba(236,72,153,0.35)',
    titleColor: '#500724',
    subtitleColor: '#9D174D',
    statLabel: '#BE185D',
    statValue: '#500724',
    statBorder: 'rgba(236,72,153,0.25)',
    playBorder: COLOR_SLIDE_THEME.playBorder,
    playBg: COLOR_SLIDE_THEME.playBg,
    sparkleColor: COLOR_SLIDE_THEME.sparkleColor,
    zoneBorder: COLOR_SLIDE_THEME.zoneBorder,
  },
  ttsIntro: COLOR_SLIDE_THEME.voiceIntro,
  ttsComplete: COLOR_SLIDE_THEME.voiceComplete,
  ttsDrag: COLOR_SLIDE_THEME.voiceDrag,
  ttsMiss: COLOR_SLIDE_THEME.voiceMiss,
  ttsColorWrong: COLOR_SLIDE_THEME.voiceWrong,
  ttsGoal: COLOR_SLIDE_THEME.voiceMatch,
  congratsMessage: COLOR_SLIDE_THEME.congrats,
  logType: 'color-match-drag',
  skillTags: ['visual-matching', 'motor', 'drag-left-right'],
};
