import type { DualDragGameConfig } from '@/components/game/occupational/level4/session9/shared/DualDragGame';

export const BOX_SORT_THEME = {
  title: 'Box Sort',
  subtitle: 'Circle → left bin, square → right bin — use both hands!',
  emoji: '📦',
  gradient: ['#2E1065', '#4C1D95', '#6D28D9', '#8B5CF6'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  circleColor: '#6366F1',
  squareColor: '#14B8A6',
  leftColor: '#6366F1',
  rightColor: '#14B8A6',
  circleGlow: '#818CF8',
  squareGlow: '#2DD4BF',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#2E1065',
  sparkleColor: '#A78BFA',
  zoneBorder: 'rgba(167,139,250,0.55)',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(221,214,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the sorting warehouse! Drag the circle to the left bin and the square to the right bin — both at the same time!',
  voiceCue: 'Circle to left bin, square to right bin — both hands!',
  voiceComplete: 'Sorting superstar! You multitasked both shapes perfectly!',
  voiceSuccess: 'Perfect sorting!',
  congrats: 'Box Sort Champion!',
} as const;

export const BOX_SORT_CONFIG: Omit<DualDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'shapeSort',
  theme: {
    title: BOX_SORT_THEME.title,
    subtitle: BOX_SORT_THEME.subtitle,
    emoji: BOX_SORT_THEME.emoji,
    gradient: BOX_SORT_THEME.gradient,
    accent: BOX_SORT_THEME.accent,
    accentDark: BOX_SORT_THEME.accentDark,
    leftColor: BOX_SORT_THEME.leftColor,
    rightColor: BOX_SORT_THEME.rightColor,
    backText: BOX_SORT_THEME.backText,
    backBorder: BOX_SORT_THEME.backBorder,
    titleColor: BOX_SORT_THEME.titleColor,
    subtitleColor: BOX_SORT_THEME.subtitleColor,
    statLabel: BOX_SORT_THEME.statLabel,
    statValue: BOX_SORT_THEME.statValue,
    statBorder: BOX_SORT_THEME.statBorder,
    playBorder: BOX_SORT_THEME.playBorder,
    playBg: BOX_SORT_THEME.playBg,
    sparkleColor: BOX_SORT_THEME.sparkleColor,
    zoneBorder: BOX_SORT_THEME.zoneBorder,
  },
  ttsIntro: BOX_SORT_THEME.voiceIntro,
  ttsComplete: BOX_SORT_THEME.voiceComplete,
  ttsCue: BOX_SORT_THEME.voiceCue,
  ttsSuccess: BOX_SORT_THEME.voiceSuccess,
  congratsMessage: BOX_SORT_THEME.congrats,
  logType: 'shape-sort',
  skillTags: ['multitasking', 'simultaneous-dragging', 'sorting', 'categorization'],
};
