import type { CrossBodySequenceGameConfig } from '@/components/game/occupational/level4/session7/shared/CrossBodySequenceGame';

export const ARROW_CHAIN_THEME = {
  title: 'Arrow Chain',
  subtitle: 'Watch the chain — tap opposite hands in order!',
  emoji: '🔗',
  gradient: ['#022C22', '#064E3B', '#047857', '#10B981'] as [string, string, string, string],
  accent: '#34D399',
  accentDark: '#A7F3D0',
  linkGlow: '#6EE7B7',
  nodeLeft: '#10B981',
  nodeRight: '#F43F5E',
  leftColor: '#10B981',
  rightColor: '#F43F5E',
  playBorder: 'rgba(52,211,153,0.42)',
  playBg: '#022C22',
  sparkleColor: '#34D399',
  backText: '#D1FAE5',
  backBorder: 'rgba(52,211,153,0.38)',
  titleColor: '#ECFDF5',
  subtitleColor: 'rgba(167,243,208,0.9)',
  statLabel: 'rgba(167,243,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(52,211,153,0.32)',
  voiceIntro:
    'Welcome to the memory chain! Watch three arrows light up, then tap the opposite hand for each one in order!',
  voiceCue: 'Watch the arrows, then tap opposite hands in order!',
  voiceComplete: 'Chain mastered! Your memory and crossover skills are linked!',
  voiceSuccess: 'Perfect chain!',
  voiceWrong: 'Wrong hand — watch the chain again!',
  congrats: 'Arrow Chain Champion!',
} as const;

export const ARROW_CHAIN_CONFIG: Omit<CrossBodySequenceGameConfig, 'onBack' | 'onComplete'> = {
  theme: {
    title: ARROW_CHAIN_THEME.title,
    subtitle: ARROW_CHAIN_THEME.subtitle,
    emoji: ARROW_CHAIN_THEME.emoji,
    gradient: ARROW_CHAIN_THEME.gradient,
    accent: ARROW_CHAIN_THEME.accent,
    accentDark: ARROW_CHAIN_THEME.accentDark,
    leftColor: ARROW_CHAIN_THEME.leftColor,
    rightColor: ARROW_CHAIN_THEME.rightColor,
    backText: ARROW_CHAIN_THEME.backText,
    backBorder: ARROW_CHAIN_THEME.backBorder,
    titleColor: ARROW_CHAIN_THEME.titleColor,
    subtitleColor: ARROW_CHAIN_THEME.subtitleColor,
    statLabel: ARROW_CHAIN_THEME.statLabel,
    statValue: ARROW_CHAIN_THEME.statValue,
    statBorder: ARROW_CHAIN_THEME.statBorder,
    playBorder: ARROW_CHAIN_THEME.playBorder,
    playBg: ARROW_CHAIN_THEME.playBg,
    sparkleColor: ARROW_CHAIN_THEME.sparkleColor,
  },
  ttsIntro: ARROW_CHAIN_THEME.voiceIntro,
  ttsComplete: ARROW_CHAIN_THEME.voiceComplete,
  ttsCue: ARROW_CHAIN_THEME.voiceCue,
  ttsSuccess: ARROW_CHAIN_THEME.voiceSuccess,
  ttsWrong: ARROW_CHAIN_THEME.voiceWrong,
  congratsMessage: ARROW_CHAIN_THEME.congrats,
  logType: 'arrow-sequence',
  skillTags: ['memory', 'movement', 'sequence-following', 'cross-body-coordination'],
};
