import type { SideTapGameConfig } from '@/components/game/occupational/level4/session8/shared/SideTapGame';

export const QUICK_SWITCH_THEME = {
  title: 'Quick Switch',
  subtitle: 'Tap the active side — it gets faster every round!',
  emoji: '⚡',
  gradient: ['#1C1917', '#422006', '#78350F', '#FBBF24'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  boltLeft: '#F59E0B',
  boltRight: '#EF4444',
  leftColor: '#F59E0B',
  rightColor: '#EF4444',
  leftIcon: '⚡',
  rightIcon: '⚡',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#1C1917',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(253,230,138,0.9)',
  statLabel: 'rgba(253,230,138,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the lightning arena! Tap whichever side flashes — but hurry, it gets faster each round!',
  voiceCue: 'Switch sides fast — speed increases!',
  voiceComplete: 'Lightning reflexes! You mastered rapid side switching!',
  voiceSuccess: 'Quick switch!',
  voiceMiss: 'Too slow — tap before the flash fades!',
  voiceWrong: 'Wrong side — tap the flashing panel!',
  congrats: 'Quick Switch Champion!',
} as const;

export const QUICK_SWITCH_CONFIG: Omit<SideTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'fast',
  theme: {
    title: QUICK_SWITCH_THEME.title,
    subtitle: QUICK_SWITCH_THEME.subtitle,
    emoji: QUICK_SWITCH_THEME.emoji,
    gradient: QUICK_SWITCH_THEME.gradient,
    accent: QUICK_SWITCH_THEME.accent,
    accentDark: QUICK_SWITCH_THEME.accentDark,
    leftColor: QUICK_SWITCH_THEME.leftColor,
    rightColor: QUICK_SWITCH_THEME.rightColor,
    leftIcon: QUICK_SWITCH_THEME.leftIcon,
    rightIcon: QUICK_SWITCH_THEME.rightIcon,
    backText: QUICK_SWITCH_THEME.backText,
    backBorder: QUICK_SWITCH_THEME.backBorder,
    titleColor: QUICK_SWITCH_THEME.titleColor,
    subtitleColor: QUICK_SWITCH_THEME.subtitleColor,
    statLabel: QUICK_SWITCH_THEME.statLabel,
    statValue: QUICK_SWITCH_THEME.statValue,
    statBorder: QUICK_SWITCH_THEME.statBorder,
    playBorder: QUICK_SWITCH_THEME.playBorder,
    playBg: QUICK_SWITCH_THEME.playBg,
    sparkleColor: QUICK_SWITCH_THEME.sparkleColor,
  },
  ttsIntro: QUICK_SWITCH_THEME.voiceIntro,
  ttsComplete: QUICK_SWITCH_THEME.voiceComplete,
  ttsCue: QUICK_SWITCH_THEME.voiceCue,
  ttsSuccess: QUICK_SWITCH_THEME.voiceSuccess,
  ttsMiss: QUICK_SWITCH_THEME.voiceMiss,
  ttsWrong: QUICK_SWITCH_THEME.voiceWrong,
  congratsMessage: QUICK_SWITCH_THEME.congrats,
  logType: 'fast-switch',
  skillTags: ['brain-speed', 'rapid-switching', 'alternating-sides', 'reaction-time'],
};
