import type { RhythmPatternGameConfig } from '@/components/game/occupational/level4/session10/shared/RhythmPatternGame';

export const BEAT_MIRROR_THEME = {
  title: 'Beat Mirror',
  subtitle: 'Listen to the beat — mirror left, right, or both hands!',
  emoji: '🎵',
  gradient: ['#2E1065', '#4C1D95', '#6D28D9', '#8B5CF6'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  leftColor: '#8B5CF6',
  rightColor: '#F472B6',
  waveGlow: '#C4B5FD',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#2E1065',
  sparkleColor: '#A78BFA',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(221,214,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the beat mirror booth! Listen to the rhythm, then mirror the hand movements — left, right, or both!',
  voiceListen: 'Listen to the beat pattern!',
  voiceCopy: 'Now mirror the hand movements!',
  voiceComplete: 'Sync superstar! Your hands move perfectly with the beat!',
  voiceSuccess: 'Perfect beat!',
  voiceFail: 'Try again — listen and mirror!',
  congrats: 'Beat Mirror Champion!',
} as const;

export const BEAT_MIRROR_CONFIG: Omit<RhythmPatternGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'musicBeat',
  theme: {
    title: BEAT_MIRROR_THEME.title,
    subtitle: BEAT_MIRROR_THEME.subtitle,
    emoji: BEAT_MIRROR_THEME.emoji,
    gradient: BEAT_MIRROR_THEME.gradient,
    accent: BEAT_MIRROR_THEME.accent,
    accentDark: BEAT_MIRROR_THEME.accentDark,
    leftColor: BEAT_MIRROR_THEME.leftColor,
    rightColor: BEAT_MIRROR_THEME.rightColor,
    backText: BEAT_MIRROR_THEME.backText,
    backBorder: BEAT_MIRROR_THEME.backBorder,
    titleColor: BEAT_MIRROR_THEME.titleColor,
    subtitleColor: BEAT_MIRROR_THEME.subtitleColor,
    statLabel: BEAT_MIRROR_THEME.statLabel,
    statValue: BEAT_MIRROR_THEME.statValue,
    statBorder: BEAT_MIRROR_THEME.statBorder,
    playBorder: BEAT_MIRROR_THEME.playBorder,
    playBg: BEAT_MIRROR_THEME.playBg,
    sparkleColor: BEAT_MIRROR_THEME.sparkleColor,
  },
  ttsIntro: BEAT_MIRROR_THEME.voiceIntro,
  ttsComplete: BEAT_MIRROR_THEME.voiceComplete,
  ttsListen: BEAT_MIRROR_THEME.voiceListen,
  ttsCopy: BEAT_MIRROR_THEME.voiceCopy,
  ttsSuccess: BEAT_MIRROR_THEME.voiceSuccess,
  ttsFail: BEAT_MIRROR_THEME.voiceFail,
  congratsMessage: BEAT_MIRROR_THEME.congrats,
  logType: 'music-copy',
  skillTags: ['auditory-motor-sync', 'rhythm', 'beat-synchronization', 'cross-body-coordination'],
};
