import type { DiagonalXPathGameConfig } from '@/components/game/occupational/level4/session3/shared/DiagonalXPathGame';

export const X_TRACE_THEME = {
  title: 'X Trace',
  subtitle: 'Trace both legs of the glowing sigil — complete the ancient X',
  emoji: '✨',
  gradient: ['#1E0A3C', '#4C1D95', '#6B21A8', '#C026D3'] as [string, string, string, string],
  accent: '#E879F9',
  accentDark: '#F0ABFC',
  accentGold: '#FDE68A',
  accentViolet: '#A78BFA',
  chamberDark: '#1A0A2E',
  sigilGlow: '#E879F9',
  runeGold: '#FBBF24',
  draggableEmoji: '🖊️',
  playBorder: 'rgba(232,121,249,0.42)',
  playBg: '#1A0A2E',
  sparkleColor: '#E879F9',
  pathColor: '#E879F9',
  backText: '#FAE8FF',
  backBorder: 'rgba(232,121,249,0.38)',
  titleColor: '#FAF5FF',
  subtitleColor: 'rgba(233,213,255,0.9)',
  statLabel: 'rgba(233,213,255,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(232,121,249,0.32)',
  voiceIntro:
    'Enter the sigil chamber! Trace the first diagonal from top-left to bottom-right, then the second from top-right to bottom-left to complete the X!',
  voiceDrag: 'Trace the glowing X — both legs!',
  voiceComplete: 'The ancient sigil is complete! Your hand and eyes are perfectly in sync!',
  voiceMiss: 'Stay on the sigil path — finish both legs of the X!',
  voiceTraced: 'Sigil complete!',
  voiceLeg1: 'First leg done!',
  congrats: 'X Trace Master!',
} as const;

export const X_TRACE_CONFIG: Omit<DiagonalXPathGameConfig, 'onBack' | 'onComplete'> = {
  theme: {
    title: X_TRACE_THEME.title,
    subtitle: X_TRACE_THEME.subtitle,
    emoji: X_TRACE_THEME.emoji,
    gradient: X_TRACE_THEME.gradient,
    accent: X_TRACE_THEME.accent,
    accentDark: X_TRACE_THEME.accentDark,
    pathColor: X_TRACE_THEME.pathColor,
    draggableEmoji: X_TRACE_THEME.draggableEmoji,
    backText: X_TRACE_THEME.backText,
    backBorder: X_TRACE_THEME.backBorder,
    titleColor: X_TRACE_THEME.titleColor,
    subtitleColor: X_TRACE_THEME.subtitleColor,
    statLabel: X_TRACE_THEME.statLabel,
    statValue: X_TRACE_THEME.statValue,
    statBorder: X_TRACE_THEME.statBorder,
    playBorder: X_TRACE_THEME.playBorder,
    playBg: X_TRACE_THEME.playBg,
    sparkleColor: X_TRACE_THEME.sparkleColor,
  },
  ttsIntro: X_TRACE_THEME.voiceIntro,
  ttsComplete: X_TRACE_THEME.voiceComplete,
  ttsDrag: X_TRACE_THEME.voiceDrag,
  ttsMiss: X_TRACE_THEME.voiceMiss,
  ttsGoal: X_TRACE_THEME.voiceTraced,
  ttsLeg1: X_TRACE_THEME.voiceLeg1,
  congratsMessage: X_TRACE_THEME.congrats,
  logType: 'x-path-trace',
  skillTags: ['eye-hand-coordination', 'diagonal-drag'],
};
