import type { SideTapGameConfig } from '@/components/game/occupational/level4/session8/shared/SideTapGame';

export const GLOW_TAP_THEME = {
  title: 'Glow Tap',
  subtitle: 'Watch which side glows — tap it fast!',
  emoji: '💡',
  gradient: ['#0C1929', '#0F2744', '#1E3A5F', '#2563EB'] as [string, string, string, string],
  accent: '#60A5FA',
  accentDark: '#BFDBFE',
  glowLeft: '#3B82F6',
  glowRight: '#F43F5E',
  neonPulse: '#93C5FD',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  leftIcon: '💡',
  rightIcon: '💡',
  playBorder: 'rgba(96,165,250,0.42)',
  playBg: '#0C1929',
  sparkleColor: '#60A5FA',
  backText: '#DBEAFE',
  backBorder: 'rgba(96,165,250,0.38)',
  titleColor: '#EFF6FF',
  subtitleColor: 'rgba(191,219,254,0.9)',
  statLabel: 'rgba(191,219,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(96,165,250,0.32)',
  voiceIntro:
    'Welcome to the neon panels! Watch which side lights up and tap it before the glow fades!',
  voiceCue: 'Tap the glowing side!',
  voiceComplete: 'Brilliant bilateral tapping! Both sides are activated!',
  voiceSuccess: 'Perfect glow tap!',
  voiceMiss: 'Too slow — tap the glowing side!',
  voiceWrong: 'Wrong side — tap the glowing panel!',
  congrats: 'Glow Tap Champion!',
} as const;

export const GLOW_TAP_CONFIG: Omit<SideTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'lights',
  theme: {
    title: GLOW_TAP_THEME.title,
    subtitle: GLOW_TAP_THEME.subtitle,
    emoji: GLOW_TAP_THEME.emoji,
    gradient: GLOW_TAP_THEME.gradient,
    accent: GLOW_TAP_THEME.accent,
    accentDark: GLOW_TAP_THEME.accentDark,
    leftColor: GLOW_TAP_THEME.leftColor,
    rightColor: GLOW_TAP_THEME.rightColor,
    leftIcon: GLOW_TAP_THEME.leftIcon,
    rightIcon: GLOW_TAP_THEME.rightIcon,
    backText: GLOW_TAP_THEME.backText,
    backBorder: GLOW_TAP_THEME.backBorder,
    titleColor: GLOW_TAP_THEME.titleColor,
    subtitleColor: GLOW_TAP_THEME.subtitleColor,
    statLabel: GLOW_TAP_THEME.statLabel,
    statValue: GLOW_TAP_THEME.statValue,
    statBorder: GLOW_TAP_THEME.statBorder,
    playBorder: GLOW_TAP_THEME.playBorder,
    playBg: GLOW_TAP_THEME.playBg,
    sparkleColor: GLOW_TAP_THEME.sparkleColor,
  },
  ttsIntro: GLOW_TAP_THEME.voiceIntro,
  ttsComplete: GLOW_TAP_THEME.voiceComplete,
  ttsCue: GLOW_TAP_THEME.voiceCue,
  ttsSuccess: GLOW_TAP_THEME.voiceSuccess,
  ttsMiss: GLOW_TAP_THEME.voiceMiss,
  ttsWrong: GLOW_TAP_THEME.voiceWrong,
  congratsMessage: GLOW_TAP_THEME.congrats,
  logType: 'side-lights',
  skillTags: ['bilateral-activation', 'alternating-sides', 'visual-motor'],
};
