import type { DiagonalPathDragGameConfig } from '@/components/game/occupational/level4/session3/shared/DiagonalPathDragGame';

export const ZIGZAG_RUN_THEME = {
  title: 'Zigzag Run',
  subtitle: 'Ride the lightning bolt along the zigzag canyon trail to the thunder gate',
  emoji: '⚡',
  gradient: ['#0A0A0A', '#1C1917', '#365314', '#84CC16'] as [string, string, string, string],
  accent: '#A3E635',
  accentDark: '#BEF264',
  accentGold: '#FACC15',
  accentElectric: '#EAB308',
  canyonDark: '#0C0A09',
  rockMid: '#292524',
  boltGlow: '#FACC15',
  draggableEmoji: '⚡',
  targetEmoji: '🌩️',
  playBorder: 'rgba(163,230,53,0.42)',
  playBg: '#0C0A09',
  sparkleColor: '#FACC15',
  pathColor: '#A3E635',
  backText: '#ECFCCB',
  backBorder: 'rgba(163,230,53,0.38)',
  titleColor: '#F7FEE7',
  subtitleColor: 'rgba(217,249,157,0.9)',
  statLabel: 'rgba(217,249,157,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(163,230,53,0.32)',
  voiceIntro:
    'Enter the lightning canyon! Trace the zigzag bolt path from the spark at the top-left all the way to the thunder gate at the bottom-right!',
  voiceDrag: 'Follow the zigzag lightning trail!',
  voiceComplete: 'Thunder master! You rode every zigzag bolt to the gate!',
  voiceMiss: 'Stay on the lightning path — reach the thunder gate!',
  voiceZapped: 'Zapped!',
  congrats: 'Zigzag Run Legend!',
} as const;

export const ZIGZAG_RUN_CONFIG: Omit<DiagonalPathDragGameConfig, 'onBack' | 'onComplete'> = {
  theme: {
    title: ZIGZAG_RUN_THEME.title,
    subtitle: ZIGZAG_RUN_THEME.subtitle,
    emoji: ZIGZAG_RUN_THEME.emoji,
    gradient: ZIGZAG_RUN_THEME.gradient,
    accent: ZIGZAG_RUN_THEME.accent,
    accentDark: ZIGZAG_RUN_THEME.accentDark,
    pathColor: ZIGZAG_RUN_THEME.pathColor,
    draggableEmoji: ZIGZAG_RUN_THEME.draggableEmoji,
    backText: ZIGZAG_RUN_THEME.backText,
    backBorder: ZIGZAG_RUN_THEME.backBorder,
    titleColor: ZIGZAG_RUN_THEME.titleColor,
    subtitleColor: ZIGZAG_RUN_THEME.subtitleColor,
    statLabel: ZIGZAG_RUN_THEME.statLabel,
    statValue: ZIGZAG_RUN_THEME.statValue,
    statBorder: ZIGZAG_RUN_THEME.statBorder,
    playBorder: ZIGZAG_RUN_THEME.playBorder,
    playBg: ZIGZAG_RUN_THEME.playBg,
    sparkleColor: ZIGZAG_RUN_THEME.sparkleColor,
  },
  ttsIntro: ZIGZAG_RUN_THEME.voiceIntro,
  ttsComplete: ZIGZAG_RUN_THEME.voiceComplete,
  ttsDrag: ZIGZAG_RUN_THEME.voiceDrag,
  ttsMiss: ZIGZAG_RUN_THEME.voiceMiss,
  ttsGoal: ZIGZAG_RUN_THEME.voiceZapped,
  congratsMessage: ZIGZAG_RUN_THEME.congrats,
  logType: 'zigzag-drag',
  skillTags: ['direction-switching', 'diagonal-drag'],
};
