import type { CrossBodyArrowGameConfig } from '@/components/game/occupational/level4/session7/shared/CrossBodyArrowGame';

export const DRIFT_TAP_THEME = {
  title: 'Drift Tap',
  subtitle: 'Track the drifting arrow — tap with the opposite hand!',
  emoji: '🌠',
  gradient: ['#2E1065', '#4C1D95', '#6D28D9', '#8B5CF6'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  driftGlow: '#C4B5FD',
  cometLeft: '#8B5CF6',
  cometRight: '#F472B6',
  leftColor: '#8B5CF6',
  rightColor: '#F472B6',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#2E1065',
  sparkleColor: '#A78BFA',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(221,214,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the nebula drift zone! Track the moving arrow and tap with your opposite hand before it floats away!',
  voiceCue: 'Catch the drifting arrow — use the opposite hand!',
  voiceComplete: 'Stellar tracking! You caught every drifting arrow!',
  voiceSuccess: 'Caught it!',
  voiceWrong: 'Use the opposite hand — cross your body!',
  voiceTooSlow: 'Too slow! Catch the arrow!',
  congrats: 'Drift Tap Champion!',
} as const;

export const DRIFT_TAP_CONFIG: Omit<CrossBodyArrowGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'moving',
  theme: {
    title: DRIFT_TAP_THEME.title,
    subtitle: DRIFT_TAP_THEME.subtitle,
    emoji: DRIFT_TAP_THEME.emoji,
    gradient: DRIFT_TAP_THEME.gradient,
    accent: DRIFT_TAP_THEME.accent,
    accentDark: DRIFT_TAP_THEME.accentDark,
    leftColor: DRIFT_TAP_THEME.leftColor,
    rightColor: DRIFT_TAP_THEME.rightColor,
    backText: DRIFT_TAP_THEME.backText,
    backBorder: DRIFT_TAP_THEME.backBorder,
    titleColor: DRIFT_TAP_THEME.titleColor,
    subtitleColor: DRIFT_TAP_THEME.subtitleColor,
    statLabel: DRIFT_TAP_THEME.statLabel,
    statValue: DRIFT_TAP_THEME.statValue,
    statBorder: DRIFT_TAP_THEME.statBorder,
    playBorder: DRIFT_TAP_THEME.playBorder,
    playBg: DRIFT_TAP_THEME.playBg,
    sparkleColor: DRIFT_TAP_THEME.sparkleColor,
  },
  ttsIntro: DRIFT_TAP_THEME.voiceIntro,
  ttsComplete: DRIFT_TAP_THEME.voiceComplete,
  ttsCue: DRIFT_TAP_THEME.voiceCue,
  ttsSuccess: DRIFT_TAP_THEME.voiceSuccess,
  ttsWrong: DRIFT_TAP_THEME.voiceWrong,
  ttsTooSlow: DRIFT_TAP_THEME.voiceTooSlow,
  congratsMessage: DRIFT_TAP_THEME.congrats,
  logType: 'moving-arrows',
  skillTags: ['tracking-skills', 'cross-body-coordination', 'visual-motor'],
};
