import type { SideTapGameConfig } from '@/components/game/occupational/level4/session8/shared/SideTapGame';

export const SOUND_TAP_THEME = {
  title: 'Sound Tap',
  subtitle: 'Listen closely — tap the side where you hear the sound!',
  emoji: '🔊',
  gradient: ['#2E1065', '#4C1D95', '#6D28D9', '#8B5CF6'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  waveGlow: '#C4B5FD',
  speakerLeft: '#8B5CF6',
  speakerRight: '#F472B6',
  leftColor: '#8B5CF6',
  rightColor: '#F472B6',
  leftIcon: '🔊',
  rightIcon: '🔊',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#2E1065',
  sparkleColor: '#A78BFA',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(221,214,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the sound studio! Listen for the bell, drum, or clap — then tap the side where you heard it!',
  voiceCue: 'Tap the side where you hear the sound!',
  voiceComplete: 'Amazing ears! You nailed every sound localization!',
  voiceSuccess: 'Perfect sound tap!',
  voiceMiss: 'Too slow — listen and tap faster!',
  voiceWrong: 'Wrong side — listen again!',
  congrats: 'Sound Tap Champion!',
} as const;

export const SOUND_TAP_CONFIG: Omit<SideTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'sound',
  theme: {
    title: SOUND_TAP_THEME.title,
    subtitle: SOUND_TAP_THEME.subtitle,
    emoji: SOUND_TAP_THEME.emoji,
    gradient: SOUND_TAP_THEME.gradient,
    accent: SOUND_TAP_THEME.accent,
    accentDark: SOUND_TAP_THEME.accentDark,
    leftColor: SOUND_TAP_THEME.leftColor,
    rightColor: SOUND_TAP_THEME.rightColor,
    leftIcon: SOUND_TAP_THEME.leftIcon,
    rightIcon: SOUND_TAP_THEME.rightIcon,
    backText: SOUND_TAP_THEME.backText,
    backBorder: SOUND_TAP_THEME.backBorder,
    titleColor: SOUND_TAP_THEME.titleColor,
    subtitleColor: SOUND_TAP_THEME.subtitleColor,
    statLabel: SOUND_TAP_THEME.statLabel,
    statValue: SOUND_TAP_THEME.statValue,
    statBorder: SOUND_TAP_THEME.statBorder,
    playBorder: SOUND_TAP_THEME.playBorder,
    playBg: SOUND_TAP_THEME.playBg,
    sparkleColor: SOUND_TAP_THEME.sparkleColor,
  },
  ttsIntro: SOUND_TAP_THEME.voiceIntro,
  ttsComplete: SOUND_TAP_THEME.voiceComplete,
  ttsCue: SOUND_TAP_THEME.voiceCue,
  ttsSuccess: SOUND_TAP_THEME.voiceSuccess,
  ttsMiss: SOUND_TAP_THEME.voiceMiss,
  ttsWrong: SOUND_TAP_THEME.voiceWrong,
  congratsMessage: SOUND_TAP_THEME.congrats,
  logType: 'sound-side-tap',
  skillTags: ['auditory-processing', 'alternating-sides', 'sound-localization'],
};
