export const HOLD_HIT_THEME = {
  title: 'Hold & Hit',
  subtitle: 'Anchor one hand steady — strike fast with the other!',
  emoji: '🤲',
  gradient: ['#0C1A1F', '#134E4A', '#1E3A5F', '#0F766E'] as [string, string, string, string],
  accent: '#2DD4BF',
  accentDark: '#5EEAD4',
  accentAmber: '#FBBF24',
  accentTeal: '#14B8A6',
  labDark: '#0C1A1F',
  anchorGlow: '#2DD4BF',
  strikeGlow: '#FBBF24',
  holdBlue: '#0D9488',
  holdRed: '#0F766E',
  tapGold: '#F59E0B',
  tapGreen: '#FBBF24',
  playBorder: 'rgba(45,212,191,0.42)',
  playBg: '#0C1A1F',
  sparkleColor: '#2DD4BF',
  backText: '#CCFBF1',
  backBorder: 'rgba(45,212,191,0.38)',
  titleColor: '#F0FDFA',
  subtitleColor: 'rgba(153,246,228,0.9)',
  statLabel: 'rgba(153,246,228,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(45,212,191,0.32)',
  voiceIntro:
    'Welcome to the split-hand lab! Hold one pad steady with one hand, then tap the strike pad with your other hand!',
  voiceHoldLeft: 'Hold with your left hand, tap with your right!',
  voiceHoldRight: 'Hold with your right hand, tap with your left!',
  voiceKeepHolding: 'Keep holding the anchor pad!',
  voiceNowTap: 'Anchor locked — now tap!',
  voiceComplete: 'Outstanding! Your hands are working independently!',
  voiceSuccess: 'Perfect split control!',
  congrats: 'Hold & Hit Master!',
} as const;
