import type { DiagonalDragGameConfig } from '@/components/game/occupational/level4/session3/shared/DiagonalDragGame';

export const CORNER_MATCH_THEME = {
  title: 'Corner Match',
  subtitle: 'Carry the glowing gem from its pedestal to the matching corner across the vault',
  emoji: '💎',
  gradient: ['#1A0A14', '#881337', '#BE123C', '#F59E0B'] as [string, string, string, string],
  accent: '#FB7185',
  accentDark: '#FDA4AF',
  accentGold: '#FBBF24',
  accentRose: '#F43F5E',
  vaultDark: '#1A0A14',
  velvet: '#4C0519',
  prismGlow: '#FBBF24',
  playBorder: 'rgba(251,113,133,0.42)',
  playBg: '#1A0A14',
  sparkleColor: '#FBBF24',
  zoneBorder: 'rgba(251,191,36,0.45)',
  backText: '#FFE4E6',
  backBorder: 'rgba(251,113,133,0.38)',
  titleColor: '#FFF1F2',
  subtitleColor: 'rgba(254,205,211,0.9)',
  statLabel: 'rgba(254,205,211,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,113,133,0.32)',
  voiceIntro:
    'Welcome to the prism vault! Pick up the glowing gem and drag it diagonally to the matching pedestal in the opposite corner!',
  voiceDrag: 'Match the gem at the opposite corner!',
  voiceComplete: 'Jewel master! Every gem found its matching corner!',
  voiceMiss: 'Drag the gem to the matching pedestal in the opposite corner!',
  voiceMatched: 'Matched!',
  congrats: 'Corner Match Hero!',
} as const;

export const CORNER_MATCH_CONFIG: Omit<DiagonalDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'colorMatch',
  theme: {
    title: CORNER_MATCH_THEME.title,
    subtitle: CORNER_MATCH_THEME.subtitle,
    emoji: CORNER_MATCH_THEME.emoji,
    gradient: CORNER_MATCH_THEME.gradient,
    accent: CORNER_MATCH_THEME.accent,
    accentDark: CORNER_MATCH_THEME.accentDark,
    draggableEmoji: '💎',
    targetEmoji: '💎',
    backText: CORNER_MATCH_THEME.backText,
    backBorder: CORNER_MATCH_THEME.backBorder,
    titleColor: CORNER_MATCH_THEME.titleColor,
    subtitleColor: CORNER_MATCH_THEME.subtitleColor,
    statLabel: CORNER_MATCH_THEME.statLabel,
    statValue: CORNER_MATCH_THEME.statValue,
    statBorder: CORNER_MATCH_THEME.statBorder,
    playBorder: CORNER_MATCH_THEME.playBorder,
    playBg: CORNER_MATCH_THEME.playBg,
    sparkleColor: CORNER_MATCH_THEME.sparkleColor,
    zoneBorder: CORNER_MATCH_THEME.zoneBorder,
  },
  ttsIntro: CORNER_MATCH_THEME.voiceIntro,
  ttsComplete: CORNER_MATCH_THEME.voiceComplete,
  ttsDrag: CORNER_MATCH_THEME.voiceDrag,
  ttsMiss: CORNER_MATCH_THEME.voiceMiss,
  ttsGoal: CORNER_MATCH_THEME.voiceMatched,
  congratsMessage: CORNER_MATCH_THEME.congrats,
  logType: 'diagonal-match',
  skillTags: ['spatial-awareness', 'diagonal-drag'],
};
