/**
 * OT Level 4 Session 9 — Two-hand simultaneous drag theme tokens.
 */

/** Game 1 — Twin Drag · Bilateral workshop (drag both objects to targets) */
export const TWIN_DRAG_THEME = {
  title: 'Twin Drag',
  subtitle: 'Use both hands — drag left and right objects to their targets!',
  emoji: '🤲',
  gradient: ['#0C1929', '#0F2744', '#1E3A5F', '#2563EB'] as [string, string, string, string],
  accent: '#60A5FA',
  accentDark: '#BFDBFE',
  leftColor: '#3B82F6',
  rightColor: '#F43F5E',
  leftGlow: '#60A5FA',
  rightGlow: '#FB7185',
  leftIcon: '🔵',
  rightIcon: '🔴',
  playBorder: 'rgba(96,165,250,0.42)',
  playBg: '#0C1929',
  sparkleColor: '#60A5FA',
  zoneBorder: 'rgba(96,165,250,0.55)',
  backText: '#DBEAFE',
  backBorder: 'rgba(96,165,250,0.38)',
  titleColor: '#EFF6FF',
  subtitleColor: 'rgba(191,219,254,0.9)',
  statLabel: 'rgba(191,219,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(96,165,250,0.32)',
  voiceIntro:
    'Welcome to the twin workshop! Use both hands at once — drag the blue and red objects to their targets!',
  voiceCue: 'Drag left and right objects to their targets together!',
  voiceComplete: 'Both hands working as one! You mastered twin dragging!',
  voiceSuccess: 'Both objects placed!',
  congrats: 'Twin Drag Champion!',
} as const;

/** Game 2 — Pair Match · Harmony merge (drag matching shapes to center together) */
export const PAIR_MATCH_THEME = {
  title: 'Pair Match',
  subtitle: 'Drag both matching shapes to the center — together!',
  emoji: '🤝',
  gradient: ['#052E16', '#14532D', '#166534', '#22C55E'] as [string, string, string, string],
  accent: '#4ADE80',
  accentDark: '#BBF7D0',
  leftColor: '#22C55E',
  rightColor: '#10B981',
  mergeGlow: '#6EE7B7',
  playBorder: 'rgba(74,222,128,0.42)',
  playBg: '#052E16',
  sparkleColor: '#4ADE80',
  zoneBorder: 'rgba(74,222,128,0.55)',
  backText: '#DCFCE7',
  backBorder: 'rgba(74,222,128,0.38)',
  titleColor: '#F0FDF4',
  subtitleColor: 'rgba(187,247,208,0.9)',
  statLabel: 'rgba(187,247,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(74,222,128,0.32)',
  voiceIntro:
    'Welcome to the pair merge zone! Two matching shapes appear — drag both to the center at the same time!',
  voiceCue: 'Drag both matching shapes to the center together!',
  voiceComplete: 'Perfect pairing! Your hands move in harmony!',
  voiceSuccess: 'Perfect match!',
  congrats: 'Pair Match Champion!',
} as const;

/** Game 3 — Box Sort · Warehouse bins (circle left, square right — both at once) */
export const BOX_SORT_THEME = {
  title: 'Box Sort',
  subtitle: 'Circle → left bin, square → right bin — use both hands!',
  emoji: '📦',
  gradient: ['#2E1065', '#4C1D95', '#6D28D9', '#8B5CF6'] as [string, string, string, string],
  accent: '#A78BFA',
  accentDark: '#DDD6FE',
  circleColor: '#6366F1',
  squareColor: '#14B8A6',
  leftColor: '#6366F1',
  rightColor: '#14B8A6',
  circleGlow: '#818CF8',
  squareGlow: '#2DD4BF',
  playBorder: 'rgba(167,139,250,0.42)',
  playBg: '#2E1065',
  sparkleColor: '#A78BFA',
  zoneBorder: 'rgba(167,139,250,0.55)',
  backText: '#EDE9FE',
  backBorder: 'rgba(167,139,250,0.38)',
  titleColor: '#F5F3FF',
  subtitleColor: 'rgba(221,214,254,0.9)',
  statLabel: 'rgba(221,214,254,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(167,139,250,0.32)',
  voiceIntro:
    'Welcome to the sorting warehouse! Drag the circle to the left bin and the square to the right bin — both at the same time!',
  voiceCue: 'Circle to left bin, square to right bin — both hands!',
  voiceComplete: 'Sorting superstar! You multitasked both shapes perfectly!',
  voiceSuccess: 'Perfect sorting!',
  congrats: 'Box Sort Champion!',
} as const;

/** Game 4 — Tug Rope · Tug-of-war arena (pull both handles outward together) */
export const TUG_ROPE_THEME = {
  title: 'Tug Rope',
  subtitle: 'Grab both handles — pull outward at the same time!',
  emoji: '🪢',
  gradient: ['#422006', '#78350F', '#92400E', '#FBBF24'] as [string, string, string, string],
  accent: '#FBBF24',
  accentDark: '#FDE68A',
  leftColor: '#F59E0B',
  rightColor: '#EF4444',
  ropeGlow: '#FCD34D',
  playBorder: 'rgba(251,191,36,0.42)',
  playBg: '#422006',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(251,191,36,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(253,230,138,0.9)',
  statLabel: 'rgba(253,230,138,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,191,36,0.32)',
  voiceIntro:
    'Welcome to the tug arena! Grab both rope handles and pull outward at the same time — feel the tension!',
  voiceCue: 'Pull both handles outward together!',
  voiceComplete: 'Strong pull! Your upper body and both arms worked as one!',
  voiceSuccess: 'Perfect tug!',
  congrats: 'Tug Rope Champion!',
} as const;

/** Game 5 — Even Pull · Balance scale (drag both down at the same pace) */
export const EVEN_PULL_THEME = {
  title: 'Even Pull',
  subtitle: 'Drag both weights down — reach the balance line together!',
  emoji: '⚖️',
  gradient: ['#450A0A', '#7F1D1D', '#1E3A8A', '#3B82F6'] as [string, string, string, string],
  accent: '#FB7185',
  accentDark: '#FECDD3',
  leftColor: '#EF4444',
  rightColor: '#3B82F6',
  balanceGlow: '#FDA4AF',
  playBorder: 'rgba(251,113,133,0.42)',
  playBg: '#1A0A14',
  sparkleColor: '#FB7185',
  backText: '#FEE2E2',
  backBorder: 'rgba(251,113,133,0.38)',
  titleColor: '#FFF1F2',
  subtitleColor: 'rgba(254,205,211,0.9)',
  statLabel: 'rgba(254,205,211,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(251,113,133,0.32)',
  voiceIntro:
    'Welcome to the balance scale! Drag both weights down to the balance line — keep both hands moving at the same speed!',
  voiceCue: 'Drag both down together at the same pace!',
  voiceComplete: 'Perfect rhythm! You mastered balanced simultaneous dragging!',
  voiceSuccess: 'Perfect balance!',
  congrats: 'Even Pull Champion!',
} as const;
