import type { RhythmPatternGameConfig } from '@/components/game/occupational/level4/session10/shared/RhythmPatternGame';

export const SHOULDER_TAP_THEME = {
  title: 'Shoulder Tap',
  subtitle: 'Watch cross-body shoulder taps — then copy the pattern!',
  emoji: '👆',
  gradient: ['#052E16', '#14532D', '#166534', '#22C55E'] as [string, string, string, string],
  accent: '#4ADE80',
  accentDark: '#BBF7D0',
  leftColor: '#22C55E',
  rightColor: '#3B82F6',
  crossArc: '#6EE7B7',
  playBorder: 'rgba(74,222,128,0.42)',
  playBg: '#052E16',
  sparkleColor: '#4ADE80',
  backText: '#DCFCE7',
  backBorder: 'rgba(74,222,128,0.38)',
  titleColor: '#F0FDF4',
  subtitleColor: 'rgba(187,247,208,0.9)',
  statLabel: 'rgba(187,247,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(74,222,128,0.32)',
  voiceIntro:
    'Welcome to the body map studio! Watch hand-to-shoulder cross-body taps, then copy the pattern!',
  voiceListen: 'Watch the shoulder tap pattern!',
  voiceCopy: 'Now copy the pattern!',
  voiceComplete: 'Body mapping pro! Your cross-body shoulder taps are perfect!',
  voiceSuccess: 'Perfect tap!',
  voiceFail: 'Try again — watch and copy!',
  congrats: 'Shoulder Tap Champion!',
} as const;

export const SHOULDER_TAP_CONFIG: Omit<RhythmPatternGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'shoulderCross',
  theme: {
    title: SHOULDER_TAP_THEME.title,
    subtitle: SHOULDER_TAP_THEME.subtitle,
    emoji: SHOULDER_TAP_THEME.emoji,
    gradient: SHOULDER_TAP_THEME.gradient,
    accent: SHOULDER_TAP_THEME.accent,
    accentDark: SHOULDER_TAP_THEME.accentDark,
    leftColor: SHOULDER_TAP_THEME.leftColor,
    rightColor: SHOULDER_TAP_THEME.rightColor,
    backText: SHOULDER_TAP_THEME.backText,
    backBorder: SHOULDER_TAP_THEME.backBorder,
    titleColor: SHOULDER_TAP_THEME.titleColor,
    subtitleColor: SHOULDER_TAP_THEME.subtitleColor,
    statLabel: SHOULDER_TAP_THEME.statLabel,
    statValue: SHOULDER_TAP_THEME.statValue,
    statBorder: SHOULDER_TAP_THEME.statBorder,
    playBorder: SHOULDER_TAP_THEME.playBorder,
    playBg: SHOULDER_TAP_THEME.playBg,
    sparkleColor: SHOULDER_TAP_THEME.sparkleColor,
  },
  ttsIntro: SHOULDER_TAP_THEME.voiceIntro,
  ttsComplete: SHOULDER_TAP_THEME.voiceComplete,
  ttsListen: SHOULDER_TAP_THEME.voiceListen,
  ttsCopy: SHOULDER_TAP_THEME.voiceCopy,
  ttsSuccess: SHOULDER_TAP_THEME.voiceSuccess,
  ttsFail: SHOULDER_TAP_THEME.voiceFail,
  congratsMessage: SHOULDER_TAP_THEME.congrats,
  logType: 'tap-shoulder-pattern',
  skillTags: ['body-mapping', 'cross-body-coordination', 'pattern-copying'],
};
