import type { CrossBodySwipeGameConfig } from '@/components/game/occupational/level4/session7/shared/CrossBodySwipeGame';

export const SWIPE_CROSS_THEME = {
  title: 'Swipe Cross',
  subtitle: 'Swipe across your body — opposite direction!',
  emoji: '➡️',
  gradient: ['#450A0A', '#7F1D1D', '#991B1B', '#DC2626'] as [string, string, string, string],
  accent: '#F87171',
  accentDark: '#FECACA',
  trailGlow: '#FB7185',
  arcLeft: '#FCA5A5',
  arcRight: '#F97316',
  playBorder: 'rgba(248,113,113,0.42)',
  playBg: '#450A0A',
  sparkleColor: '#F87171',
  backText: '#FEE2E2',
  backBorder: 'rgba(248,113,113,0.38)',
  titleColor: '#FEF2F2',
  subtitleColor: 'rgba(254,202,202,0.9)',
  statLabel: 'rgba(254,202,202,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(248,113,113,0.32)',
  voiceIntro:
    'Welcome to the wind tunnel! See an arrow, then swipe the opposite way — across your body!',
  voiceCue: 'Swipe across your body in the opposite direction!',
  voiceComplete: 'Powerful cross-body swipes! Your coordination is on fire!',
  voiceSuccess: 'Perfect swipe!',
  voiceMiss: 'Swipe the opposite direction — cross your body!',
  congrats: 'Swipe Cross Champion!',
} as const;

export const SWIPE_CROSS_CONFIG: Omit<CrossBodySwipeGameConfig, 'onBack' | 'onComplete'> = {
  theme: {
    title: SWIPE_CROSS_THEME.title,
    subtitle: SWIPE_CROSS_THEME.subtitle,
    emoji: SWIPE_CROSS_THEME.emoji,
    gradient: SWIPE_CROSS_THEME.gradient,
    accent: SWIPE_CROSS_THEME.accent,
    accentDark: SWIPE_CROSS_THEME.accentDark,
    backText: SWIPE_CROSS_THEME.backText,
    backBorder: SWIPE_CROSS_THEME.backBorder,
    titleColor: SWIPE_CROSS_THEME.titleColor,
    subtitleColor: SWIPE_CROSS_THEME.subtitleColor,
    statLabel: SWIPE_CROSS_THEME.statLabel,
    statValue: SWIPE_CROSS_THEME.statValue,
    statBorder: SWIPE_CROSS_THEME.statBorder,
    playBorder: SWIPE_CROSS_THEME.playBorder,
    playBg: SWIPE_CROSS_THEME.playBg,
    sparkleColor: SWIPE_CROSS_THEME.sparkleColor,
  },
  ttsIntro: SWIPE_CROSS_THEME.voiceIntro,
  ttsComplete: SWIPE_CROSS_THEME.voiceComplete,
  ttsCue: SWIPE_CROSS_THEME.voiceCue,
  ttsSuccess: SWIPE_CROSS_THEME.voiceSuccess,
  ttsMiss: SWIPE_CROSS_THEME.voiceMiss,
  congratsMessage: SWIPE_CROSS_THEME.congrats,
  logType: 'arrow-swipe',
  skillTags: ['cross-body-coordination', 'direction-control', 'visual-motor'],
};
