import type { DualDragGameConfig } from '@/components/game/occupational/level4/session9/shared/DualDragGame';

export const PAIR_MATCH_THEME = {
  title: 'Pair Match',
  subtitle: 'Drag both matching shapes to the center — together!',
  emoji: '🤝',
  gradient: ['#052E16', '#14532D', '#166534', '#22C55E'] as [string, string, string, string],
  accent: '#4ADE80',
  accentDark: '#BBF7D0',
  leftColor: '#22C55E',
  rightColor: '#10B981',
  mergeGlow: '#6EE7B7',
  playBorder: 'rgba(74,222,128,0.42)',
  playBg: '#052E16',
  sparkleColor: '#4ADE80',
  zoneBorder: 'rgba(74,222,128,0.55)',
  backText: '#DCFCE7',
  backBorder: 'rgba(74,222,128,0.38)',
  titleColor: '#F0FDF4',
  subtitleColor: 'rgba(187,247,208,0.9)',
  statLabel: 'rgba(187,247,208,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(74,222,128,0.32)',
  voiceIntro:
    'Welcome to the pair merge zone! Two matching shapes appear — drag both to the center at the same time!',
  voiceCue: 'Drag both matching shapes to the center together!',
  voiceComplete: 'Perfect pairing! Your hands move in harmony!',
  voiceSuccess: 'Perfect match!',
  congrats: 'Pair Match Champion!',
} as const;

export const PAIR_MATCH_CONFIG: Omit<DualDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'matchCenter',
  theme: {
    title: PAIR_MATCH_THEME.title,
    subtitle: PAIR_MATCH_THEME.subtitle,
    emoji: PAIR_MATCH_THEME.emoji,
    gradient: PAIR_MATCH_THEME.gradient,
    accent: PAIR_MATCH_THEME.accent,
    accentDark: PAIR_MATCH_THEME.accentDark,
    leftColor: PAIR_MATCH_THEME.leftColor,
    rightColor: PAIR_MATCH_THEME.rightColor,
    backText: PAIR_MATCH_THEME.backText,
    backBorder: PAIR_MATCH_THEME.backBorder,
    titleColor: PAIR_MATCH_THEME.titleColor,
    subtitleColor: PAIR_MATCH_THEME.subtitleColor,
    statLabel: PAIR_MATCH_THEME.statLabel,
    statValue: PAIR_MATCH_THEME.statValue,
    statBorder: PAIR_MATCH_THEME.statBorder,
    playBorder: PAIR_MATCH_THEME.playBorder,
    playBg: PAIR_MATCH_THEME.playBg,
    sparkleColor: PAIR_MATCH_THEME.sparkleColor,
    zoneBorder: PAIR_MATCH_THEME.zoneBorder,
  },
  ttsIntro: PAIR_MATCH_THEME.voiceIntro,
  ttsComplete: PAIR_MATCH_THEME.voiceComplete,
  ttsCue: PAIR_MATCH_THEME.voiceCue,
  ttsSuccess: PAIR_MATCH_THEME.voiceSuccess,
  congratsMessage: PAIR_MATCH_THEME.congrats,
  logType: 'match-pair',
  skillTags: ['coordination', 'simultaneous-dragging', 'matching'],
};
