/**
 * OT Level 4 Session 2 — Drag Right → Left theme tokens.
 */

/** Game 1 — Return Pass · Sunset away stadium (RTL) */
export const RETURN_PASS_THEME = {
  title: 'Return Pass',
  subtitle: 'Send the ball home — slide from right to left into the net',
  emoji: '⚽',
  gradient: ['#431407', '#7C2D12', '#C2410C', '#FB923C'] as [string, string, string, string],
  accent: '#FDE68A',
  accentDark: '#F59E0B',
  accentCoral: '#FB7185',
  pitchDark: '#14532D',
  pitchLight: '#22C55E',
  pitchLine: 'rgba(255,255,255,0.72)',
  goalGold: '#FDE68A',
  sunsetGlow: 'rgba(251,146,60,0.18)',
  draggableEmoji: '⚽',
  targetEmoji: '🥅',
  playBorder: 'rgba(253,224,71,0.48)',
  playBg: '#166534',
  sparkleColor: '#FDE68A',
  zoneBorder: 'rgba(253,224,71,0.55)',
  voiceIntro: 'Sunset kick-off! Drag the ball from the right and score in the home goal on the left!',
  voiceDrag: 'Slide the ball left across the pitch!',
  voiceComplete: 'What a comeback! Every return pass found the net!',
  voiceMiss: 'Keep it on the pitch — aim for the left goal!',
  voiceScore: 'Home goal!',
  congrats: 'Return Pass Legend!',
} as const;

/** Game 2 — Star Sweep · Cosmic star collection (RTL) */
export const STAR_SWEEP_STARS = ['⭐', '🌟', '✨', '💫'] as const;

export const STAR_SWEEP_THEME = {
  title: 'Star Sweep',
  subtitle: 'Sweep falling stars from the sky into your cosmic bag',
  emoji: '🌌',
  gradient: ['#0F0520', '#1E1B4B', '#4C1D95', '#7C3AED'] as [string, string, string, string],
  accent: '#FCD34D',
  accentDark: '#EAB308',
  accentViolet: '#C4B5FD',
  nebulaPink: '#F472B6',
  spaceDark: '#0F0520',
  bagPurple: '#5B21B6',
  draggableEmoji: '⭐',
  targetEmoji: '🎒',
  playBorder: 'rgba(196,181,253,0.42)',
  playBg: '#1E1033',
  sparkleColor: '#FCD34D',
  zoneBorder: 'rgba(196,181,253,0.45)',
  voiceIntro: 'Welcome to the star field! Sweep each star from the right into your cosmic bag on the left!',
  voiceDrag: 'Slide the star into the bag!',
  voiceComplete: 'The whole galaxy is in your bag! Amazing star sweeping!',
  voiceMiss: 'Guide the star into the cosmic bag on the left!',
  voiceCaught: 'Star caught!',
  congrats: 'Galaxy Collector!',
} as const;

/** Game 3 — Back Track · Glowing forest trail (RTL path follow) */
export const BACK_TRACK_THEME = {
  title: 'Back Track',
  subtitle: 'Follow the glowing trail from the forest edge back home',
  emoji: '🛤️',
  gradient: ['#042F2E', '#0F766E', '#14B8A6', '#2DD4BF'] as [string, string, string, string],
  accent: '#A3E635',
  accentDark: '#65A30D',
  accentAmber: '#FBBF24',
  forestDark: '#042F2E',
  forestMid: '#134E4A',
  pathGlow: '#A3E635',
  pathCore: '#84CC16',
  moss: '#166534',
  lantern: '#FDE68A',
  draggableEmoji: '📦',
  backText: '#CCFBF1',
  backBorder: 'rgba(45,212,191,0.35)',
  titleColor: '#F0FDFA',
  subtitleColor: 'rgba(153,246,228,0.9)',
  statLabel: 'rgba(153,246,228,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(45,212,191,0.3)',
  playBorder: 'rgba(163,230,53,0.42)',
  playBg: '#0C3530',
  sparkleColor: '#A3E635',
  pathColor: '#A3E635',
  voiceIntro: 'Welcome to the forest trail! Follow the glowing path from the right all the way back home on the left!',
  voiceDrag: 'Trace the trail back home!',
  voiceComplete: 'Trail master! You found your way home on every path!',
  voiceMiss: 'Stay on the glowing trail — reach the home camp!',
  voiceArrived: 'Home safe!',
  congrats: 'Trail Guide Legend!',
} as const;

/** Game 4 — Cross Reach · Split mirror gym (RTL cross-body drag) */
export const CROSS_REACH_THEME = {
  title: 'Cross Reach',
  subtitle: 'Reach across your body — drag from right to the mirror catch on the left',
  emoji: '🤲',
  gradient: ['#1E1035', '#4C1D95', '#9A3412', '#FB923C'] as [string, string, string, string],
  accent: '#38BDF8',
  accentDark: '#7DD3FC',
  accentWarm: '#FB923C',
  accentCoral: '#FDBA74',
  studioDark: '#1A1625',
  mirrorLine: 'rgba(255,255,255,0.55)',
  leftGlow: '#0EA5E9',
  rightGlow: '#F97316',
  draggableEmoji: '✋',
  targetEmoji: '🪞',
  playBorder: 'rgba(56,189,248,0.42)',
  playBg: '#1A1625',
  sparkleColor: '#38BDF8',
  zoneBorder: 'rgba(56,189,248,0.45)',
  voiceIntro:
    'Welcome to the mirror studio! Use your right hand to reach across and land the orb in the mirror catch on the left!',
  voiceDrag: 'Reach across — slide to the left mirror!',
  voiceComplete: 'Amazing cross-body control! Your brain and hand are in perfect sync!',
  voiceMiss: 'Reach farther across — aim for the mirror catch on the left!',
  voiceReached: 'Crossed!',
  congrats: 'Cross Reach Champion!',
} as const;

/** Game 5 — Pattern Run · Neon circuit track (RTL pattern trace) */
export const PATTERN_RUN_THEME = {
  title: 'Pattern Run',
  subtitle: 'Race the neon circuit — trace zigzag, wave, or step patterns right to left',
  emoji: '🏁',
  gradient: ['#0F0A1A', '#1E0A3C', '#7C0A6E', '#EC4899'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#A78BFA',
  accentPink: '#F472B6',
  accentGold: '#FACC15',
  circuitDark: '#12081F',
  gridLine: 'rgba(34,211,238,0.12)',
  pathGlow: '#F472B6',
  pathCore: '#EC4899',
  finishGreen: '#4ADE80',
  draggableEmoji: '💠',
  backText: '#F5D0FE',
  backBorder: 'rgba(244,114,182,0.38)',
  titleColor: '#FAF5FF',
  subtitleColor: 'rgba(233,213,255,0.9)',
  statLabel: 'rgba(233,213,255,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(244,114,182,0.32)',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#12081F',
  sparkleColor: '#22D3EE',
  pathColor: '#F472B6',
  voiceIntro:
    'Welcome to the neon circuit! Trace each zigzag, wave, or step pattern from the start gate all the way to the finish on the left!',
  voiceDrag: 'Follow the neon pattern to the finish!',
  voiceComplete: 'Circuit champion! You traced every pattern like a pro!',
  voiceMiss: 'Stay on the neon path — trace the full pattern to the finish line!',
  voiceTraced: 'Pattern traced!',
  congrats: 'Pattern Run Legend!',
} as const;

export const PATTERN_RUN_VARIANT_EMOJI: Record<string, string> = {
  ZIGZAG: '⚡',
  WAVE: '〰️',
  STEPS: '🪜',
};
