import type { DualTapGameConfig } from '@/components/game/occupational/level4/session4/shared/DualTapGame';

export const DUO_KEYS_THEME = {
  title: 'Duo Keys',
  subtitle: 'Strike both ivory keys together before the spotlight fades!',
  emoji: '🎹',
  gradient: ['#1C0A0A', '#3D1515', '#5C2E0A', '#78350F'] as [string, string, string, string],
  accent: '#F59E0B',
  accentDark: '#FDE68A',
  accentGold: '#FBBF24',
  stageDark: '#1C0A0A',
  curtainRed: '#7F1D1D',
  spotlight: '#FEF3C7',
  leftColor: '#FFFBEB',
  rightColor: '#FEF9C3',
  keyPressed: '#FBBF24',
  leftEmoji: '♩',
  rightEmoji: '♪',
  leftNote: 'C',
  rightNote: 'G',
  playBorder: 'rgba(245,158,11,0.45)',
  playBg: '#1C0A0A',
  sparkleColor: '#FBBF24',
  backText: '#FEF3C7',
  backBorder: 'rgba(245,158,11,0.38)',
  titleColor: '#FFFBEB',
  subtitleColor: 'rgba(254,243,199,0.88)',
  statLabel: 'rgba(254,243,199,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(245,158,11,0.32)',
  voiceIntro:
    'Welcome to the concert hall! Press both piano keys at the same time before the spotlight goes out!',
  voiceCue: 'Press both keys together!',
  voiceComplete: 'Bravo! You played every chord in perfect harmony!',
  voiceSuccess: 'Beautiful chord!',
  voiceMiss: 'Too slow — press both keys before time runs out!',
  congrats: 'Duo Keys Virtuoso!',
} as const;

export const DUO_KEYS_CONFIG: Omit<DualTapGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'keys',
  theme: {
    title: DUO_KEYS_THEME.title,
    subtitle: DUO_KEYS_THEME.subtitle,
    emoji: DUO_KEYS_THEME.emoji,
    gradient: DUO_KEYS_THEME.gradient,
    accent: DUO_KEYS_THEME.accent,
    accentDark: DUO_KEYS_THEME.accentDark,
    leftColor: DUO_KEYS_THEME.leftColor,
    rightColor: DUO_KEYS_THEME.rightColor,
    leftEmoji: DUO_KEYS_THEME.leftEmoji,
    rightEmoji: DUO_KEYS_THEME.rightEmoji,
    targetStyle: 'key',
    backText: DUO_KEYS_THEME.backText,
    backBorder: DUO_KEYS_THEME.backBorder,
    titleColor: DUO_KEYS_THEME.titleColor,
    subtitleColor: DUO_KEYS_THEME.subtitleColor,
    statLabel: DUO_KEYS_THEME.statLabel,
    statValue: DUO_KEYS_THEME.statValue,
    statBorder: DUO_KEYS_THEME.statBorder,
    playBorder: DUO_KEYS_THEME.playBorder,
    playBg: DUO_KEYS_THEME.playBg,
    sparkleColor: DUO_KEYS_THEME.sparkleColor,
  },
  ttsIntro: DUO_KEYS_THEME.voiceIntro,
  ttsComplete: DUO_KEYS_THEME.voiceComplete,
  ttsCue: DUO_KEYS_THEME.voiceCue,
  ttsSuccess: DUO_KEYS_THEME.voiceSuccess,
  ttsMiss: DUO_KEYS_THEME.voiceMiss,
  congratsMessage: DUO_KEYS_THEME.congrats,
  logType: 'piano-keys',
  skillTags: ['hand-synchronization', 'two-hand-tap'],
};
