import type { ReversePathDragGameConfig } from '@/components/game/occupational/level4/session2/shared/ReversePathDragGame';

export const PATTERN_RUN_THEME = {
  title: 'Pattern Run',
  subtitle: 'Race the neon circuit — trace zigzag, wave, or step patterns right to left',
  emoji: '🏁',
  gradient: ['#0F0A1A', '#1E0A3C', '#7C0A6E', '#EC4899'] as [string, string, string, string],
  accent: '#22D3EE',
  accentDark: '#A78BFA',
  accentPink: '#F472B6',
  accentGold: '#FACC15',
  circuitDark: '#12081F',
  gridLine: 'rgba(34,211,238,0.12)',
  pathGlow: '#F472B6',
  pathCore: '#EC4899',
  finishGreen: '#4ADE80',
  draggableEmoji: '💠',
  backText: '#F5D0FE',
  backBorder: 'rgba(244,114,182,0.38)',
  titleColor: '#FAF5FF',
  subtitleColor: 'rgba(233,213,255,0.9)',
  statLabel: 'rgba(233,213,255,0.75)',
  statValue: '#FFFFFF',
  statBorder: 'rgba(244,114,182,0.32)',
  playBorder: 'rgba(34,211,238,0.42)',
  playBg: '#12081F',
  sparkleColor: '#22D3EE',
  pathColor: '#F472B6',
  voiceIntro:
    'Welcome to the neon circuit! Trace each zigzag, wave, or step pattern from the start gate all the way to the finish on the left!',
  voiceDrag: 'Follow the neon pattern to the finish!',
  voiceComplete: 'Circuit champion! You traced every pattern like a pro!',
  voiceMiss: 'Stay on the neon path — trace the full pattern to the finish line!',
  voiceTraced: 'Pattern traced!',
  congrats: 'Pattern Run Legend!',
} as const;

export const PATTERN_RUN_VARIANT_EMOJI: Record<string, string> = {
  ZIGZAG: '⚡',
  WAVE: '〰️',
  STEPS: '🪜',
};

export const PATTERN_RUN_CONFIG: Omit<ReversePathDragGameConfig, 'onBack' | 'onComplete'> = {
  mode: 'patternDrag',
  theme: {
    title: PATTERN_RUN_THEME.title,
    subtitle: PATTERN_RUN_THEME.subtitle,
    emoji: PATTERN_RUN_THEME.emoji,
    gradient: PATTERN_RUN_THEME.gradient,
    accent: PATTERN_RUN_THEME.accent,
    accentDark: PATTERN_RUN_THEME.accentDark,
    pathColor: PATTERN_RUN_THEME.pathColor,
    draggableEmoji: PATTERN_RUN_THEME.draggableEmoji,
    backText: PATTERN_RUN_THEME.backText,
    backBorder: PATTERN_RUN_THEME.backBorder,
    titleColor: PATTERN_RUN_THEME.titleColor,
    subtitleColor: PATTERN_RUN_THEME.subtitleColor,
    statLabel: PATTERN_RUN_THEME.statLabel,
    statValue: PATTERN_RUN_THEME.statValue,
    statBorder: PATTERN_RUN_THEME.statBorder,
    playBorder: PATTERN_RUN_THEME.playBorder,
    playBg: PATTERN_RUN_THEME.playBg,
    sparkleColor: PATTERN_RUN_THEME.sparkleColor,
  },
  ttsIntro: PATTERN_RUN_THEME.voiceIntro,
  ttsComplete: PATTERN_RUN_THEME.voiceComplete,
  ttsDrag: PATTERN_RUN_THEME.voiceDrag,
  ttsMiss: PATTERN_RUN_THEME.voiceMiss,
  ttsGoal: PATTERN_RUN_THEME.voiceTraced,
  congratsMessage: PATTERN_RUN_THEME.congrats,
  logType: 'pattern-drag',
  skillTags: ['motor-planning', 'drag-right-left'],
};
